### ISSUE TITLE
about page contains "about" string at bottom left

### ISSUE THREAD

**Issue by wolexa** [zzossig/hugo-theme-zzo#10]
At the bottom left of the about page appears the string "about page". 
![HugoZzoAbout](https://user-images.githubusercontent.com/57860851/69006581-3aa28b80-0931-11ea-80a3-6a4e64eedbff.gif)
This is driven by the block
```
<main class="main">
  about page
</main>

```
in layouts/about/single.html. What is the intention of that block here since all the "real" content is added above that part of the final page?

**Comment by zzossig** [comment]
Actually, that part do nothing. Should be deleted. I uploaded new version. Can you check?

**Comment by wolexa** [comment]
I checked the new version, and it works, i.e. the "about page" string does not appear anymore. Thanks!

Looking at the single.html file, however, in line 6 I noticed the end of a span tag, which doesn't have a corresponding starting tag. I guess this line can be deleted.

**Comment by zzossig** [comment]
Ah Ok I'll delete it!
