### ISSUE TITLE
[Suggestion] Have an ability to provide multiple version of code (or other cases)

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#100]
I saw this : https://themes.gohugo.io//theme/hugo-book/docs/shortcodes/tabs/

The use case I see for something like this, in my case would be for providing code in two languages i.e on Android we have Java and Kotlin. Being able to provide both in the same spot would be helpful.

Also helpful to provide some command that works for Linux and another for Windows but to do the same thing.

![Peek 2020-01-21 01-10](https://user-images.githubusercontent.com/2096087/72765078-f8285400-3bea-11ea-9db3-a1d4fd52d4bb.gif)

Your thoughts on this?

For implementation you can probably take the same from above theme. 

I really like that theme and will probably use it to write my own book :sweat_smile:

**Comment by zzossig** [comment]
good morning (or evening?)
It looks like something like this one in the Hugo homepage.
![주석 2020-01-21 091555](https://user-images.githubusercontent.com/52706977/72765206-a6a1b880-3c2e-11ea-9f3e-e4c3f6b26e85.png)

Ok, It would be a good feature😋

**Comment by nisrulz** [comment]
I like the version that theme has, the one I linked.

And it is 1:22 am here. I work late on personal stuff because I work during the day :eyes:

**Comment by zzossig** [comment]
You better take a rest!
All the bug will be fixed when you wake up

**Comment by zzossig** [comment]
This is our new shortcode. `codes` `code`

`````
{{< codes java javascript >}}
  {{< code >}}
  ```java
  System.out.println('Hello World!');
  ```
  {{< /code >}}
  {{< code >}}
  ```javascript
  console.log('Hello World!');
  ```
  {{< /code >}}
{{< /codes >}}
`````

Actually, this is not the general purpose. Only for the multiple version of code

**Comment by nisrulz** [comment]
Do you have a screenshot or did you put it on your blog? or maybe the question is did you put it in the example website so I can see it?

**Comment by zzossig** [comment]
Yes, I just uploaded my test post to my blog [https://zzossig.io](https://zzossig.io)

**Comment by nisrulz** [comment]
![awesome](https://media.giphy.com/media/26ufdipQqU2lhNA4g/giphy.gif)

This is sooo awesome! Even the copy button works for each language differently! 

This is a going to make life so much easier for me!

Thank you 🎉

**Comment by zzossig** [comment]
Thx, But I didn't test it much.
And I'll add general-purpose tab when I have more time

**Comment by zzossig** [comment]
I added general purpose tabs.
![zzc](https://user-images.githubusercontent.com/52706977/73009421-e8f80f00-3e53-11ea-824b-a9dda375d6c0.png)

usage:
`````
{{< tabs Windows MacOS Ubuntu >}}
  {{< tab >}}

  ### Windows section

  ```javascript
  console.log('Hello World!');
  ```

  {{< /tab >}}
  {{< tab >}}

  ### MacOS section

  Hello world!
  {{< /tab >}}
  {{< tab >}}

  ### Ubuntu section

  Great!
  {{< /tab >}}
{{< /tabs >}}
`````

**Comment by nisrulz** [comment]
Got it. Closing this for now.

Thanks!
