### ISSUE TITLE
Deprecation Warning regarding Page.URL when rendering pages

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#101]
While running the hugo server everytime I make a change, the terminal lists the below warning.

```bash
WARN 2020/01/21 01:16:34 Page.URL is deprecated and will be removed in a future release. Use .Permalink or .RelPermalink. If what you want is the front matter URL value, use .Params.url
```

**Comment by zzossig** [comment]
Yes, should be fixed!

**Comment by zzossig** [comment]
I fixed the deprecated code.
Have confirmed that other `.URL` is still safe. 
So I just removed `Page.URL`

**Comment by nisrulz** [comment]
Thank you 😄

**Comment by zzossig** [comment]
Ok, I'm waiting for your next homework😄

**Comment by nisrulz** [comment]
I must say, the theme you have built is really good and I appreciate your efforts in making changes to it. I will contribute more once I get used to the way this thing works. I am also learning with you. I read your commits to understand the changes. 

From what I understand, this theme covers almost all the good options people in tech community need as you can see from my blog.

Thank you for taking the time to make that happen. I will be helping you maintain this as much as I can since I find it really useful + now my blog depends on this 😅

**Comment by zzossig** [comment]
Haha, thanks a lot.
But my code might be not as good as other people.
I have to confess that, I should have better-structure css, but it didn't.
So, it is getting bigger and bigger.
Anyway, It is interesting that people around the world use my code 😋

**Comment by nisrulz** [comment]
This is fixed.Closing.
