### ISSUE TITLE
[Suggestion] Table of contents should be in the white space outside the content area

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#102]
![Screenshot from 2020-01-21 01-15-41](https://user-images.githubusercontent.com/2096087/72765346-32debc00-3bec-11ea-970e-7c9efa1386c1.jpg)

The reasoning behind it is that when the table of contents is enabled it occupies a large portion of the content area.

![Peek 2020-01-21 01-21](https://user-images.githubusercontent.com/2096087/72765394-7e916580-3bec-11ea-97ec-31e193ae1d8d.gif)

**Comment by zzossig** [comment]
I prefer a small content area.
I'll add an option to position it to the outside the content area

**Comment by zzossig** [comment]
We have another param `tocPosition`

Your `params.toml` file,
```toml
...
tocPosition: outer # inner / outer
...
```

**Comment by nisrulz** [comment]
Question: When the TOC is outside the content section, in the "gutter" region as it is called, then when someone resizes the browser i.e the width is small enough then the TOC should not show at all. 

Why?

Because it cannot fit in smaller screens. TOC should only show when the there is enough screen space for it to show in the "gutter" region.

Thoughts?

**Comment by zzossig** [comment]
We already hide the `toc` when screen is small.
![gg](https://user-images.githubusercontent.com/52706977/72790990-ec37a300-3c79-11ea-9fec-9219fc24cead.png)
Did you mean this content area is too small?

**Comment by nisrulz** [comment]
Yes, in the small screen the extra space is gone. I will need to re-check. If the TOC is hidden in smaller screen then everything is good 🎉

**Comment by nisrulz** [comment]
Ok, so I ran this on my blog.

Found 2 problems
when using "inner"

![inner](https://user-images.githubusercontent.com/2096087/72833298-d2e92380-3c86-11ea-9dcc-e2060dab9392.gif)

when using "outer"

![outer](https://user-images.githubusercontent.com/2096087/72833310-da103180-3c86-11ea-9df3-78455b339707.gif)

I imagined "outer" will have the toc all the time on side and people can enable disable it using the switch. Right now it is going in and out based on scrolling :thinking:

**Comment by zzossig** [comment]
I fixed some issues.
The problem in the gif above, you need to set the Goldmark toc config

In your config.toml file,
```toml
...
[markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 3
...
```

I found that in your post, the max title level is 3, and min title level is 4.

I know that every post doesn't have the same title level.
I tried to dynamically set the title level. But, I can't find an easy way to do this.
So I asked it to the Hugo community [https://discourse.gohugo.io/t/can-i-get-the-goldmark-config-value/22947](https://discourse.gohugo.io/t/can-i-get-the-goldmark-config-value/22947)

**Comment by nisrulz** [comment]
Interesting find. I did not know this. I will also investigate on my end. Thank you 😄

**Comment by nisrulz** [comment]
I see your test page and you kind of fixed the TOC section. When I resize the page, I see it is gone, but the switch with text still remains. I think it should be gone too.

<img width="726" alt="Screen Shot 2020-01-22 at 10 16 45 AM" src="https://user-images.githubusercontent.com/2096087/72881122-7591b880-3d00-11ea-9289-6ae4b232b56d.png">

What do you think about this?

**Comment by zzossig** [comment]
Ah, I didn't notice it. It should be gone!

**Comment by nisrulz** [comment]
Everything looks fixed by now. Thank you :+1: 

I just noticed one small case. This is when there is no titles in the page, then "Whats in this page" should also go away.

![Screenshot from 2020-01-23 19-26-51](https://user-images.githubusercontent.com/2096087/73012317-51c09680-3e16-11ea-8631-9bfc469f2ac4.png)

**Comment by zzossig** [comment]
It is already gone away.

**Comment by zzossig** [comment]
It's fixed now!
But I found another bug.
When we use the newly added `tabs` shortcode, toc not properly highlighted.
I'll investigate more about it.

**Comment by nisrulz** [comment]
I think you should open new issue for that and this issue should be closed.

**Comment by zzossig** [comment]
Oh, I just uploaded the code.
All fixed now

**Comment by nisrulz** [comment]
Closing this issue then, since it is fixed!
