### ISSUE TITLE
Signal app icon

### ISSUE THREAD

**Issue by kvandenbrande** [zzossig/hugo-theme-zzo#103]
Since more people are dropping Whatsapp and going to Signal maybe best to add that icon as well. (no hurry mate) 
This is the icon:
https://upload.wikimedia.org/wikipedia/commons/8/88/Signal_Icon.png

**Comment by zzossig** [comment]
Ok, I'll find the icon

**Comment by zzossig** [comment]
I can find the Whatsapp icon but what is the Signal icon?
Is this a service? 
Or you personally made the icon?

**Comment by kvandenbrande** [comment]
No it's an application like Whatsapp, website: https://www.signal.org/
I found this vector image of it.  https://www.flaticon.com/free-icon/signal_906383?term=signal%20messenger&page=1&position=1

**Comment by zzossig** [comment]
Oh, Ok! I'll find one or make it😋

**Comment by nisrulz** [comment]
Just to mention, most people who don't use Whatsapp actually move to Telegram which is the obvious choice. Signal is on the same list, but it isn't as famous as Telegram.

**Comment by kvandenbrande** [comment]
This isn't the place to debate your chat preferences.
You can use your telegram, I will stick with a fully open source client as
Signal.

**Comment by nisrulz** [comment]
If it sounded like a debate about preference of chat client one uses, then I might have worded it wrong. 

I wanted to highlight that this issue can be used to add a Telegram icon too along with Signal. 

It is a theme, it allows to choose what preferences an individual wants, so my voice wouldn't change anything for anyone except myself anyways :man_shrugging:

**Comment by zzossig** [comment]
@kvandenbrande 
I add `WhatsApp` and `signal app ` both.
After update the theme, set the param in the params.toml file like this

```toaml
...
[socialOptions]
  ...
  signal = ""
```

**Comment by kvandenbrande** [comment]
Thx mate
