### ISSUE TITLE
[Suggestion] Only allow setting the username for social links in params.toml file

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#104]
![Screenshot from 2020-01-24 13-51-44](https://user-images.githubusercontent.com/2096087/73070499-bcbeab80-3eb0-11ea-92f3-109ed3fb7d66.png)

Right now the whole URL is being passed in the param.toml file.

This has a side effect: The theme wouldn't be able to make use of using the username right away.
For instance in the twitter share button, the link loads up the author name instead of the twitter username in the `via` part.

![Screenshot from 2020-01-24 13-54-02](https://user-images.githubusercontent.com/2096087/73070608-014a4700-3eb1-11ea-9841-44606741bccf.png)

My username for twitter is `@nisrulz`.

One can work around this by extracting the username from the path string. However, if we just take in username then it becomes simpler for other usecases too related to social media actions.

Hard coding the base URL also means that the theme works for people out of the box. They just need to fill in their usernames.

Thoughts?

**Comment by nisrulz** [comment]
The corresponding code for twitter share button link is below (inside the share.html file)

```
{{ with $ctx.Params.author }}&via={{ . }}{{ end }}"
```

which would become, if changed to below (I guess):

```
{{ with "twitter"  }}&via={{ . }}{{ end }}"
```

**Comment by zzossig** [comment]
Ok, the user name can be different from each social media.
It's better to make the relevant param as you suggest

**Comment by nisrulz** [comment]
You are right about changing params.toml

Can we extract the username then ?

**Comment by zzossig** [comment]
I suggest that just change the `share` data structure as we want.
Something like this

```
...
[share]
  - facebook:
     - username: abc
  - twitter:
    - via: abc
...
```

**Comment by nisrulz** [comment]
Interesting. That sounds like a good solution. I did not think about it.

**Comment by zzossig** [comment]
I'll make the data structure something like the above.
Just now, I'll apply it twitter

**Comment by zzossig** [comment]
I changed the `share` data structure
Now, you can do like this.

`params.toml` file
```
...
[[share]]
  name = "facebook"
  username = "zzossig"
  
[[share]]
  name = "twitter"
  username = "zzossig"
```

**Comment by nisrulz** [comment]
![Screenshot from 2020-01-24 15-57-27](https://user-images.githubusercontent.com/2096087/73078334-41fe8c00-3ec2-11ea-8167-b1ce0a559a9f.png)

**Comment by zzossig** [comment]
Did you do it on the localhost?

**Comment by nisrulz** [comment]
Yes, I did it on the localhost. It was working earlier though on local host.

Also you can use this for getting share url template: http://sharelinkgenerator.com/

**Comment by zzossig** [comment]
The Facebook share button never worked on the `localhost`.
I checked that the URL is accurately connected to the button.

When you inspect the Facebook component and decode the URL,
![주석 2020-01-25 025724](https://user-images.githubusercontent.com/52706977/73092330-c3383c00-3f1f-11ea-8321-98b0aa213deb.png)

you can get this text which is the right URL for the share button.
```
https://www.facebook.com/sharer/sharer.php?u=http://localhost:4846/posts/javascript/ball_with_mouse/
```

Just the localhost is the problem.
And I changed the share button design😋

**Comment by nisrulz** [comment]
Can confirm it is working when published. Just pushed the changes.

Thank you :)

**Comment by zzossig** [comment]
Oops, I didn't check the donation button.
![주석 2020-01-25 031947](https://user-images.githubusercontent.com/52706977/73093324-9d139b80-3f21-11ea-8149-dec2372eee63.png)

**Comment by zzossig** [comment]
I changed the donation button too.
![주석 2020-01-25 032655](https://user-images.githubusercontent.com/52706977/73093763-8b7ec380-3f22-11ea-955c-5431a81ce478.png)

**Comment by mrfoxie** [comment]
> I changed the `share` data structure
> Now, you can do like this.
> 
> `params.toml` file
> 
> ```
> ...
> [[share]]
>   name = "facebook"
>   username = "zzossig"
>   
> [[share]]
>   name = "twitter"
>   username = "zzossig"
> ```

I added 3 sharing platforms but it's giving me error all the time here is the link [Live site ](https://mistrysiddh.tk) I just added username but everytime it's shows error
