### ISSUE TITLE
Wrong list-style-type in expand shortcode

### ISSUE THREAD

**Issue by zzossig** [zzossig/hugo-theme-zzo#106]
[https://github.com/zzossig/hugo-theme-zzo/issues/105#issuecomment-578400570](https://github.com/zzossig/hugo-theme-zzo/issues/105#issuecomment-578400570)

**Comment by zzossig** [comment]
@ndgnuh
It's fixed now😃

**Comment by ndgnuh** [comment]
![image](https://user-images.githubusercontent.com/33273948/73121836-14dcd700-3fb1-11ea-8ec9-e42b55c7d3b7.png)

The list's still using the title font. Is this a expected behavior?

**Comment by zzossig** [comment]
Oops No,
Will be fixed soon

**Comment by zzossig** [comment]
@ndgnuh 
It is fixed now😃

**Comment by ndgnuh** [comment]
Awesome, thank you.

**Comment by zzossig** [comment]
Thanks for the issue!
I can't wait to fix bugs😡
