### ISSUE TITLE
Theme selector still visible on About and Posts when enableThemeChange is false

### ISSUE THREAD

**Issue by ralius18** [zzossig/hugo-theme-zzo#11]
Theme selector footer is still visible on About and Posts pages (and likely similar pages) when enableThemeChange config options is set to false.
When it is visible, the selector still contains all themes originally in themeOptions array, regardless of how many are actually there in the file.

**Comment by zzossig** [comment]
I can't reproduce this. Works well on my end. Are you edited the enableThemeChange param at root/config/_default/params.toml file?

**Comment by ralius18** [comment]
Correct, enableThemeChange was set to false in config/_default/params.toml file.

Seems to have resolved itself now, but I could reproduce it reliably when building the site and deploying static files instead of running a hugo server.
