### ISSUE TITLE
IE11 - code display is broken

### ISSUE THREAD

**Issue by VictorZakharov** [zzossig/hugo-theme-zzo#110]
It looks much better in the latest version, I even took out half of the patches I put for IE11 specifically. However, this issue with code layout - I tried to fix, but could not find a good/stable solution. The problem is visible on your website also (when viewing in IE11):
https://zzossig.io/posts/javascript/ball_with_mouse/

1. First line number in code snippet is misaligned.
2. Weird bottom margin/padding at the bottom of the snippet.

Please see below screenshot.

![image](https://user-images.githubusercontent.com/8978766/73129243-c6c5d480-3fac-11ea-9dc7-2f5c022b1186.png)

**Comment by zzossig** [comment]
@VictorZakharov
It's fixed now with this code. 
https://github.com/zzossig/hugo-theme-zzo/commit/9ee37b85dcbab4c2d34b623ba5ebbb5825518916#diff-da6a67c304b4f34da3d66dc01d7a7d41R74

**Comment by VictorZakharov** [comment]
Thanks @zzossig , it's fine now.
