### ISSUE TITLE
In the post page, we can't change the language

### ISSUE THREAD

**Issue by xiaohao890809** [zzossig/hugo-theme-zzo#111]
In the post page, we can't change the language....

![image](https://user-images.githubusercontent.com/9626465/73161914-8fc7fe00-4127-11ea-890a-dc98a93c7e3b.png)

**Comment by zzossig** [comment]
That is because you don't have any posts in that language.
Make your MD file like `post/mypost.zh.md`

**Comment by xiaohao890809** [comment]
> That is because you don't have any posts in that language.
> Make your MD file like `post/mypost.zh.md`

Got it, thank you!
