### ISSUE TITLE
How to rename "Galleries" to other words...

### ISSUE THREAD

**Issue by xiaohao890809** [zzossig/hugo-theme-zzo#112]
Hi, I want to rename the Galleries to other words in the gallery page, but I can't find where to replace the words in the whole dirs.

![image](https://user-images.githubusercontent.com/9626465/73162430-bc304a00-4128-11ea-9629-5ffff4313196.png)

**Comment by zzossig** [comment]
Find the file at `root/content/gallery/_index.md`
Edit `title` in that file like this.

```yaml
---
title: my awesome gallery
...
---
```

**Comment by xiaohao890809** [comment]
> Find the file at `root/content/gallery/_index.md`
> Edit `title` in that file like this.
> 
> ```yaml
> ---
> title: my awesome gallery
> ...
> ---
> ```

Ok, I create the file as you direct, it works. 
Thank you!
