### ISSUE TITLE
[Suggestion] add RTL support (right to left ) for rtl languages like arabic and farsi

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#113]
I would like to try your beautiful Hugo theme on my blog because it has multiple language support and my blog has English and Farsi so since Farsi is a right to left language, I got some issues with that.
so if it is possible, please add "RTL direction" and "right-align" for this theme Thank you.

**Comment by zzossig** [comment]
Did you tried to set param `languagedir` ?

`params.toml` file
```
...
languagedir = "rtl"
...
```

**Comment by Gictorbit** [comment]
omg I didn't know that, it's like magic
you're my hero, thank u

**Comment by zzossig** [comment]
Thanks for using the theme.
We can close this issue now
