### ISSUE TITLE
Inline mathjax function $ not working

### ISSUE THREAD

**Issue by xiaohao890809** [zzossig/hugo-theme-zzo#114]
When I turn on the mathjax, 
the $ a + b = c $ doesn't work...
but $$ a + b = c $$ works.

![image](https://user-images.githubusercontent.com/9626465/73181761-ccf5b580-4152-11ea-9529-0e451224b177.png)

**Comment by zzossig** [comment]
I'll find a way to solve it.

**Comment by zzossig** [comment]
$ is working now.
Update the theme and check again

**Comment by xiaohao890809** [comment]
> $ is working now.
> Update the theme and check again

Yes, it's working now.
Tks.

**Comment by sim590** [comment]
I am trying out mathjax right now and I'm noticing issues with inline math. See the following screenshot:

![espace](https://user-images.githubusercontent.com/4147254/75805286-8c8be780-5d4f-11ea-9299-1777690e1e71.png)

Some blank space is inserted at the end of the expressions and the expressions themselves are displayed too big. It seems like `\displaystyle` was used to [display the inline expressions as if they were in display math mode][displaystyle]. If I instead use Katex, the blank spaces are gone and the size is reasonable, but I can't figure out how to make display math line expression. For exemple:

```
$$
f(n) =
\begin{array}{c}
  0               & \text{si}\ n=0\\\\
  1               & \text{si}\ n=1\\\\
  f(n-1) + f(n-2) & \text{sinon}
\end{array}
$$
```

This renders OK with mathjax, but renders as the following with katex...

![tex](https://user-images.githubusercontent.com/4147254/75805459-e2f92600-5d4f-11ea-81ca-900c7f9cdd38.png)


[displaystyle]: https://tex.stackexchange.com/questions/32824/show-inline-math-as-if-it-were-display-math-and-vice-versa
