### ISSUE TITLE
some CSS conflict appears after setting "languagedir" to "rtl" in parms.toml

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#115]
since my blog has multiple language `farsi` and `english` and farsi is a `rtl` language, I added `languagedir` to `rtl` in languages.toml config file , here is content of my config file:
```
[en]
  languageName = "English"
  weight = 1
  languagedir = "ltr"

[fa]
  languageName = "Farsi"
  weight = 2
  languagedir = "rtl"
```
and after that when I switch to farsi some css conflict happens 
one of theme is in mobile responsive menu bar:
in farsi mode:
![image](https://user-images.githubusercontent.com/34630603/73210918-7b542780-4160-11ea-8bda-b028d71997bd.png)
in english mode:
![image](https://user-images.githubusercontent.com/34630603/73211006-a50d4e80-4160-11ea-9a7b-7c5aa61e643f.png)
another one is about search bar left margin
![image](https://user-images.githubusercontent.com/34630603/73211156-eef63480-4160-11ea-857a-23fd88d6bce1.png)
and archive time line
![image](https://user-images.githubusercontent.com/34630603/73211211-0df4c680-4161-11ea-99a0-3bd53bd3c437.png)
but in english mode is fine
![image](https://user-images.githubusercontent.com/34630603/73211266-27960e00-4161-11ea-9006-022ca502bbb5.png)
and toc margin and writer information margin
![image](https://user-images.githubusercontent.com/34630603/73211451-852a5a80-4161-11ea-9fe6-26b2befdf4e3.png)

**Comment by zzossig** [comment]
Ok, thanks for the detailed explanation.
This will be fixed soon

**Comment by Gictorbit** [comment]
ok thanks

**Comment by zzossig** [comment]
I made some changes.
Can you update the theme and check again?

**Comment by Gictorbit** [comment]
oh thank you so much seems all the above problems fixed
please keep this open, I will check all components and if wasn't any bug I'll close it. good job thanks

**Comment by Gictorbit** [comment]
another little issue is about bio, with margin in `RTL` mode
![image](https://user-images.githubusercontent.com/34630603/73239172-9b133c00-41b0-11ea-9aa0-54d5f620215e.png)
and in post detail with `min read`, the position of min read value jumps to the first of line
this problem happens in home page and in `example.com/fa/posts` only, not in post content
![image](https://user-images.githubusercontent.com/34630603/73239599-da8e5800-41b1-11ea-87ac-105fee312bdb.png)
the correct position should be like this:
![image](https://user-images.githubusercontent.com/34630603/73240189-7371a300-41b3-11ea-9f8a-744b4ff1cf23.png)

**Comment by zzossig** [comment]
![주석 2020-01-28 154911](https://user-images.githubusercontent.com/52706977/73241576-c49a8a80-41e5-11ea-8ecb-eab5a906d03e.png)
What is the collect one
1. 3 min read
2. min read 3

1? or 2?

**Comment by Gictorbit** [comment]
in farsi:
-----------------
‍‍min = دقیقه
read = خواندن
-----------------
and correct one in farsi is 
------------------
‍read 1 min or
خواندن 1 دقیقه
------------------
but according to your question, I think 2 can be compatible with all languages

**Comment by zzossig** [comment]
hmm, I think `read 1 min` is not natively supported by browsers.
Anyway, I made some changes. Check again😋

**Comment by Gictorbit** [comment]
above problems fixed thanks :1st_place_medal: :+1:

**Comment by Gictorbit** [comment]
in RTL, markdown lists need the right margin. here is the latest post of my blog
http://gictor.ir/fa/posts/etc/unlimited-google-drive/
![image](https://user-images.githubusercontent.com/34630603/73432273-a0f75180-4357-11ea-80c9-6d5ad09214dc.png)

**Comment by zzossig** [comment]
Bro~ thanks for finding bugs.
I fixed it.

**Comment by Gictorbit** [comment]
thank you for your pretty theme

**Comment by zzossig** [comment]
Feel free to open a new issue😋
I'm glad to fix bugs, improve UI

**Comment by Gictorbit** [comment]
the background of badge counter need to be fixed for `rtl` languages in tags, categories and series section 
![image](https://user-images.githubusercontent.com/34630603/73525017-90141200-4423-11ea-829f-e184351c003b.png)

**Comment by zzossig** [comment]
It is fine on my end.
![주석 2020-01-31 175650](https://user-images.githubusercontent.com/52706977/73525702-1267fa80-4453-11ea-97c5-f9f229cb59e9.png)

Can you give me the repo?

**Comment by Gictorbit** [comment]
ok this is my repo 
[https://github.com/Gictorbit/myblog](https://github.com/Gictorbit/myblog)
I checked that with `hugo server` in my localhost
the build of it is on [http://gictor.ir](http://gictor.ir)

**Comment by zzossig** [comment]
I did fix it.

**Comment by Gictorbit** [comment]
excellent thank you

**Comment by zzossig** [comment]
Make a **`new`** issue for further UI fixing.
It's totally fine to make a new issue. I don't mind.
I love to fix bugs, improve UI.
So feel free to open a `new` issue.
I just want to fix thing one at a time
