### ISSUE TITLE
Change avatar url in config

### ISSUE THREAD

**Issue by VictorZakharov** [zzossig/hugo-theme-zzo#116]
I disabled gravatar - then by trial and error (and looking at theme implementation), I figured that putting my avatar into static/images/whoami with the name avatar.png works (when not using gravatar). Is it possible via settings instead (params.toml)? I tried authorImage - didn't do anything, with/without "static". Then I don't need to change folder structure.

**Comment by zzossig** [comment]
Maybe we add new param something like `avatarLink`

**Comment by VictorZakharov** [comment]
I think it should match what's available as article front matter. From your docs:
```
---
title:
...
author: # author name
authorEmoji: 🤖 # emoji for subtitle, summary meta data
authorImage: "/images/whoami/avatar.jpg" # image path in the static folder
authorDesc: # author description
socialOptions: # override params.toml file socialOptions
  email: ""
  facebook: ""
  ...
---
```

**Comment by zzossig** [comment]
Ok, good suggestion.
But I want to divide the params one from `static` and the other is from `url`
So, Maybe `authorImageUrl` would be fine

**Comment by VictorZakharov** [comment]
authorImage or authorImageUrl  - either is fine with me.

**Comment by zzossig** [comment]
I added two parameters.
- `authorImageUrl`
- `bioImageUrl`

The `bioImageUrl` is used in the bio component. You can set this param at `params.toml` file.
The `authorImageUrl` is used in the whoami component. You can set this param at `params.toml` file or in a markdown file

**Comment by zzossig** [comment]
I think we can close this issue now.
Feel free to open a new issue👍

**Comment by VictorZakharov** [comment]
Yes, sorry - did not have time to test. Maybe today.
