### ISSUE TITLE
Exclude code blocks from summary / excerpt, stop extracting on excerpt

### ISSUE THREAD

**Issue by VictorZakharov** [zzossig/hugo-theme-zzo#117]
Currently code blocks are included if they fall within word count, and it looks pretty ugly:
![image](https://user-images.githubusercontent.com/8978766/73230113-1ee60d80-414a-11ea-809b-22ef4a7fd574.png)

The article starts like this:
![image](https://user-images.githubusercontent.com/8978766/73230121-286f7580-414a-11ea-9b63-24fe1cbd16b1.png)

Would it be possible to stop summary/excerpt block when code block starts? So in my case excerpt would be just this:
> Here is my pure CSS implementation of simple blockquote style, based on this article.
> I will explain every line of CSS being used as CSS comments - you will need most of them.

**Comment by zzossig** [comment]
I will try

**Comment by VictorZakharov** [comment]
Alternatively, if there is some sort of divider I can specify in markdown, that would be a good workaround.

**Comment by zzossig** [comment]
I found that Hugo provide us the way of doing it.
![more](https://user-images.githubusercontent.com/52706977/73245530-c8cba580-41ef-11ea-954b-89882fe37b5c.png)

You can get the summary text from the start to the `<!-- more -->`.

More read [https://discourse.gohugo.io/t/markdown-content-renders-as-regular-text-in-summary/1396](https://discourse.gohugo.io/t/markdown-content-renders-as-regular-text-in-summary/1396)

**Comment by VictorZakharov** [comment]
I just tried - it did not work. Nothing changed. Do I need some config ?

**Comment by zzossig** [comment]
You don't need any configurations.
Can you give me a repo that I can take a look at?

**Comment by VictorZakharov** [comment]
No I don't have your url changes yet.
I also tried to specify summary in front matter, but could not figure out the syntax
```
---
layout: post
title: Powershell - Get CPU Usage by Process (remote)
tags: [powershell]
date: 2017-04-19
summary = """
You would expect `Get-Process` to do the job, but it turns out that its CPU metric is not on a 0..100% scale. \

Here is a one-liner (find who's eating into your CPU - or that of a remote server):"""
---
```
My website is on a private repo. For zzo theme, I forked your repo to display build date/time in the footer (to remember when it was last deployed), but no other changes.

**Comment by VictorZakharov** [comment]
Here is my markdown for that article:

```md
---
layout: post
title: Powershell - Get CPU Usage by Process (remote)
tags: [powershell]
date: 2017-04-19
---

You would expect `Get-Process` to do the job, but it turns out that its CPU metric is not on a 0..100% scale.

Here is a one-liner (find who's eating into your CPU - or that of a remote server):

```powershell
gwmi Win32_PerfFormattedData_PerfProc_Process -filter "Name <> '_Total' and Name <> 'Idle'" -Computer $servername | where { $_.PercentProcessorTime -gt 0 } | select Name, PercentProcessorTime
```

For some reason, the total percentage of all selected processes can be greater than 100, I'm guessing there was a measurement lag. Don't forget to initialize `$servername` (or hard code it before executing).

Credit goes [here](http://stackoverflow.com/a/39251507/897326).
```

**Comment by zzossig** [comment]
There is no layout, summary front-matter in our theme.
You can reference the `exampleSite ` directory. https://github.com/zzossig/hugo-theme-zzo/tree/master/exampleSite/content/posts

The `summary` should be `desctipsion`

**Comment by VictorZakharov** [comment]
I gave up on multiline strings, and just removed all newlines manually. It works using description.
Thanks - I'm new to Hugo.
