### ISSUE TITLE
featured_image setting ignored for posts in the "classic" mode

### ISSUE THREAD

**Issue by thomas-maurice** [zzossig/hugo-theme-zzo#120]
Hello !

I seem to be hitting a bug with the latest revision, `ce9ec4e`, when I compile the website with the `classic` `summaryShape` I do not see any featured image on the homepage, even though they show up properly if I switch the summaryShape to `card`

cheers

**Comment by zzossig** [comment]
Hello!
I think ce9ec4e version is fine because I changed the author part and my blog also works well.

Can you show me how did you set the featured_image or repository link?

**Comment by zzossig** [comment]
Can you tell me what version of Hugo using

**Comment by zzossig** [comment]
I think you did something wrong.
