### ISSUE TITLE
Proper use of authorImageUrl and bioImageUrl

### ISSUE THREAD

**Issue by VictorZakharov** [zzossig/hugo-theme-zzo#121]
So I added this to my params.toml:
```
authorImageUrl = "/images/avatar.png"
bioImageUrl = "/images/avatar.png"
```
Side picture is loaded from the new path:
![image](https://user-images.githubusercontent.com/8978766/73503688-f6a11d80-439a-11ea-8159-2082a3725d7c.png)

But author image in the bottom of every article still points to `/whoami/` folder. What am I doing wrong?
![image](https://user-images.githubusercontent.com/8978766/73503722-07519380-439b-11ea-8449-60ab56cf45d3.png)

Also why do you need the complexity of 2 urls? Would you ever want a different image for your site vs under every article of yours? And it turns out they have a different non-obvious setup.

**Comment by zzossig** [comment]
The `authorImageURl` and `bioImageUrl` is for the URL outside of the project like `https://myimage.png`.
The `authorImage` is for the project relative path.
So, change the `authorImageUrl` to `authorImage` 

I made two separate params as I told you before. https://github.com/zzossig/hugo-theme-zzo/issues/116#issuecomment-579117026. The `authorImageUrl` is for the whoami element and the `authorImageUrl` is for the bio element.

**Comment by VictorZakharov** [comment]
Ok I changed to
```
authorImage = "/images/avatar.png"
bioImageUrl = "/images/avatar.png"
```
Nothing changed.

**Comment by VictorZakharov** [comment]
I mean bottom src still points to /whoami/ folder.

**Comment by zzossig** [comment]
Not in the params.toml file, 
use it in the markdown file
```yaml
---
title:
date:
description:
authorImage: "/image/avatar.png"
---
```

**Comment by VictorZakharov** [comment]
I don't want to set it in every markdown file. That was the whole point of having it in params.toml, set once and forget. Why would every article written by me have a different avatar every time?

**Comment by zzossig** [comment]
Ok, It was my mistake.
I have to change  some syntax

this 
```
.Site.Params.bioImageUrl
```

to this
```
$.Param "bioImageUrl"
```

Can you just try to specify it in the markdown file and works as expected?
I'll update it shortly

**Comment by VictorZakharov** [comment]
Yes it works, I changed one article now it has `/images/avatar.png` path, all the rest are pointing to `/whoami/` folder.

**Comment by zzossig** [comment]
Ok, thanks,
I made some changes.
After some test on my end, I'll upload it soon

**Comment by zzossig** [comment]
Bro, I got some misunderstood what you mean.
I made some changes.
This time, it should work.
Update the theme and check again

**Comment by VictorZakharov** [comment]
Deployed and working. Thanks.
