### ISSUE TITLE
Request: Add XMPP communication protocol icon (also matrix icon)

### ISSUE THREAD

**Issue by Ashpex** [zzossig/hugo-theme-zzo#123]
I know you can't keep adding icons whenever being requested but xmpp is not a chat application that's made by some random companies.

"XMPP is the open standard for messaging and presence.
XMPP powers emerging technologies like IoT, WebRTC, and social.
No one owns XMPP. It's free and open for everyone since 1999.
Millions use XMPP software daily to connect to people and services."

[Project's home page](https://xmpp.org/)

In short, it's an popular open source communication protocol. 

Matrix is also a similar thing: [matrix.org](https://matrix.org/) 
* XMPP logo:
![xmpp logo: ](https://user-images.githubusercontent.com/38400042/73514936-116ca400-4426-11ea-9ccb-1158b2e3fcfb.png)
* Matrix logo: 
![matrix logo: ](https://user-images.githubusercontent.com/38400042/73515128-c30bd500-4426-11ea-9f8d-54b00732691d.png)

Would be wonderful if you add both of them. Though if two icons are too much then please consider adding xmpp. Thank you.

**Comment by zzossig** [comment]
I think the XMPP logo should material style logo with no colors for compatibility with other icons.

**Comment by Ashpex** [comment]
> I think the XMPP logo should material style logo with no colors for compatibility with other icons.

Yes, absolutely. I can't find it anywhere though. I'll try to make it if possible.
For more information. The link for xmpp contact should be:
xmpp:(account addess)
* For example:
xmpp:name@example.domain
The browser will look up and open xmpp application or any applications support this link. Kind of like how mailto:name@example.com works.
As for matrix, things are different though. There is [matrix.to](https://matrix.to/) , but I guess you can just simply let user put their urls instead.

**Comment by Ashpex** [comment]
@zzossig 
Hi, I made this. Will this work?
* Logo with "xmpp"  (the logo is white + transparent background so you won't see anything at all, save and open it somewhere else)
![XMPP_logo](https://user-images.githubusercontent.com/38400042/73520278-d7a39980-4435-11ea-823c-8e209d7894f9.png)
* Without the "xmpp" under the logo
![XMPP_logo](https://user-images.githubusercontent.com/38400042/73520341-fdc93980-4435-11ea-9374-1484d687fcf5.jpg)
I have the svg file incase you need it.

**Comment by zzossig** [comment]
No, I'm using paid service for icons.
I requested the two icons.
They said that it will take a week to make it.

**Comment by Ashpex** [comment]
> No, I'm using paid service for icons.
> I requested the two icons.
> They said that it will take a week to make it.

Oh. That's so great. Thanks!

**Comment by zzossig** [comment]
The icons added.

`params.toml`
```
...
[socialOptions]
...
    matrix = ""
    xmpp = xmpp:name@example.domain
```

**Comment by Ashpex** [comment]
Awesome. Thank you very much!
