### ISSUE TITLE
Summary description is gone

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#126]
![Screenshot from 2020-01-31 20-32-59](https://user-images.githubusercontent.com/2096087/73568557-f5d6bd00-4468-11ea-9da6-7ac205180b5b.png)

I think this in your last commit broke it:
![Screenshot from 2020-01-31 20-33-08](https://user-images.githubusercontent.com/2096087/73568558-f5d6bd00-4468-11ea-9496-6ec4043ac117.png)

**Comment by zzossig** [comment]
Oops, I'll fix it

**Comment by zzossig** [comment]
Thanks for reporting this! It's fixed now

**Comment by nisrulz** [comment]
Thank you. Closing now.
