### ISSUE TITLE
[Feature Request] Personal website link in footer

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#127]
![Screenshot from 2020-01-31 20-50-26](https://user-images.githubusercontent.com/2096087/73569792-654dac00-446b-11ea-9079-9e4866f1c905.png)

I would like to add a link to my personal website in the footer, however it is not possible right now.

**Comment by zzossig** [comment]
Ok, I just quickly think about this. Maybe the syntax would look like this.

`config.toml`
```toml
copyright = {Nishant Srivastava:https://www.example.com} - c2015-2020, All content is licensed under CC BY-SA
```

**Comment by nisrulz** [comment]
`{Nishant Srivastava:https://www.example.com}`

Can I do this?

**Comment by xdot26** [comment]
you can try like this

> copyright = "<a target=\"_blank\" rel=\"external noopener license\" href=\"https://www.example.com\">Nishant Srivastava</a> - hosted in AWS. &copy;{year}, All Rights Reserved"

**Comment by zzossig** [comment]
I just made the footer text markdonwify.
So, you can do this

```toml
...
copyright = "[Nishant Srivastava](https://www.example.com) - c2015~"
```

**Comment by zzossig** [comment]
I think we can close this issue.
Feel free to reopen if something wrong.

**Comment by nisrulz** [comment]
This works, thanks for this!

Just a small thing though, the link opens in the same page instead of opening a new page. Can this be done?

**Comment by zzossig** [comment]
I can't control the markdown syntax link right now.
It could be possible using rendering hooks.
But it will make the whole link to open external.
Hugo doc says

> currently only possible to have one set of render hook templates, e.g. not per Type or Section. We may consider that in a future version. ↩︎

If it's ok in your case(by default open links external) you can make a hook.
I just copy-pasted the official Hugo site document

`layouts/_default/_markup/render-link.html`
```
<a href="{{ .Destination | safeURL }}"{{ with .Title}} title="{{ . }}"{{ end }}{{ if strings.HasPrefix .Destination "http" }} target="_blank"{{ end }}>{{ .Text }}</a>
```

**Comment by nisrulz** [comment]
I tried what @talz26 suggested and that worked too :thinking: 

```
copyright = "<a target='_blank' rel='external noopener' href='https://nisrulz.com'>Nishant Srivastava</a> - ©2015 - {year}, All content is licensed under "
```

**Comment by zzossig** [comment]
Oh, it also good
I didn't notice it.
Markdown makes `a` tag anyway.
That is the easest solution
