### ISSUE TITLE
Add support twitter preview link

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#129]
`meta_image` is a good option for link preview, it could be better if preview link support twitter
twitter has particular meta tags for it
I think [socialsharepreview](https://socialsharepreview.com/) could be helpful
thanks :+1:

**Comment by zzossig** [comment]
Ok, I'll check about it👍

**Comment by zzossig** [comment]
Wow, the `social share preview` is a good tool to test with.
I added some twitter meta tags. Check if it is what you expected

**Comment by Gictorbit** [comment]
nice, preview ink improved.:1st_place_medal: 
thank you so much
