### ISSUE TITLE
how can I add an image in my post?

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#130]
I tried image markdown syntax to add an image in my blog post
`![header image](/static/images/post-image/2020/image.jpg)`
but it couldn't load the image
how could I put an image in my posts?

**Comment by zzossig** [comment]
Refer this link
https://zzodocs.netlify.com/docs/shortcodes/img/

**Comment by Gictorbit** [comment]
problem solved thanks
