### ISSUE TITLE
add button shortcode feature

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#132]
the theme could be better if it has a button shortcode feature, something like this:
[https://learn.netlify.com/en/shortcodes/button/](https://learn.netlify.com/en/shortcodes/button/)

**Comment by zzossig** [comment]
What would you do with the buttons?
Do you want to use it to the external link?

**Comment by Gictorbit** [comment]
yes

**Comment by zzossig** [comment]
I added the button shortcode
https://zzodocs.netlify.com/docs/shortcodes/button/

**Comment by Gictorbit** [comment]
ok great I tested this feature it and added this shortcode to my post
`{{< button href="https://google.com"  >}}download{{< /button >}}`
but doesn't appear any button
![image](https://user-images.githubusercontent.com/34630603/73597186-a5ca2a00-453e-11ea-841a-0cfaa5a2dc8c.png)

**Comment by zzossig** [comment]
Can you try this?
`{{< button href="https://google.com" color="primary">}}download{{< /button >}}`

**Comment by Gictorbit** [comment]
> Can you try this?

yes I tried and it works great thanks :1st_place_medal: 


> Did you update the theme?

yes I updated

> Try force refresh the browser

also, I tried this trick and it works too :+1: 
it was my mistake sorry

**Comment by zzossig** [comment]
great!
So, the button is as you expected one?
Can we close this issue now?

**Comment by Gictorbit** [comment]
yes it's great thanks
