### ISSUE TITLE
add link preview for website url 

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#134]
it could be better if the latest link preview feature (twitter and telegram ) added to site url
I think the home page hasn't meta tag?

**Comment by zzossig** [comment]
I don’t understand what you mean.
What did you tried?

**Comment by Gictorbit** [comment]
> Did you mean the posting page has a good preview link but not the case on the home page(root url)?

yes I added `meta_image` to my posts and they have great preview link now but if I send my blog url to someone there is no any preview link even a description
![image](https://user-images.githubusercontent.com/34630603/73605162-080f4300-45b0-11ea-89cb-12e3b47304a7.png)



> I think the `meta_image` param not set in the `params.toml` file. So try this

I did it but doesn't work

**Comment by zzossig** [comment]
Oh ok, I did a quick search and found this https://stackoverflow.com/a/35793374/11747951
I just added the code `<html prefix="og: http://ogp.me/ns#">`.

So, update the theme, and send a text message to @webpagebot then it should work.

**Comment by Gictorbit** [comment]
I updated the theme but seems something went wrong 
I checked my website url in telegram (using `@WebpageBot` also ) and [socialsharepreview](https://socialsharepreview.com/) but preview link doesn't work yet

**Comment by zzossig** [comment]
When I check your blog, it works well
![주석 2020-02-02 185705](https://user-images.githubusercontent.com/52706977/73606461-d7e69500-45ed-11ea-9964-2c55029385dd.png)

**Comment by zzossig** [comment]
How about set the `defaultContentLanguageInSubdir` param to `false` in the file at `root/config/_default/params.toml`

**Comment by zzossig** [comment]
Anyway, I fixed the post title link wrong positioning
![주석 2020-02-02 191844](https://user-images.githubusercontent.com/52706977/73606779-221d4580-45f1-11ea-8f11-fe197d3fb3b9.png)

**Comment by Gictorbit** [comment]
I think the extension isn't accurate I recommend check online with web edition of it
anyway this is the link preview in telegram and twitter
in telegram: 
![image](https://user-images.githubusercontent.com/34630603/73606967-6a267300-45c5-11ea-991f-bba2a24640c5.png)
in twitter with [twitter card validator](https://cards-dev.twitter.com/validator)
![image](https://user-images.githubusercontent.com/34630603/73606986-b671b300-45c5-11ea-9a87-d0741c8924d3.png)
 but for Facebook I checked with [facebook developer tools](https://developers.facebook.com/tools/debug/sharing/) and was good

**Comment by zzossig** [comment]
Did you tried `http://gictor.ir/fa`?

**Comment by zzossig** [comment]
Did you send the text message to the webpagebot?
![주석 2020-02-02 195403](https://user-images.githubusercontent.com/52706977/73607139-cf925800-45f5-11ea-88ee-3917ee1dc47c.png)

**Comment by Gictorbit** [comment]
oh I didn't notice to `/fa` with this path works well thanks
also, I didn't know about `defaultContentLanguageInSubdir` problem solved thanks

**Comment by zzossig** [comment]
Great,
If the link preview still not working, or have a question, we can chat more about it here
