### ISSUE TITLE
avatar image + theme changer are not working for me

### ISSUE THREAD

**Issue by brimwats** [zzossig/hugo-theme-zzo#137]
Here's the relavant part of my params.toml

```
logo = true
description = "Brian M. Watson's Blog"
custom_css = []
custom_js = []
themeOptions = ["dark", "light", "hacker", "solarized", "kimbie"]

notAllowedTypesInHome = ["contact", "talks", "about", "posts", "events", "pt", "contact"] # not allowed page types in home page. type can be set in front matter or default to folder name.
notAllowedTypesInHomeSidebar = ["contact", "talks", "about", "posts", "events", "pt", "contact"] # not allowed page types in home page sidebar(recent post titles).
notAllowedTypesInArchive = ["contact", "talks", "about", "posts", "events", "pt", "contact"] # not allowed page types in archive page

# header
homeHeaderType = "text" # text, img, slide

# navbar
enableThemeChange = true # site color theme

# body
enableBreadcrumb = true
enablePhotoSwipe = true
enableSearch = true
enableSearchHighlight = true
enableGoToTop = true
enableWhoami = true
summaryShape = "classic" # card, classic, compact
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"

# whoami
myname = "Brian M. Watson"
# email = "EMAIL"
whoami = "Archivist, Historian, Digital Humanist"
useGravatar = false
bioImageUrl = "" # image url like http//... If not set, we find a avatar image in root/static/images/whoami/avatar.(png|jpg|svg)
location = "Bloomington, Indiana"
organization = "Kinsey Institute Library; Indiana University Bloomington"
link = "https://brimwats.com"

# sidebar
enableBio = true
enableSidebar = true
enableSidebarTags = false
enableSidebarSeries = false
enableSidebarCategories = false
enableToc = false
hideToc = true
enableTocSwitch = false
itemsPerCategory = 0
sidebarPosition = "right" # bio, profile component layout position

# footer
showPoweredBy = true # show footer text: Powered by Hugo and Zzo theme
showFeedLinks = true # RSS Feed 
showSocialLinks = true # email, facebook, twitter ...
enableLangChange = true # show button at bottom left of footer.
```

but when I hugo serve or when I push to github pages (site is deployed into the docs folder) i get a blank image. the URL of that image is 

> data:image/svg+xml,%0A%3Csvg xmlns='http://www.w3.org/2000/svg' width='24' height='24' viewBox='0 0 24 24'%3E%3Cpath fill='none' d='M0 0h24v24H0V0z'/%3E%3Cpath fill='%23aaa' d='M19 3H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-1 16H6c-.55 0-1-.45-1-1V6c0-.55.45-1 1-1h12c.55 0 1 .45 1 1v12c0 .55-.45 1-1 1zm-4.44-6.19l-2.35 3.02-1.56-1.88c-.2-.25-.58-.24-.78.01l-1.74 2.23c-.26.33-.02.81.39.81h8.98c.41 0 .65-.47.4-.8l-2.55-3.39c-.19-.26-.59-.26-.79 0z'/%3E%3C/svg%3E

I've tried changing

>bioImageUrl = "" # image url like http//... If not set, we find a avatar image in root/static/images/whoami/avatar.(png|jpg|svg)

**to a different URL**, no luck
 **to the actual file path**:  (because there is an image in /ststic/images/whoami/ and it is named avatar.jpg, no luck

For the theme: changing the 

> themeOptions = ["dark", "light", "hacker", "solarized", "kimbie"]

changes the theme, and

># navbar
>enableThemeChange = true # site color theme

is enabled but doesn't do anything in hugo serve or on the live page.

**Comment by zzossig** [comment]
Can you provide me the repository?
It's impossible just looking at the config params and diagnose what's wrong.

What Hugo version are you using? What OS?
Can you try this guide? https://zzodocs.netlify.com/docs/gettingstarted/quickstart/

**Comment by brimwats** [comment]
I can un-private the repository for awhile so you can take a look. Please be aware that there are articles about the history of sexuality that also have pictures about (no porn)

https://github.com/brimwats/musings

I got this URL after some research idk if relavant: https://css-tricks.com/probably-dont-base64-svg/

**Comment by brimwats** [comment]
I am using the most recent version of hugo. 63.2

I have used chrome, firefox, brave browser on windows 10, ubuntu 18, and android phone (all three browsers on all three platforms)

**Comment by zzossig** [comment]
I have a question.
Why did you override the theme's script?
You have a file at `root/layouts/partials/head/scripts.html` and this file prevent you from using theme's script file(root/themes/zzo/layouts/partials/head/scripts.html)

And the front matter you are using in the post markdown file is not applicable in the zzo theme.
![주석 2020-02-02 160507](https://user-images.githubusercontent.com/52706977/73604552-e7f27a80-45d5-11ea-9298-aa3c9b0c02ed.png)

Check the front matter in the file at `root/themes/zzo/archetypes`

**Comment by brimwats** [comment]
that might be it!

I didn't *intend* to overwrite the theme's script, I moved the files more or less intact from a different hugo theme because it was a *lot* to edit all the frontmatters. Let me go do some deleting and see if that helps!!

**Comment by brimwats** [comment]
It works!!! thank you so so much for catching that! I'd been going insane trying to figure it out :)

**Comment by zzossig** [comment]
It could be a time-consuming job to change all the post front matter. 
If you have any trouble to change the front-matter, we can chat more about it here

**Comment by brimwats** [comment]
agreed--the variety and mixture of front matter and issues with it when jumping from theme to theme is my only complaint about hugo! thank you again!!
