### ISSUE TITLE
404 not found page

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#139]
I saw that your theme does not have `404 not found` page
so I think it could be better if you add this page

**Comment by zzossig** [comment]
What Hugo version are you using?

**Comment by Gictorbit** [comment]
v0.63.0

**Comment by zzossig** [comment]
We already have it https://github.com/zzossig/hugo-theme-zzo/blob/master/layouts/404.html
But the recent Hugo version fixed something related 404 template. https://gohugo.io/news/0.63.2-relnotes/

So, update the Hugo version to 0.63.2.
Make sure that the 404 page not showing in the localhost. It only appears when you deploy the site

**Comment by Gictorbit** [comment]
Hmm ok
got it thanks

**Comment by zzossig** [comment]
Also, refer to this page https://gohugo.io/templates/404/#automatic-loading.
I see that only GitHub Pages automatically load the 404 page

**Comment by zzossig** [comment]
We can talk more about it here. I'm closing this issue now.
If you want to see what 404 page look like, just check this url http://gictor.ir/404.html

And I saw that you used 4 levels deep post title.
You are using `#### My title` something like this right?

Then you should edit the tableOfContent configuration

config.toml
```toml
  [markup.tableOfContents]
    endLevel = 4 # instead of 3
    ordered = false
    startLevel = 2
```
