### ISSUE TITLE
Styles show up after page loads

### ISSUE THREAD

**Issue by shihaamabr** [zzossig/hugo-theme-zzo#14]
Styles show up a fraction of second later on demo site

**Comment by zzossig** [comment]
I already fixed it. It will take 2days to update theme website. The theme site updated automatically not manually so we have to wait 😭

**Comment by shihaamabr** [comment]
Ahh, I see
So if I tried out it will be fine?

**Comment by zzossig** [comment]
Yes I think so

**Comment by zzossig** [comment]
It's fixed now. I'm gonna close this issue.
