### ISSUE TITLE
Pseudo-static

### ISSUE THREAD

**Issue by Jason-cqtan** [zzossig/hugo-theme-zzo#141]
want to customize the suffix on the URL when I visit the article, such as .html, .php, etc.

**Comment by zzossig** [comment]
What do you mean?
Do you have PHP files on your blog?

**Comment by zzossig** [comment]
You can not use PHP file in Hugo
https://discourse.gohugo.io/t/can-i-use-dynamic-php-in-hugo-site-layout/1507

I think the feature is more related to the Hugo.
I can't manage the file extension.

**Comment by Jason-cqtan** [comment]
Not accessing dynamic files, but disguised as a suffix when accessed, it looks like it is not

**Comment by Jason-cqtan** [comment]
you know,url rewrite

**Comment by zzossig** [comment]
try this

```yaml
title:
date:
...
url: yourcustomurl.php
```

**Comment by zzossig** [comment]
We can keep talking here if you have more questions
