### ISSUE TITLE
share block says "post" on the talk page

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#142]
![Screenshot from 2020-02-04 01-21-07](https://user-images.githubusercontent.com/2096087/73702330-bf10d900-46ec-11ea-825a-94c63ed8c394.png)

You can check live version [here](https://crushingcode.nisrulz.com/talks/fosdem_2020/)

**Comment by zzossig** [comment]
I didn't think it can be used somewhere other than post page.
How about just set it `Share this`?
Or we can make another i18n param

**Comment by zzossig** [comment]
I have searched for what is the appropriate word for it.
I think `Share on` seems to be the best.
Anyway, Thanks for the issue😋

**Comment by nisrulz** [comment]
That sounds right actually. Thanks 🎉
