### ISSUE TITLE
Navigation doesn't respect boundaries

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#144]
![Screenshot from 2020-02-04 20-57-02](https://user-images.githubusercontent.com/2096087/73781677-fd5fd400-4790-11ea-8ae6-1ec88e87cc51.png)

Notice while being in the talk page, it is giving the next page to be the one from SHOWCASE page i.e RecyclerViewHelper.

Also on showcase page, "RecyclerViewHelper" is treated as a clickable link, so when I click on this link here in navigation page..it takes me to the page itself which obviously doesn't have anything in there.

![Screenshot from 2020-02-04 20-59-27](https://user-images.githubusercontent.com/2096087/73781830-3ef07f00-4791-11ea-9f37-86d3122e04ce.png)

The solution should be that the navigation should only cycle through a certain type i.e only talks or only posts or only showcases and not jump between the types.

**Comment by zzossig** [comment]
You are right.
Should be fixed.
Thanks for the good issue 👍

**Comment by zzossig** [comment]
It's fixed now.
Pagination not jumping types, sections anymore

**Comment by nisrulz** [comment]
Closing as this is fixed.

Thank you :tada:
