### ISSUE TITLE
Publication overview page UI redesign

### ISSUE THREAD

**Issue by zzossig** [zzossig/hugo-theme-zzo#146]
https://github.com/zzossig/hugo-theme-zzo/issues/138#issuecomment-582944666

**Comment by zzossig** [comment]
@brimwats
You want `tags` on the publications page because you want to filter inside the sections.
We already make sections categorize your `.bib` file, but you want to filter the section also.
is that right?

**Comment by brimwats** [comment]
I think so... I might be using the wrong word

Take a look here:

https://themes.gohugo.io//theme/academic/publication/ is generally what I'm aiming for :) I've played around with some ideas and tagging about how to represent it best on the front page

**Comment by zzossig** [comment]
Ok,
I think we already have almost all the same features.
I'll make the page in my own style.

**Comment by zzossig** [comment]
@brimwats hi,
I made some changed. I'm not in a hurry so, try this when you have a time

1. update the `zzo-bibtex-parser` to 1.0.8. The `1.0.8` version supports the non-curly braces month parameter.
2. the `1.0.8` version also makes `links` parameter. I think this is what you are looking for `the tags`
3. To update the `zzo-bibtex-parser` to `1.0.8` type this in your terminal.
    ```
    pip install zzo-bibtex-parser==1.0.8
    ```
4. Assuming that you have a `bibtex.bib` file at the root folder, type this
    ```
    zzo --path bibtex.bib
    ```
5. Now, you can see the publication folder. When you check the `md` file, you can see the `links` front matter. You can make as many links as you want.

    ```
    ...
    links:
    - name: mylink
       link: https://exampleSite.com
    - name: anotherLink
       link: https://mysite.com
    ```
6. I redesigned the overview page too. You can set `pinned` param to `true` when you want to expose your article to the overview page. By default, I set `pinned` to true for the current year article.

**Comment by brimwats** [comment]
I think it might be a bit backwards--but it does look so much nicer!

Let me try to explain, from my site's POV:

1) landing page
![image](https://user-images.githubusercontent.com/49103046/74087618-151ead00-4a5c-11ea-9755-1ab129d72035.png)

2) click publication
![image](https://user-images.githubusercontent.com/49103046/74087619-2071d880-4a5c-11ea-854d-8fa92ad05563.png)

Essentially it would be a matter of sorting by *type* of publication, and then by *topic* of publication:

so here's a (rough) mockup, and not a demand--feel free to stylize it however you want!

3) 

![image](https://user-images.githubusercontent.com/49103046/74087903-734c8f80-4a5e-11ea-8bc3-e524381e9ed2.png)


4) after a person has picked a "topic" tag, in this case history, it would show them articles about that

![Image](https://user-images.githubusercontent.com/49103046/74087922-a000a700-4a5e-11ea-8a84-0e3cd3a2a83b.png)

**Comment by zzossig** [comment]
You didn't update the theme.
It's not updated version

**Comment by brimwats** [comment]
omg, that's embarrassing, sorry about that!! 🤦‍♂ 🤦‍♀ 

Yes, I see it now! It looks very nice :) 
![image](https://user-images.githubusercontent.com/49103046/74088249-06d38f80-4a62-11ea-9c12-73b4d67a32ea.png)

So perhaps like this?

![image](https://user-images.githubusercontent.com/49103046/74088270-692c9000-4a62-11ea-82d0-ca3fb562e129.png)

(the boxes are supposed to read[intellectual freedom], [libraries] to match the  VSCode


If you'd like an explanation: often people who visit academic types come from one specific discipline--but I write about sexuality, libraries, history, and so on, so it helps to have the ability to sort through by topic.

**Comment by brimwats** [comment]
Ah! like on the talks page:

![image](https://user-images.githubusercontent.com/49103046/74088293-bad51a80-4a62-11ea-9788-7c5eff677acc.png)


clicking "history of sexuality" goes here:

![image](https://user-images.githubusercontent.com/49103046/74088294-c0cafb80-4a62-11ea-9242-4a35247423cd.png)


To have it as a clickable thing before, perhaps? I apologize if I'm asking for too much!

**Comment by zzossig** [comment]
No, please do give me more homework.
It's totally fine.
Ok, you just need the tags, anything else?

**Comment by brimwats** [comment]
The URLS work so flawlessly! I am so impressed! You are very good at this!

> Ok, you just need the tags, anything else?

If you're letting me make wild requests. These are both pretty involved so don't overdo yourself--and it might not even be the way you want to go! 

1) more customization on the 'about' page, or a section that allows for the creation of a resume. Basically the ability to add static sections or fill out a param and have it be generated. Some themes that do this:

https://hugothemesfree.com/my-cv-resume-using-a-free-hugo-theme/
https://github.com/themefisher/Academia-hugo
https://jamstackthemes.dev/theme/hugo-academic/
https://jamstackthemes.dev/theme/hugo-resume-theme/
https://github.com/darshanbaral/sada
https://github.com/hadisinaee/avicenna


2) a feature that I think would be killer is the ability to generate a PDF from a CV. (so Markdown -> hugo (makes HTML) -> wkhtmltopdf -> PDF generated in /static/files for download

(relevant links: [one](https://github.com/patrick-othmer/cv), [two](https://wkhtmltopdf.org/), [three](https://discourse.gohugo.io/t/generate-hugo-website-as-a-pdf/22855), [four](https://github.com/gohugoio/hugo/issues/6332), [five](https://weasyprint.org/start/)). But I know that might be a dream!

**Comment by zzossig** [comment]
Dreams come true

>more customization on the 'about' page

Do you have any idea regarding a UI, design?

> PDF generated in /static/files

Why it should generate files in the static folder. I think just download the pdf file is enough?

> wkhtmltopdf 

what is this word?

> generate a PDF from a CV

what is the CV?

**Comment by brimwats** [comment]
> Dreams come true

😁 ✨ 

> Do you have any idea regarding a UI, design?

I have my personal preference--which is something similar to the academic theme (https://academic-demo.netlify.com/ harder) or the CV theme (https://themes.gohugo.io/theme/hugo-orbit-theme/ easier)

> Why it should generate files in the static folder. I think just download the pdf file is enough? 

That is fine--but yes, to generate it from the site

> Or you mean, generate PDF files when building the site
>wkHTMLtoPDF 

is the library that does this. here's the documentation & an example of a hugo theme that does use it

https://wkhtmltopdf.org/
https://github.com/patrick-othmer/cv

**Comment by brimwats** [comment]
Other relavant sites that I originally linked:
https://weasyprint.org/start/
https://discourse.gohugo.io/t/generate-hugo-website-as-a-pdf/22855

**Comment by zzossig** [comment]
Ok, thanks for all the information.
I don't like the academic theme. So, `hugo-orbit-theme` is a good design for the about page?
You are going to use the about page for the resume right? The `hugo-orbit-theme` is a good design for a resume?

I'll search more about the resume page. Since I don't have an idea what contents should include in the resume page. e.g:EDUCATION, LANGUAGES, INTERESTS, PROJECTS, SKILLS & PROFICIENCY

**Comment by brimwats** [comment]
The Orbit Theme is good as well! I do like how some Jekyll resume themes use a circle or indicate how much experience someone has in something like these:

https://blackcurrant.jekyll-themes.com/
https://hydejack.com/

Along with those categories WORK EXPERIENCE and CLASSES TAUGHT maybe? A portfolio might be nice too but I think you already have that with the Showcase tab!

B

On Feb 8, 2020 12:34 PM, zzossig <notifications@github.com> wrote:

Ok, thanks for all the information.
I don't like the academic theme. So, hugo-orbit-theme is a good design for the about page?
You are going to use the about page for the resume right? The hugo-orbit-theme is a good design for a resume?

I'll search more about the resume page. Since I don't have an idea what contents should include in the resume page. e.g:EDUCATION, LANGUAGES, INTERESTS, PROJECTS, SKILLS & PROFICIENCY

**Comment by zzossig** [comment]
The publication page now supports tags.
If it's not what you have expected, open a new issue.
