### ISSUE TITLE
Is it possible to widen the page layout ?

### ISSUE THREAD

**Issue by benzwt** [zzossig/hugo-theme-zzo#147]
Is it possible to widen the page layout, such that the page can make use all the space of the screen ? 
It will be good for reading the post for wide screen.

**Comment by zzossig** [comment]
You can override theme's default `grid.toml` file to yours by making file at `root/data/grid.toml`

I didn't test the widen layout much. And the feature is an old legacy. So It might not work well.
Just test the layout and tell me what should I have to fix.

Key in mind that after you change the `grid.toml` file parameters, you should restart Hugo.

**Comment by zzossig** [comment]
As far as I know, we already have the feature.
If you found some bugs, open a new issue.
