### ISSUE TITLE
Support code block with title

### ISSUE THREAD

**Issue by LGTMXD** [zzossig/hugo-theme-zzo#149]
![47058C60-9F00-4C47-837A-39396C185E2A](https://user-images.githubusercontent.com/30213081/74085334-0ca59100-4ab3-11ea-8793-6d6349b18447.jpeg)

https://linuxize.com/post/how-to-install-apache-maven-on-debian-10/

**Comment by zzossig** [comment]
This is not relevant to this project.
Your screenshot is not using zzo theme

**Comment by LGTMXD** [comment]
> This is not relevant to this project.
> Your screenshot is not using zzo theme

I know，i wanna zzo theme also can have this effect when inserting code blocks

**Comment by zzossig** [comment]
Ok, this is a feature request.
I understand `how to show this` part.
But what is the `can't be copied` means?

**Comment by LGTMXD** [comment]
> Ok, this is a feature request.
> I understand `how to show this` part.
> But what is the `can't be copied` means?

u can click the link blow picture，“$”  this character cant be selected and also cant be copied.

**Comment by zzossig** [comment]
I know. `$` character cant' be selected. And that is the expected behavior.
What do you want to do in the zzo theme?

**Comment by LGTMXD** [comment]
> expected behavior

same effect in that picture

**Comment by zzossig** [comment]
Which part? the zzo theme has the same effect.
Can you show me a screenshot?

**Comment by LGTMXD** [comment]
> Which part? the zzo theme has the same effect.
> Can you show me a screenshot?

Feature request：set some special characters can be shown but cant be copied

**Comment by zzossig** [comment]
You just type the Chinese and I will use google translate.
I can't understand what you mean

**Comment by LGTMXD** [comment]
> You just type the Chinese and I will use google translate.
> I can't understand what you mean

![19FF9956-0103-4590-853F-DDADA29C73D9](https://user-images.githubusercontent.com/30213081/74085930-2d70e500-4ab9-11ea-8693-4e02e6201a70.GIF)

复制代码的时候让$不要被复制

Don't copy $ when copying code

**Comment by zzossig** [comment]
Ok, thanks for the gif.
I understand now.
I think it's a good feature for other people too.
I'll do some work tomorrow.

**Comment by zzossig** [comment]
Now, we can use `$`, `>` symbol for the line number, and set the code block title.
Update the zzo theme first and then follow the documentation
https://zzodocs.netlify.com/docs/configuration/codeblock/

**Comment by LGTMXD** [comment]
> Just keep in mind that the code block title should end with extensions. (e.g: .js, .c, .python) otherwise, the code-block would not render properly

**Comment by zzossig** [comment]
You might be saying that you don't want to keep the extensions.
I have tried to do that.
But since we are depending on some library - chroma(Hugo use this library for syntax highlight), I can't fully control over the behavior.

The pseudo-element(:: before) is not working. It's automatically deleted for some reason. I think chroma force detete the pseudo-element.

I hope you understand.
