### ISSUE TITLE
Remove the dependency on prism.js and use Hugo's built in syntax highlighing.

### ISSUE THREAD

**Issue by zzossig** [zzossig/hugo-theme-zzo#15]
I found that Hugo's build in syntax highlighing is so much faster than prism.js. So, I decided to use it instead using prism.js.

**Comment by fandean** [comment]
I support you.

**Comment by NickLarsenNZ** [comment]
How can I enable Prism? The default Hugo highlighter doesn't work properly for ANTLR. I get lots of valid symbols appearing with an `err` class, but it renders perfectly in prism.
