### ISSUE TITLE
Add Support HTML -> PDF

### ISSUE THREAD

**Issue by zzossig** [zzossig/hugo-theme-zzo#151]
https://github.com/zzossig/hugo-theme-zzo/issues/146#issuecomment-583754803

**Comment by zzossig** [comment]
@brimwats
I'll move this issue to the `zzo-bibtex-parser` project.
I can't include the heavy library for this theme.
So, we can make the pdf file in python, not in the browser.

**Comment by brimwats** [comment]
?That's a great idea and point!!

**Comment by julientaq** [comment]
WAIT!
we have an option for that :)

check the website i made using Hugo (for paged.js, the lib that let you print and make PDF from HTML : https://www.pagedjs.org

you got a button top right on this page to set up the preview. Once it’s done, you only need to print from the browser, and you’re all set. Browser side printin as it should be :)

http://localhost:1313/posts/2020-02-18-return-from-prague-the-future-of-web-to-print/

Tell me if you think that would help you as i try to make it reusable inside hugo.

**Comment by brimwats** [comment]
This looks very nice! It would be great if there was a button for pint (done) and a button to automatically get a pdf. But it works exactly like I'd imagine, and looks very nice. How hard is it go add to a theme in hugo?



________________________________

**Comment by julientaq** [comment]
Not that much hard. But the goal would be that you add a git submodule, a couple of info in the config and add the button in the template you’d like.

i’ll be workin on it asap.

**Comment by julientaq** [comment]
Hey folks, wanna try it out for me?
Still pretty experimental, but i’d love to have your thoughts.

https://gitlab.pagedmedia.org/julientaq/pagedjs-hugo

If you follow the readme, you’ll get a print button that you can add to any page as part of the template. next step is to add a configurable option in the front matter to show it or not :)
