### ISSUE TITLE
Global author variables

### ISSUE THREAD

**Issue by RheingoldRiver** [zzossig/hugo-theme-zzo#153]
Hi, do you support defining all author parameters in a single file and then calling them by their key in individual blog posts? e.g. if I want to change my authorDesc in a year, can I change that in just one place or does it have to be hard-coded into every blog post individually? thanks!

**Comment by zzossig** [comment]
If you want to set the author globally, set it in the params.toml file. All params in the params.toml file can set in the single md file as a front matter and all the front matter can be set in the    Params.toml file.

**Comment by RheingoldRiver** [comment]
Oh nice, thanks for the response!
