### ISSUE TITLE
Contact page getform

### ISSUE THREAD

**Issue by knightdave** [zzossig/hugo-theme-zzo#155]
Hi! Could you please add  https://getform.io/ service to contact page?

Form looks like that

```html
<form action="getform.io/f/1234" method="POST">
    <input type="text" name="name">
    <input type="email" name="email">
    <input type="text" name="tel">
    <input type="file" name="file">
    <button type="submit">Send</button>
</form>
```

Where `1234` is token that is unique for account.

Link to documentation: https://getform.io/docs

Thanks!

**Comment by zzossig** [comment]
Ok, I will

**Comment by zzossig** [comment]
I added the `getform`.
I've not tested it since I have no `getform` account😭

**Comment by knightdave** [comment]
Working! Thank you

![image](https://user-images.githubusercontent.com/13086223/74136992-572c2800-4bef-11ea-9363-15d0f5df966b.png)
---
![image](https://user-images.githubusercontent.com/13086223/74137035-6b702500-4bef-11ea-99e0-65a76c24f8d4.png)

**Comment by sysadmin-info** [comment]
I have set up an account at https://getform.io

I followed the tutorial from this website for getform

https://zzo-docs.vercel.app/zzo/pages/contact/

as a token you have to use the token generated by the basic section in form endpoint settings

so copy the some random string generated by the getform.io app and put it into the index.md file located in the contact directory according to the tutorial.

`<form action="https://getform.io/f/some-random-string" method="POST">`

Content of the index.md file should look like this one:

```
---
title: "Contact"
description: Contact page
type: contact
service: getform
getformToken: "some-random-string"
---

This is contact page.
```




I made a copy of the file from zzo theme and put it as below (see tree)
root directory for hugo website/layouts/partials/contact/getform.html

Then I replaced this code:

  `<div class="contact__input--container">`
   ` <div class="contact__input--wrapper">`
    `  <label class="contact__label">`
     `   {{ i18n "contact-tel" }}`
     ` </label>`
     ` <input type="text" name="tel" class="contact__input" aria-label="{{ i18n "contact-tel" }}">`
    `</div>`
    `<div class="contact__input--wrapper">`
    `  <label class="contact__label">`
    `    {{ i18n "contact-file" }}`
    `  </label>`
    `  <input type="file" id="upload" name="file" style="display: none;">`
    `  <input type="button" id="uploadBtn" value="{{ i18n "contact-browse" | default "Browse..." }}" class="contact__input" aria-label="{{ i18n "contact-file" }}"/>`
    `</div>`
  `</div>`

to this code:

`<div class="contact__message--wrapper">`
`    <label class="contact__label">`
`      {{ i18n "contact-message" }}`
`    </label>`
`    <textarea name="message" class="contact__message" aria-label="{{ i18n "contact-message" }}"></textarea>`
`</div>`

Goal achieved.

The result you can see here: https://sysadmin-info.netlify.app/en/contact/
