### ISSUE TITLE
search results appear twice

### ISSUE THREAD

**Issue by nocquidant** [zzossig/hugo-theme-zzo#156]
Search results appear twice since last modifications.

![image](https://user-images.githubusercontent.com/217054/74132725-68713680-4be7-11ea-93b3-41380e07167c.png)

Thanks
--nick

**Comment by zzossig** [comment]
Can you point me out what version are you using? e.g: e9ceb32
It has occurred to me also, but I thought I had fixed it.

**Comment by nocquidant** [comment]
Just updated to the last one: cd89d9fe

**Comment by zzossig** [comment]
Ok I'll look into it

**Comment by zzossig** [comment]
The problem was I made a double search index for the search.
I think it has been fixed now.

**Comment by nocquidant** [comment]
Right, it looks fine now, thanks!
