### ISSUE TITLE
Feat Request: Markup for Phone Numbers

### ISSUE THREAD

**Issue by Asjas** [zzossig/hugo-theme-zzo#157]
Hi @zzossig , 

Thanks for the awesome theme 😃. It definitely makes the move to Hugo much easier and it is really fast.

I was wondering if it would be possible for you to adjust the markup generated for the telephone number to include a `tel:` in the href attribute. That way if someone clicks on the phone number it would open the number in their phone automatically. 

```
<a href="tel:+123456789">123456789</a>
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#href

At the moment it seems that it is adding the website URL before the phone number and when you click on the number it is trying to take you to a page (which won't exist since it is a telephone number). You can test it on the website I deployed here https://asjas.xyz/.

**Comment by zzossig** [comment]
Hi @Asjas
Thanks for using the zzo theme.

Did you set the `phone` param in the `params.toml` file?
Can you show me how you set the `phone` param?

When I tested it on my end, it works well.
```toml
[socialOptions]
  ...
  phone = "tel:821011111111"
```

**Comment by Asjas** [comment]
Hi @zzossig.

That works 😆. I didn't realize I should be setting `tel:` with the number. Thanks for the message - it works now.
