### ISSUE TITLE
Bug - Whoami Description Alignment

### ISSUE THREAD

**Issue by Asjas** [zzossig/hugo-theme-zzo#158]
Hi @zzossig 👋 

I picked up an alignment issue in the `whoami` section at the bottom of the post pages. The `whoami__desc` div isn't center aligned on mobile devices.

![Screenshot 2020-02-10 at 16 10 08](https://user-images.githubusercontent.com/3828967/74156906-f537e680-4c1f-11ea-88df-ae3166cd129c.png)

You can check this on this page https://asjas.xyz/posts/andela-alc4.0-global-meetup/

**Comment by zzossig** [comment]
You are right. It looks so weird.
It seems to be better to center the description when a mobile view

**Comment by zzossig** [comment]
Thanks for the issue
ff3c1ee fix this

**Comment by Asjas** [comment]
Thanks 👍
