### ISSUE TITLE
How to set up SEO

### ISSUE THREAD

**Issue by cjade** [zzossig/hugo-theme-zzo#16]
??

**Comment by zzossig** [comment]
I don't understand what you mean.
![seo](https://user-images.githubusercontent.com/52706977/69899146-8e878880-13a5-11ea-8d59-00fcd52aa63f.png)

As you can see, the search engine already optimized. Can you tell me more specifically?

**Comment by zzossig** [comment]
Feel free to re-open this issue if you have a question.
