### ISSUE TITLE
Navigation bar in smaller window width with long logoText

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#160]
With longer logoText (say 30+ characters), when the broswer window width is greatly reduced (e.g. on mobile, but it is enough to narrow a browser window) the theme and search icons are properly placed. However the menu icon is not visible.
In addition that longer logoText could be truncated to do not overlaps the buttons.

In general it is a minor issue - it's enough to use shorter logoText, e.g. 15 characters.

**Comment by zzossig** [comment]
Thanks for the issue.
I made the icon visible when the logo text is long. 8fee402
But I don't want to truncate the logo text. it has to be the full text.

I think we can close this issue.
