### ISSUE TITLE
Is this alignment problem?

### ISSUE THREAD

**Issue by NghiaMaster** [zzossig/hugo-theme-zzo#164]
![Screenshot-2020-02-13-Archive.png](https://i.postimg.cc/C5m4Zfyy/Screenshot-2020-02-13-Archive.png)
Header of Archive page & about page
https://themes.gohugo.io//theme/hugo-theme-zzo/en/about
https://themes.gohugo.io//theme/hugo-theme-zzo/en/archive

**Comment by zzossig** [comment]
Opps this will be fixed soon

**Comment by zzossig** [comment]
It's fixed now!
