### ISSUE TITLE
Missing green color for texts in bio in hacker theme

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#168]
It seems there is something missing in the bio styling in the hacker theme:
![image](https://user-images.githubusercontent.com/148013/74466263-279f4900-4e97-11ea-82be-fd83c8e4c7dc.png)

**Comment by szpak** [comment]
And also in the submenu:
![image](https://user-images.githubusercontent.com/148013/74474724-596bdc00-4ea6-11ea-97be-5abc6108b1b0.png)

**Comment by zzossig** [comment]
Actually, I changed the color from light green to white. It’s on purpose.
