### ISSUE TITLE
Incorrent footer feed link on subpages

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#169]
The feed link in the page footer works for the main page. However, for subpages is take the current address as base and generates 404.

E.g. for
https://themes.gohugo.io//theme/hugo-theme-zzo/en/posts/shortcodes/
is it:
https://themes.gohugo.io//theme/hugo-theme-zzo/en/posts/shortcodes//index.xml
instead of:
https://themes.gohugo.io//theme/hugo-theme-zzo/en//index.xml

The same for blogs in one language.

**Comment by zzossig** [comment]
Ok, thanks for the issue!
I’ll do something on it!
I’m new to RSS feed so this happend 😋

**Comment by zzossig** [comment]
I need more information.
>What is the point of having a feed with a single post? Who would subscribe to it?

https://discourse.gohugo.io/t/rss-for-single-postings-single-xml/19491/2?u=zzo

**Comment by szpak** [comment]
I wasn't think that way, but in fact with some kind of pages you may want to subscribe to - let's say - updates (e.g. talks or posts, or even categories). I don't know what should it return for a regular blog post (even comments are out of the scope due to external implementation), so probably it depends what would be easier for you to implement - return just this post information or disable it.

**Comment by szpak** [comment]
I'm just entered the About page and realize that a feed icon there could be misleading. People might expect to subscribe to the new posts updates, not for "updates" of the "about" page :). Maybe it should be possible to disable the icon for particular types (or subscribe to the new posts on those pages)?

**Comment by zzossig** [comment]
I think when we click the rss button on a single page, we can generate the single page’s section list. e.g. shortcode.md file is in the posts section so we can serve the posts section for the rss link

Also, I’ll hide the rss button when the page is not allowed page.

Thanks for the test!

**Comment by zzossig** [comment]
Now, we can hide the feed icon in the footer when we are in the not allowed type pages.
And we can generate RSS feed in the single page as a section

**Comment by szpak** [comment]
> And we can generate RSS feed in the single page as a section

Do you mean, for example generate feed for talks when you are on the talk list page?

Btw, what is the easiest way to refer `homePage/index.xml` from markdown (to have a link in the content of the about page)?

I ended up with a deficated shortcode `home-url.html`:
```{{ .Site.Home.Permalink }}```

and call it:
```
[Feed]({{< home-url >}}/index.xml)
```
but I believe it can be done easier in Hugo.

**Comment by zzossig** [comment]
>Do you mean, for example generate feed for talks when you are on the talk list page?

When in a list page, the RSS feed button serves the list page.
When in a single(post) page, the RSS feed button also serves the list page since I don't want to link for a single article.

e.g:
When in a shortcodes post page, we generate feed
this
https://themes.gohugo.io//theme/hugo-theme-zzo/en/posts//index.xml
not this
https://themes.gohugo.io//theme/hugo-theme-zzo/en/posts/shortcodes/index.xml

>Btw, what is the easiest way to refer homePage/index.xml from markdown (to have a link in the content of the about page)?

How about `[feed](/index.xml)`?

**Comment by szpak** [comment]
> When in a single(post) page, the RSS feed button also serves the list page since I don't want to link for a single article.

:+1: 

One more idea for enhancement here. For pages link such as: `/categories/tricks-tips/` - where all articles from that category/tag/series are presented, the link could cover only articles from that group (i.e. those that are displayed on that page). People might want to subscribe only to one category from many.

> How about [feed](/index.xml)?

I tried it first, but for local development it generates `http://localhost:1313/index.xml` instead of `http://localhost:1313/blog//index.xml`.

**Comment by zzossig** [comment]
>so it is complicated to do, don't waste your time on it.

It's easy to do! Actually, I forgot to test the category/tag/series page.

>http://localhost:1313/blog//index.xml

You are using a sub URL!
Actually I don't know right now😋
I'll share it with you if I find a way of doing it.

**Comment by zzossig** [comment]
>ategory/tag/series are presented, the link could cover only articles from that group

I added the feature.

**Comment by szpak** [comment]
Thanks!
