### ISSUE TITLE
Questions about the license

### ISSUE THREAD

**Issue by gcushen** [zzossig/hugo-theme-zzo#17]
This Github repository fails to give proper attribution to the theme(s) that it copies/derives from.

**As this project appears to be (at least in part) a derivative work of the [Academic theme](https://github.com/gcushen/hugo-academic/issues)**, please keep the original Academic license and copyright notice packaged in your distribution, as per Academic's MIT license. You had the license file, with copyright notice, packaged [until recently when you defaced the Academic license/copyright](2fe99cc11762acba0e39563c1c782659377ceb9d).

Also, Hugo Themes Site enable you to properly attribute original work that a project is partially based on by editing `themes.toml`. For example,

```
[original]
  name = "Academic"
  homepage = "https://sourcethemes.com/academic/"
  repo = "https://github.com/gcushen/hugo-academic/"
```

Please kindly revert your defacement to Academic's license and copyright notice.

**Comment by zzossig** [comment]
This theme is not the modification of academic theme. It was my mistake to include your name in the LICENSE.md file. So I changed it. Your project and mind is totally different.And you didn't contribute for this theme at all. Why are you saying that?

**Comment by gcushen** [comment]
If you refuse to comply with Academic's MIT license then we will consider escalating this.

The MIT license requires that you include Academic's license and copyright notice and revert your attempts to deface it. If you have a problem understanding the MIT license then I suggest you seek legal advice.

**Comment by zzossig** [comment]
Hey.. you know that the code base is totally different. That was a mistake that I included your name in README.MD file.

**Comment by gcushen** [comment]
I'm glad that you were inspired by the Academic Page Builder for Hugo.

You appear to claim to have changed significant parts of the code and only have small parts of the Academic codebase remaining. All I am asking is for you to attribute the code that you copied and respect the MIT license by including the copyright notice in the MIT license that you also copied. You were complying with the license until recently, when you choose to remove Academic's copyright notice. Why is it so difficult to revert the defacement to the license and include any other additional copyright notices for yourself and any of the other themes which you mentioned you copied code from.

**Comment by zzossig** [comment]
I made this project from zero bases. Not forked from your project. I don't mind mentioning the code I referenced, but I created this project from scratch and I own it, and I think my name should be in the license and not others.

**Comment by gcushen** [comment]
It does not matter if you copied code from other themes by forking or by other methods.

What matters is that you properly attribute all the code that you copied and include the copyright notices of those themes. If you need clarification of the MIT license, then you can seek legal advice.

**Comment by zzossig** [comment]
I'll delete all the parts that are related to the Academic theme. Then, everything should be fine?

**Comment by zzossig** [comment]
@gcushen Can you point me to the portions of code that should I fix?

**Comment by zzossig** [comment]
@gcushen There is no more code left that I copied from your theme. If you find anything that from your code, just tell me. I'll remove it from my theme. thanks
