### ISSUE TITLE
Ability to configure what kind of pages should be included in feed

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#170]
Currently feed seems to include all the pages (also showcase, talks, etc.). It should be configurable, e.g. `allowedTypesInFeed`, probably with posts only allowed by default.

**Comment by zzossig** [comment]
Good idea!

**Comment by zzossig** [comment]
I add a new option `notAllowedTypesInHomeFeed` instead of `allowedTypesInFeed` for consistency and that is my preference!

**Comment by szpak** [comment]
`*homeFeed` makes sense in the context of #169. `allowed*` would be probably more convenient, but `notAllowed*` is definitely more consistent with existing properties and in the end there is usually not so many different types used.
