### ISSUE TITLE
[Feature] Add badges in showcased cards for github projects

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#173]
It is possible to add badges for all public repositories.

![Screenshot from 2020-02-16 01-41-54](https://user-images.githubusercontent.com/2096087/74597314-be1d6700-505d-11ea-83c3-53fb2bd5d2e0.png)

Would be nice to have, those in the showcase cards.

The code for is as below (taken from my own repo):

```
[![GitHub stars](https://img.shields.io/github/stars/nisrulz/android-tips-tricks.svg?style=social&label=Star)](https://github.com/nisrulz/android-tips-tricks) [![GitHub forks](https://img.shields.io/github/forks/nisrulz/android-tips-tricks.svg?style=social&label=Fork)](https://github.com/nisrulz/android-tips-tricks/fork) [![GitHub watchers](https://img.shields.io/github/watchers/nisrulz/android-tips-tricks.svg?style=social&label=Watch)](https://github.com/nisrulz/android-tips-tricks) [![GitHub followers](https://img.shields.io/github/followers/nisrulz.svg?style=social&label=Follow)](https://github.com/nisrulz/android-tips-tricks)
```
Copy pasted code here to see it live:
[![GitHub stars](https://img.shields.io/github/stars/nisrulz/android-tips-tricks.svg?style=social&label=Star)](https://github.com/nisrulz/android-tips-tricks) [![GitHub forks](https://img.shields.io/github/forks/nisrulz/android-tips-tricks.svg?style=social&label=Fork)](https://github.com/nisrulz/android-tips-tricks/fork) [![GitHub watchers](https://img.shields.io/github/watchers/nisrulz/android-tips-tricks.svg?style=social&label=Watch)](https://github.com/nisrulz/android-tips-tricks) [![GitHub followers](https://img.shields.io/github/followers/nisrulz.svg?style=social&label=Follow)](https://github.com/nisrulz/android-tips-tricks)

Notice how the base url has section with username, the same as `repo` in the showcase page's metadata after github.com
![Screenshot from 2020-02-16 01-49-00](https://user-images.githubusercontent.com/2096087/74597366-98449200-505e-11ea-9eda-e20a24e7cad4.png)

**Comment by zzossig** [comment]
Ok, I'll try

**Comment by zzossig** [comment]
When I add the links to the meta, it looks like this which is not quite good
![주석 2020-02-16 163917](https://user-images.githubusercontent.com/52706977/74601000-4cd0c900-50dc-11ea-870b-311689c6301b.png)

How about making the description markdownify so we can add the link to the description.
![주석 2020-02-16 165146](https://user-images.githubusercontent.com/52706977/74601039-a507cb00-50dc-11ea-87a4-0373483ad813.png)

**Comment by zzossig** [comment]
In your md file

`showcase/hugo/hugo-theme-zzo.md`

```yaml
...
shields:
- name: GitHub stars
  image: https://img.shields.io/github/stars/nisrulz/android-tips-tricks.svg?style=social&label=Star
  link: https://github.com/nisrulz/android-tips-tricks
```

You can also take advantage of markdown syntax in `description`

```yaml
---
title:
description: "your markown"
---
```

**Comment by nisrulz** [comment]
The markdown version in the description works for me. Thank you :rocket:
