### ISSUE TITLE
Blockquote needs to be right side in rtl

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#175]
I think Blockquote should be on the right side in RTL mode here is my Blockquote in rtl:

![image](https://user-images.githubusercontent.com/34630603/74608357-9083fc80-50f5-11ea-9fc4-7306c29ed00f.png)

**Comment by zzossig** [comment]
I update it just now.

**Comment by Gictorbit** [comment]
oh my goodness thank you
