### ISSUE TITLE
(How to?) Disable or reduce animation on pageloads.

### ISSUE THREAD

**Issue by woolwood** [zzossig/hugo-theme-zzo#176]
One thing has been bothering me, and that's the distracting lead-in animation on every page load. I tried to disable this by editing the CSS, but unfortunately I just ended up breaking drop-down menus along with it.

**Comment by zzossig** [comment]
I'll make new option for disabling the animation

**Comment by zzossig** [comment]
I added new param `enableUiAnimation`

`params.toml` file,
```toml
...
enableUiAnimation = false
```

**Comment by woolwood** [comment]
Unfortunately, this breaks the dropdown menu to select a theme.
In Firefox 73.0 on X11/Linux:

```enableUiAnimation = false```
![Screenshot_20200216_193717](https://user-images.githubusercontent.com/35411775/74610498-0edf9f00-50f4-11ea-9c38-4ead236fc500.png)


```enableUiAnimation = true```
![Screenshot_20200216_193649](https://user-images.githubusercontent.com/35411775/74610499-0f783580-50f4-11ea-983b-e2e1ec790b39.png)

**Comment by zzossig** [comment]
Thanks for the test.
It's fixed now

**Comment by woolwood** [comment]
Yes it is—thanks!
