### ISSUE TITLE
alert shortcode needs to be right side in Rtl mode

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#177]
It could be better if alert shortcode supports rtl mode
![image](https://user-images.githubusercontent.com/34630603/74629873-87834180-516e-11ea-8856-9c197b56aca7.png)

**Comment by zzossig** [comment]
You can do this.
```
{{< alert theme="" dir="rtl" >}}
{{< /alert >}}
```
