### ISSUE TITLE
image shortcode caption and title align

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#178]
I think if the caption and title of IMG shortcode have center align is better than right align
this is the bottom of the image
![image](https://user-images.githubusercontent.com/34630603/74630444-da112d80-516f-11ea-8c3f-2d7034c164ac.png)

**Comment by zzossig** [comment]
you can do this
```
{{< img src="" position="center" ... >}}
```

**Comment by Gictorbit** [comment]
nice thank you so much
