### ISSUE TITLE
Possible enhancements in RSS feed

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#179]
Hello again. After a hiatus during weekend to think about the things I am back with some RSS-related enhancements proposals :).

I subscribed to my new test blog from [TinyTinyRSS](https://tt-rss.org/) and in comparison to the [feed from Wordpress](https://solidsoft.wordpress.com/feed/) which hosts the current version of my blog there are some XML elements which could be added:

 - author (per post) - `<dc:creator>`
 - tags (per post) - `<category>`

At the whole feed level there could be added update related fields (https://www.feedforall.com/syndication.htm), for example:

```
<sy:updatePeriod>hourly</sy:updatePeriod>
<sy:updateFrequency>1</sy:updateFrequency>
```

Btw, Wordpress uses `<![CDATA[` for the post description. I don't know if you quote it on your own, to do not break XML in specific cases.

**Comment by zzossig** [comment]
Hello!
Ok, I'll make it soon.

>Btw, Wordpress uses <![CDATA[ for the post description. I don't know if you quote it on your own, to do not break XML in specific cases.

I think the link (https://solidsoft.wordpress.com/feed/) generates text so it maybe needs to do some escape for making it `xml` in the future. But, Hugo generate `xml` right away for us. So we don't need to use escape syntax.

**Comment by zzossig** [comment]
I added all of them

`params.toml`
```toml
...
updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false
```

**Comment by szpak** [comment]
Thanks! It works fine, but my feed reader seems to expect `<dc:creator>` at the post level, not the whole feed (and it ignores it). Could it be changed?

In addition it might to [good](http://www.rssboard.org/rss-profile#namespace-elements-dublin) to add namespace description do `<dc:` (and along the way also for others) in the leading rss tag, e.g.

```
<rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
        xmlns:media="http://search.yahoo.com/mrss/">
```

**Comment by szpak** [comment]
Btw, atom feeds allow to [define](https://validator.w3.org/feed/docs/atom.html#requiredEntryElements) also an `updated` field (at the **entry level**). It would be nice to put it if `lastmod` is used in the blog post - to inform feeders that there was some change in the content.

Sample usage in the RSS 2.0 feed:
http://grumet.net/weblog/archives/rss-with-atom-example.html

**Comment by zzossig** [comment]
I added them all.
I think all is working now. Maybe?

**Comment by szpak** [comment]
It is, thanks!
