### ISSUE TITLE
There is a problem with the toc on PC and the return top button on mobile

### ISSUE THREAD

**Issue by fandean** [zzossig/hugo-theme-zzo#18]
The toc display on PC is the same as here [Markdown Syntax Guide – Hugo Zzo Theme](https://themes.gohugo.io//theme/hugo-theme-zzo/en/posts/markdown-syntax/)
![image](https://user-images.githubusercontent.com/25637720/69909812-9560da80-143b-11ea-81d0-e217b2ce5532.png)

The go to top button on the mobile seems to behave strangely. When I select "中文", 
![image](https://user-images.githubusercontent.com/25637720/69909787-49159a80-143b-11ea-9998-756fae443858.png)

the first post looks like this, 
![image](https://user-images.githubusercontent.com/25637720/69909792-52066c00-143b-11ea-98a4-c6fbbc617bb4.png)

the second post looks like this, 
![image](https://user-images.githubusercontent.com/25637720/69909796-59c61080-143b-11ea-95a8-4aea5758e56f.png)

and the third post appears normal.
![image](https://user-images.githubusercontent.com/25637720/69909798-60ed1e80-143b-11ea-93b1-37c07e1ab9f5.png)

**Comment by zzossig** [comment]
Ah ok, I'll look into it. Thanks!

**Comment by zzossig** [comment]
@fandean Hey~ I really appreciate you keep interesting my project! I have a question. When did you update your blog? I fixed grid bugs 12 hours ago.

**Comment by fandean** [comment]
Here is my git log output

```shell
 zzo   master 
λ git lg
* 7d87627 2019-12-01 style file clean up, grid bug fixed, prepare for presentation page(reveal.js)  (HEAD -> master, origin/master, origin/HEAD) <zzossig>
* 07b6712 2019-11-30 Example site update  <zzossig>
* 152145f 2019-11-29 whoami, bio, img shortcode image lazyload,  <zzossig>
* 2fe99cc 2019-11-29 comment added to config files, lazy summary image load, better html tag, better mobile icon, license update  <zzossig>
```

when I run the 'Hugo server' command on my local computer, TOC has no problem.
But when I deploy to the managed server, it will be the same as the zzo theme demo site.


> On my local computer, The command will have the following prompt
> ```shell
>  hugoblog   master ± 
> λ hugo server
> WARN 2019/12/01 12:33:55 Module "zzo" is not compatible with this Hugo version; run "hugo mod graph" for more information.                                                                                    r more information.
> project zzo
> 
> λ hugo version
> Hugo Static Site Generator v0.59.1/extended windows/amd64 BuildDate: unknown
> ```

**Comment by zzossig** [comment]
I checked your blog! pretty nice😁
When I inspect your blog, you are not using the latest version of the Zzo theme.
Can you update your blog to the latest?

**Comment by fandean** [comment]
This is because the zzo theme is very, very good

This is my first time to use the git submodule. I don't know much about it

**Comment by zzossig** [comment]
Thanks, bro~
I also a newbie in the open-source world.
I still keep learning to program. This project is my first step.
I also don't know much about git submodule. 😭
Anyway, I want to see when you update the Zzo theme to the latest version and works well.

**Comment by fandean** [comment]
Hi, I seem to have updated it, but

**Comment by zzossig** [comment]
Oh, I see, you updated new version!

**Comment by zzossig** [comment]
@fandean I just fixed it now! Can you update one more?

**Comment by fandean** [comment]
Unable to connect to "github" from my command line.It wastes a lot of my time. It's so sad 😢 
```shell
ping github.com

Pinging github.com [52.74.223.119] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.
```

**Comment by zzossig** [comment]
I'm so sorry about that 😢. How do you update your site? How about using a graphic user interface instead of using command line?

**Comment by fandean** [comment]
I generally use the following methods to update websites
```shell
git submodule update --remote --merge
git add .
git commit -m ...
git push
```
I just tried using vs-code's sync change feature, and it worked.

thank you

**Comment by zzossig** [comment]
So we can close this issue now? It works well on your end?
