### ISSUE TITLE
Display sidebar after articles in mobile view?

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#181]
Currently the sidebar is completely removed in the mobile view. As it can contain some important information, I wonder, if you think it would be possible (and sensible) to display it after the main content?

**Comment by zzossig** [comment]
I'm currently thinking that it's not sensible.
What is the important information?
As far as I know, the sidebar has toc and post list, tags, categories, series, bio which is don't need to be displayed in a mobile view.
What information do you want to display?

**Comment by szpak** [comment]
You are probably right. The posts and some important pages should be reachable using the menu.
