### ISSUE TITLE
Unable to get robots.txt file generated

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#182]
According to the Hugo [documentation](https://gohugo.io/templates/robots/) it should be enough to set `enableRobotsTXT = true` in `config.toml` to have a permissive `robots.txt` generated. Unfortunately it doesn't work (404). Putting a file in `/layouts/robots.txt` doesn't change anything.

I wonder, if there could be anything in zzo theme to filter it out?

I can put `robots.txt` in `/static` and it works, but having it generated by Hugo allows me to modify its content based on set  environment variables (e.g. to disabled crawling on public `test/devel` environment).

**Comment by zzossig** [comment]
> Unfortunately it doesn't work (404)

I think it's the Hugo issue. I didn't do anything related to the `robot.txt` file.

And I don't understand why you need the Hugo to generate the `robots.txt` file?
I think it's not a big deal to specify some paths in the robot.txt file that you don't want to be scrapped.
e.g
```
User-agent: *
Disallow: /test/devel
```

Maybe this link helps https://discourse.gohugo.io/t/custom-robots-txt-and-sitemap-xml-templates/11869

**Comment by szpak** [comment]
> Maybe this link helps https://discourse.gohugo.io/t/custom-robots-txt-and-sitemap-xml-templates/11869

I know that thread and there is an example of custom logic shown. I deploy automatically from Netlify and when the build it from (let's say) the devel branch (which result in the another domain, not path) I would like to have:
```
User-agent: *
Disallow: /
```

For the production site it is not the best possible configuration :-).

Of course I have put different files in `/static` in different branches, but it is fragile. The logic there to check for the environment variable set to disable crawlers seems nicer.

> I think it's the Hugo issue. I didn't do anything related to the robots.txt file.

Ok, I will try to the vanilla Hugo.

**Comment by szpak** [comment]
The problem was my insufficient experience with `toml`. Just as a reference for others:

```
[permalinks]
  posts = "/:year/:month/:day/:title/"

enableRobotsTXT = true
```
doesn't work and `enableRobotsTXT` has to be put before the first nested configuration.
