### ISSUE TITLE
add Header Bar/Address Bar color support in browser for Android

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#183]
I think this feature could help to look and feel of themes. I think it's possible with adding some simple meta tag like this
```
!-- Chrome, Firefox OS and Opera -->
<meta name="theme-color" content="YOUR-COLOR-HERE">
<!-- Windows Phone -->
<meta name="msapplication-navbutton-color" content="YOUR-COLOR-HERE">
<!-- iOS Safari -->
<meta name="apple-mobile-web-app-status-bar-style" content="YOUR-COLOR-HERE">
```

**Comment by zzossig** [comment]
Ok, I added it!

**Comment by Gictorbit** [comment]
is it the same color for all theme modes?
I mean, your theme has 5 different modes [dark, light, hacker,...] and for each mode themecolor meta tag is different and I think it could be perfect if the header bar has the same color of the navbar.
for example, when user choose a dark theme, header bar color changes to the navbar background color as it's dark or when choose light theme header bar would be white

**Comment by zzossig** [comment]
You are right.
Ok, I’ll find a way how to set theme color dynamic

**Comment by zzossig** [comment]
@Gictorbit Can you check again?

**Comment by Gictorbit** [comment]
headbar color changed but has the same color in all modes
![Untitled-1](https://user-images.githubusercontent.com/34630603/74744536-af120100-5277-11ea-9e3a-c04e6e047bfb.jpg)

**Comment by zzossig** [comment]
Can you check the google dev tool?
![주석 2020-02-18 232720](https://user-images.githubusercontent.com/52706977/74744845-44c48500-52a6-11ea-902f-432c11f1344c.png)

**Comment by Gictorbit** [comment]
Meta tags were added which is great but what I wanted was to change the color of the top bar with the theme change I mean each theme mode could have own header color something like this
for dark:
```
<meta name="theme-color" content="#403e41">
<meta name="msapplication-navbutton-color" content="#403e41">  
<meta name="apple-mobile-web-app-status-bar-style" content="#403e41">
```
for light:
```
<meta name="theme-color" content="#eeeeee">
<meta name="msapplication-navbutton-color" content="#eeeeee">  
<meta name="apple-mobile-web-app-status-bar-style" content="#eeeeee">
```
for hacker
```
<meta name="theme-color" content="#252526">
<meta name="msapplication-navbutton-color" content="#252526">  
<meta name="apple-mobile-web-app-status-bar-style" content="#252526">
```
for solarized
```
<meta name="theme-color" content="#eee8d5">
<meta name="msapplication-navbutton-color" content="#eee8d5">  
<meta name="apple-mobile-web-app-status-bar-style" content="#eee8d5">
```
for kimbie
```
<meta name="theme-color" content="#51412c">
<meta name="msapplication-navbutton-color" content="#51412c">  
<meta name="apple-mobile-web-app-status-bar-style" content="#51412c">
```

**Comment by zzossig** [comment]
Opps, sorry, I just check that the color not changing dynamically.
I'll look into it

**Comment by zzossig** [comment]
Now, it is changing dynamically!

**Comment by Gictorbit** [comment]
awsome
thank you a lot
