### ISSUE TITLE
header doesn't work

### ISSUE THREAD

**Issue by FalcoN1995** [zzossig/hugo-theme-zzo#187]
i try to make my blog but header doesn't work !!! I made a mistake somewhere?

I set config/_default/config.toml and config/_default/params.toml.
and I set homeHeaderType

my blog is https://FalcoN1995.github.io

**Comment by szpak** [comment]
Do you have [`_index.md`](https://github.com/zzossig/hugo-theme-zzo/blob/master/exampleSite/content/en/_index.md) file in the `content` directory (as mentioned in the [README](https://github.com/zzossig/hugo-theme-zzo#custom-header) file?

Is there the source repository available?

**Comment by zzossig** [comment]
I suspect you didn’t read documentation.
Check this link https://zzodocs.netlify.com/docs/gettingstarted/quickstart/
