### ISSUE TITLE
Photos in gallery are poorly stretched when viewed on smartphone devices

### ISSUE THREAD

**Issue by Nianze** [zzossig/hugo-theme-zzo#188]
Site built with the latest zzo will generate the gallery photos in a poor way. This can be reproduced by visiting the [demo website gallery page](https://themes.gohugo.io//theme/hugo-theme-zzo/en/gallery/photo) on a iPhone safari browser.

**Comment by Nianze** [comment]
![1C9078B1-1023-4FAB-9F21-69A6669C20F3](https://user-images.githubusercontent.com/4755792/74878704-cadbdc80-5335-11ea-92ca-6e71d07bd658.png)

**Comment by zzossig** [comment]
Yes, it is.
And some other bugs out there.
I’ll fix all of them

**Comment by zzossig** [comment]
I made some changes.
Can you check again?

**Comment by Nianze** [comment]
Cool thanks so much for the quick fix! I can confirm that the image is presented in the proper scale now. 

However it seems the 'full screen' and 'close' button originally showing up around upper-right corner is missing after clicking into the pictures on smartphone devices (it is outside of the screen area by default now)

**Comment by zzossig** [comment]
I also use iphone11 and the phone screen has longer height than usual phone.
If you swipe up the screen, the toolbar will show up. I’ll think about it more.

**Comment by Nianze** [comment]
Yeah you are right. It shows up when I scroll down a little bit, so not a big problem now.

**Comment by zzossig** [comment]
I made the gallery using some other libraries.
I tried some tricks but none of them worked.
I'll close this issue now.
But if some more people ask about it, I'll spend more time on it.

**Comment by Nianze** [comment]
Thanks again for the fix 👍

**Comment by trashken** [comment]
The problem persists in MacOS Safari though. Can you check?
