### ISSUE TITLE
How to add Google Analytics? It doesn't seem to work

### ISSUE THREAD

**Issue by fandean** [zzossig/hugo-theme-zzo#19]
```toml
google_analytics  = "<my-id>"
```
It doesn't seem to work. 

> Google tag assistant prompt:
>
> result of Tag Analysis :  2 In total    2 Errors.
>
> Where to optimize : [No HTTP response detected](https://support.google.com/tagassistant/answer/3059154#http_response)

**Comment by zzossig** [comment]
Hmm, I haven't tested it yet. I'll do this just a moment

**Comment by zzossig** [comment]
@fandean It seems like google analytics not working now. I'm not familiar with this part. I have to investigate more. Do you want to use Google analytics and google tag manager both or just google analytics? I need some time for doing this

**Comment by fandean** [comment]
I just need Google Analysis. It's not urgent

**Comment by zzossig** [comment]
Ah Ok~ Until then, we can keep this issue open.

**Comment by Jason-cqtan** [comment]
just put this code in /layouts/partials/head/meta.html,its work.
```html
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=<my-id>"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', '<my-id>');
</script>
```

**Comment by Jason-cqtan** [comment]
兄die，你好呀

**Comment by zzossig** [comment]
Thanks for the information! I'll try it😄

**Comment by zzossig** [comment]
I just moved the googleAnalytics param from params.toml to config.toml file. And I just followed the [Hugo docs guidelines](https://gohugo.io/templates/internal#google-analytics). So, just set the googleAnalytics param to your ID. I've not tested it yet because It needs to host a website. I hope it works.

**Comment by fandean** [comment]
Hi, it's working

**Comment by zzossig** [comment]
Sounds great!

**Comment by enricodata** [comment]
did you add the code in the format:
googleAnalytics: "G-01234xxxxx"
in config.yaml ?

It does not work like that on my side.
