### ISSUE TITLE
new UI for drop-down menu in mobile

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#192]
in the mobile responsive mode of the blog the tags, categories, and series section not shown
I thought a new drop-down sidebar menu could cover these with new UI something like this

<img src="https://user-images.githubusercontent.com/34630603/74938896-22e11480-5404-11ea-8e61-c96d8209cea8.png" width="300" />

**Comment by zzossig** [comment]
Actually, I don't agree with you.
The UI is totally different from the current one.
And it will take a lot of time for me.
If the mobile menu should contain the taxonomies(tags,categories,series) it must be contained current dropdown menu

**Comment by Gictorbit** [comment]
Ok I know. It was just a suggestion
thank you for your response

**Comment by zzossig** [comment]
But do you think the taxonomies(tags, categories, series) should include in the mobile menu?
I'm curious if it will be a helpful feature for some people

**Comment by Gictorbit** [comment]
It's not obligatory
however sometimes the user may want to check all post of a series from mobile, in this case, It's not possible if we not provided  taxonomy page in the menu
anyway I will add the series page into the menu depends on demand

**Comment by zzossig** [comment]
Ok, I'm thinking that it could be a helpful feature.
I'll make options for it.

**Comment by Gictorbit** [comment]
nice, thank you so much :1st_place_medal:
