### ISSUE TITLE
Social links open in new window?

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#194]
I wonder, if it would make sense also for you to open social links (mostly icons in a few places) in the new window (`_blank`)? Currently they open inline which may be unexpected for visitors.

**Comment by zzossig** [comment]
I thought that I made all of the links open in a new window.
Can you point me where it is?

**Comment by szpak** [comment]
Maybe not the icons :)

In `site-bio.html`:
```
      <a href="{{ $path | safeURL }}" title="{{ $name }}" aria-label="{{ $name }}">
        {{ partial (print "svgs/social/" $name ".svg") (dict "width" 25 "height" 25) }}
      </a>
```
The same with the icons in the post summary.

**Comment by zzossig** [comment]
>In site-bio.html

Yes! Maybe I forgot to add `target="_blank" rel="noreferrer"`

>The same with the icons in the post summary.

Are there any other links that inline open?

**Comment by szpak** [comment]
In addition to 3x social icons probably only those in the footer:
![image](https://user-images.githubusercontent.com/148013/74954575-9afb0a80-5403-11ea-82eb-500ef3e3a484.png)

I will let you know if found anything else.

**Comment by zzossig** [comment]
Thank you so much!

**Comment by zzossig** [comment]
I added the missing `target=_blank` to the links you mentioned above!
Thanks!
Open a new issue if you find another one.
