### ISSUE TITLE
Could not start hugo server because of "FirstSection"

### ISSUE THREAD

**Issue by WingLim** [zzossig/hugo-theme-zzo#195]
hugo version: 0.65.2
theme version: lastest

I try in Linux Mac and Windows, they got same problem

```
Error: Error building site: render of "404" failed: execute of template failed: template: 404.html:37:15: executing "404.html" at <partial "footer/site-footer" .>: error calling partial: execute of template failed: template: partials/footer/site-footer.html:3:7: executing "partials/footer/site-footer.html" at <partial "footer/links-social.html" .>: error calling partial: execute of template failed: template: partials/footer/links-social.html:11:7: executing "partials/footer/links-social.html" at <partial "footer/links-feed.html" .>: error calling partial: "/Users/winglim/Documents/blog/themes/zzo/layouts/partials/footer/links-feed.html:5:31": execute of template failed: template: partials/footer/links-feed.html:5:31: executing "partials/footer/links-feed.html" at <.FirstSection.Permalink>: error calling FirstSection: runtime error: invalid memory address or nil pointer dereference
```

I using the theme with your README, it failed:
```
git submodule add https://github.com/zzossig/hugo-theme-zzo.git themes/zzo
cd themes/zzo/exampleSite
hugo server --themesDir ../..
```

Then I copy the exampleSite to the site root folder, it still failed.

I though it might be my configure the zzo theme wrong, so I clone your blog souce, it success

```
git clone https://github.com/zzossig/blog.git
cd blog
hugo server
```

that really mess me up

and I try the hugo offical's quick start, it works. so the hugo has no problem

waitting for you reply, thx

**Comment by zzossig** [comment]
It's really weird.
This does not happen before.
Can you update the theme and check again?
I made some changes

**Comment by WingLim** [comment]
https://github.com/gohugoio/hugo/commit/4c2a0de412a850745ad32e580fcd65575192ca53

https://github.com/gohugoio/hugo/commit/f46053034759c4f9790a79e0a146dbc1b426b1ff

This two commit has fix this bug, I try and works. The new ```0.65.2```  can use your theme now.

Thanks a lot.
