### ISSUE TITLE
[Mostly meant for discussion] What are the possibilities of integrating with `hugo-academic`?

### ISSUE THREAD

**Issue by ionlights** [zzossig/hugo-theme-zzo#196]
I'm cross-referencing this: gcushen/hugo-academic#1565

I love the styling of `zzo`! However, as a researcher, I find many of the features from `hugo-academic` quite desirable. (e.g. publications, posts, slides, talks, authors, and projects.)

I think there's some synthesis that might be mutually beneficial to both `hugo-academic` and `zzo`, but am unsure of what that kind of integration would look like. So figured I'd start a conversation between us.

What are your thoughts on this?

**Comment by zzossig** [comment]
The zzo theme already has publications, projects(showcase page), posts, slide(presentation page), talks page.

What do you mean `integration`.
Since the two themes totally different code base so I don't think the two themes can mutually beneficial.

**Comment by ionlights** [comment]
> **NB:** I think I should be clear about this – I'm not suggesting that you're the only participant in developing some sort of migration/synthesis/what-have-you. I'm mostly looking to see where you stand on the possibility of something like this and what constraints might exist.

## So, I think this is an adequate summarization
`zzo` has many of the features in `academic`; however, `zzo`'s implementations aren't quite as developed. I would attribute this lag to project age, as `academic` is going on 4 years old while `zzo` is about 4 months old.

## What I mean by "integration"
Given the current state of both `academic` and `zzo`, I think most of the integration would involve:
- migrate `zzo` styling (`assets/{js,scss}`) to `academic`
- discern an optimal way to setup `_layouts` to support `academic` and `zzo` "skins"
- migrate `academic` to a grid-based CSS system, like `zzo` has

**Certainly, this would _not_ be a singular effort on your end.** However, I think some components may start with you (as you're clearly the most knowledgeable of `zzo`).

My primarily rationale for proposing this transition is that while I prefer `zzo`'s look-and-feel, `academic`'s feature-set is quite thorough and very useful. While `zzo` could always reach this degree of capability, it's re-inventing the wheel, which seems like a sub-optimal use of time.

### A note on hosting an open-source project
I totally get that `zzo` has a special place in your heart because you can point to it and say "I built this from nothing and it's helping X people." But I also see tremendous value in extending `academic`'s platform with "skins," as the current layout creates a lot of bland websites.

### Different code-bases
While it's true that the code bases are different, I'm skeptical to toss up hands just over that – without doing a proper investigation on how difficult adjusting `academic` and `zzo` to support each other might be.

## A bit of a comparison
> The zzo theme already has publications, projects(showcase page), posts, slide(presentation page), talks page.

**Agreed.** However, many of these lack the feature-set that `academic` provides, especially in terms of ready-to-use components that can be placed across the site.

### Publications
Features in `academic`:
- Reference co-authors (requires a built-in author's layout) – this works on both personal and organization pages
- Different presentation layouts based on type of research publication
- Filtering is explicit. (I believe `zzo`'s "search" could do this, but it's not as clear that one would strictly extract publications matching the query.)

### Posts
Features in `academic`:
- Posts can be attached (analogous to how showcases categorize) to `projects`, `publications`, and `talks`.
- Posts may also have slides attached to them.
- Posts (and `projects`, `publications`, `talks`, etc.) can be cross-referenced across the site easily (and in some cases automatically).
- Multiple authors – specified globally with author profiles. (This also applies to `projects`, `publications`, etc.)
> **NB:** I haven't tested the full extent of cross-linking/reference in `zzo`. From what I've read in the documentation, though, this __wouldn't__ be possible. As `showcases` are directory-based. `series` might be able to capture this, but that doesn't work well in the case that a project has multiple posts, publications, talks, and slides. 

### Slides
Can't comment on – haven't looked into this, but (as the documentation says, you're disinclined to use this, so it's likely not a first-class feature.)[https://zzodocs.netlify.com/docs/pages/presentation/]

### Talks
Features from `academic`:
- Cross-linking/referencing I've mentioned earlier.

**Comment by zzossig** [comment]
> I'm not suggesting that you're the only participant

In that case, I don't want to participate

> what constraints might exist.

We can do anything if we want. But there is a significant amount of `time` and `effort` consumed.

>  however, zzo's implementations aren't quite as developed

No, My theme's implementation is better than Academic

> What I mean by "integration"

For each project, development should be done independently. Since the Academic theme not designed dynamic color change, there will be a significant amount of time to do that.
I can make PR regarding styling, but in that case, I insist that my name should be specified in the license file in the Academic repository which is I don't think Cushen will accept this.

>  without doing a proper investigation on how difficult adjusting academic and zzo

Academic theme using a 3-party library(bootstrap) for styling, And Zzo theme is not using any styling library. So, If there will be integration, Cushen may have to redesigns the styling.

> Agreed. However, many of these lack the feature-set that academic provides, especially in terms of ready-to-use components that can be placed across the site.

I don't think Zzo theme lacks the feature-set that academic provides(Just the two theme has different concepts to provide contents). If you want to make change something, open a new issue in this repository. I'll make it better with your suggestions.

**Comment by ionlights** [comment]
> > I'm not suggesting that you're the only participant
> 
> In that case, I don't want to participate

What do you mean by this? Are you looking to be the sole contributor to something like this?
I was stating that you __wouldn't__ be the only person involved in a change like this.

> > however, zzo's implementations aren't quite as developed
> 
> No, My theme's implementation is better than Academic

That's subject to opinion, but all right.

> I can make PR regarding styling, but in that case, I insist that my name should be specified in the license file in the Academic repository which is I don't think Cushen will accept this.

What do you mean by this? Are you saying that your name should be present in: https://github.com/gcushen/hugo-academic/blob/master/LICENSE.md 🤔 

Would you making further contributions to `hugo-academic` with style updates that would be made to `zzo`?

**Comment by zzossig** [comment]
> What do you mean by this? Are you looking to be the sole contributor to something like this?
I was stating that you wouldn't be the only person involved in a change like this.

If you want to use an academic theme and want to change the color theme dynamically like zzo theme, ask about it to Cushen(the owner of the academic theme).
If you want to use zzo theme, you can make an issue here.

What you said is not a trivial job to do. The two themes have a different concept and not designed to benefit each other.

> What do you mean by this? Are you saying that your name should be present in:

Yes, when If I contribute to the hugo-academic repository.

> Would you making further contributions to hugo-academic with style updates that would be made to zzo?

I didn't contribute anything to `hugo-academic`. Don't have a plan to contribute in the future.

**Comment by ionlights** [comment]
> What you said is not a trivial job to do. The two themes have a different concept and not designed to benefit each other.

I'm quite aware of what kind of ask this is... I did web development for about 6 years. 
I'm not sure what you mean by "... not designed to benefit each other." – the defining line between `zzo` and `academic` seems to be `zzo`'s visual styling. Otherwise the intended audiences seem to overlap quite a bit.

> If you want to use an academic theme and want to change the color theme dynamically like zzo theme, ask about it to Cushen(the owner of the academic theme).
> If you want to use zzo theme, you can make an issue here.

Personally, I have minimal preference on the ability to allow users to change the color scheme. The main use `zzo` has, for me, is the visual layout.

> I didn't contribute anything to `hugo-academic`. Don't have a plan to contribute in the future.
> But the hugo-academic theme owner accept my name specified the license file, I'll make some contributions

So, I'm not insinuating you contribute or anything of the sort. I'm mostly getting a feel for what your "terms" might be, in the case George is interested in expanding `academic`'s support for alternate themes.

**Comment by zzossig** [comment]
> not designed to benefit each other

I think I select the wrong word because of language. I mean, It will take plenty of time to do this ->`What I mean by "integration"`

I'll wait other people's opinion(mostly George)

**Comment by nisrulz** [comment]
Just my 2 cents on this topic. I use zzo theme already.

Merging two projects would be good chunk of work. Anyone who has done web development would agree "just changing layout/visual styling" is not as easy as said. 

If still that is something someone wants to do, the project is open sourced  and anyone is free to make the changes. I think the maintainer here has made it quite vocal they don't want to take on the huge task of "integrating" two themes. 

What started as a "discussion" issue is now turning into "demanding" extra free work.

Please open a PR to bring parity on either side of the platform or even kick of what you wish to have in the project with a subset PR.

This project is built by the maintainer and is supported by contributions from the community. If someone requires a functionality they open an issue, discuss feasibility as well as provide possible solutions. Then eventually either tries to help by opening a PR or asking for directions from the maintainer itself.

**Comment by ionlights** [comment]
@nisrulz I'm well aware something like this *is not simple*. To the best of my knowledge, I've not proposed it was simple to begin with – anything that conveyed otherwise was a printed misstep.

I've opened this as a question largely because there's already significant overlap between both projects. The largest distinctions are the support and utilities that `academic` already has, and the styling that `zzo` offers.

> What started as a "discussion" issue is now turning into "demanding" extra free work.

I'm not sure where you got that idea. I have no intent of demanding work of anyone on open-source. For my own adjustment/self-improvement, can you point out where you see that?

**Comment by nisrulz** [comment]
@ionlights Well this can be seen in this thread, the maintainer has voiced that he doesn't see the work done in the direction of merging two projects, citing time and effort. At the same time also mentioned that if there is any possibility of doing some work directly on the `academic` theme they would want to be cited for their work in the `academic` theme (be it just license file, its their choice).

Your statements on the other hand have been on the lines of "can you do it?". You have not once suggested a possible solution around how to even hit the problem from the technical side of things. It is pretty much known that there is a lot of work required, yes. But please give something more than an "ask" of doing the work. 

>  However, many of these lack the feature-set that academic provides, especially in terms of ready-to-use components that can be placed across the site.

> Would you making further contributions to hugo-academic with style updates that would be made to zzo?

> So, I'm not insinuating you contribute or anything of the sort. I'm mostly getting a feel for what your "terms" might be, in the case George is interested in expanding academic's support for alternate themes.

Your constant emphasis on pushing for the maintainer to commit to contributing is disturbing here.

What is really bad that someone made a negative statement and you decided to dump it here:
> however, zzo's implementations aren't quite as developed. 

In whatever state it is, it is what it is. It is open sourced, Free as in Freedom, piece of code. Respect that. Be empathetic about other people effort and time spent. Some of us do open source work in our free time after work hours. You don't like something, then don't use it. However please stop spreading negative statements made elsewhere within the open source community. 

For the most part, the maintainer is not entitled to service your feature request. They are the maintainer of this project, you can make a request and they can decline your request. If you don't like it, fork it and build on your own.
