### ISSUE TITLE
Gallery ordering, and captions

### ISSUE THREAD

**Issue by BGnoinski** [zzossig/hugo-theme-zzo#2]
Hello,

Is it possible to specify the order the pictures in a gallery are shown, as well as specify a caption for the picture?

**Comment by zzossig** [comment]
I didn't think about it and I feel that feature should be included to this theme.
And where do you think gallery captions should be located?
In fact, I was working on this part. What about caption text displayed when the mouse hovers over the image?
![gallery caption](https://user-images.githubusercontent.com/52706977/68733236-577d4d00-0619-11ea-944a-4fa45e2001b9.png)

**Comment by BGnoinski** [comment]
I think adding the gallery captions to content/gallery/{GALLERY}/index.md would be a great place, if that's what you meant by located.

Yeah I think hover over on the main gallery page, and when I click on a picture it shows the file name at the bottom right now, maybe replace that with the caption?

![Screenshot from 2019-11-12 20-54-34](https://user-images.githubusercontent.com/7493665/68734376-058fe500-058f-11ea-8d4e-cb0a6e065780.png)

**Comment by zzossig** [comment]
@BGnoinski Can you update the zzo theme and check if the gallery works as expected?

**Comment by fandean** [comment]
![image](https://user-images.githubusercontent.com/25637720/68780169-d487e100-0670-11ea-9c26-fa2ed4b01796.png)

But

![mkcert02](https://user-images.githubusercontent.com/25637720/68782114-c8515300-0673-11ea-8521-543a65ea9aac.gif)
The ability to click through images is missing.Unless you click on the image caption . 
The caption can be displayed over the picture?  Or is not shown here

If you can do it like this, it's best
![mkcert03](https://user-images.githubusercontent.com/25637720/68782301-2120eb80-0674-11ea-9607-6de1456ece51.gif)

**Comment by zzossig** [comment]
@fandean Hm? I already made it like that. Maybe you are missing some style file. Can you check the file under themes/zzo/assets/sass/pages/_gallery.scss and you should find this code
![c](https://user-images.githubusercontent.com/52706977/68786404-10c43d00-0683-11ea-8543-73e0aa4d68ef.png)

**Comment by BGnoinski** [comment]
It looks like the custom captions are working now. 

However on Chrome I am running into the same issue as @fandean 

I am not able to click on a picture to enlarge it, only the caption. 

Also if I have multiple files the caption gets hidden.

![zzotheme](https://user-images.githubusercontent.com/7493665/68822075-c754fd00-0644-11ea-8e38-03a6e7318c15.png)

**Comment by zzossig** [comment]
Oh, I forgot to upload resources file. Please update one more time and all should work

**Comment by BGnoinski** [comment]
@zzossig Thank you very much it is now working.

After my initial pull it still wasn't working, but then I removed the generated `resources` folder from the hugo root directory, it was then re-generated by hugo and all seems good.
