### ISSUE TITLE
Support reveal.js for presentation page

### ISSUE THREAD

**Issue by zzossig** [zzossig/hugo-theme-zzo#20]
[Reveal.js](https://github.com/hakimel/reveal.js/) is awesome. I feel that I must include this feature in this theme.

**Comment by fandean** [comment]
Hi, 怎么说 , when I saw review.js, I remembered that I used it to make slides before, and I also recorded it through the article. When I looked at this article on the website, I found a bug in zzo.

**Comment by zzossig** [comment]
It's working now. Only basic functions work.  If there is something that I missed, feel free to reopen this issue or make a new issue
