### ISSUE TITLE
Featured image in post

### ISSUE THREAD

**Issue by bootyocean18** [zzossig/hugo-theme-zzo#200]
I was hoping that you could implement the feature image inside of the post, either above the title or maybe directly below it? 

We already declare it in the front matter and it's called and used in the various home page layouts. Surely we can pull it in to the post with a fairly simple call, right? 

This isn't a bug, but a feature request! <3 thank you for the amazing theme and the hard work you do on it.

**Comment by szpak** [comment]
Similar idea come to my mind recently, but I wonder wouldn't it be better (more flexible) to just provide a shortcode putting the featured image in the place where used (to do not have to use `img` with `src`)? E.g.

```
# My new blog post

{{< featuredImage >}}

More text
```

**Comment by szpak** [comment]
And btw I wonder which image should be used: `image`, `meta_image` or maybe `featured_image`?

**Comment by zzossig** [comment]
@bootyocean18
Did you mean something like Medium?

![주석 2020-02-24 205338](https://user-images.githubusercontent.com/52706977/75150484-cfdec880-5747-11ea-8153-f9c88943213f.png)

@szpak
But what if we want to set a different image on summary and under the post title.
We already have markdown syntax to do it like this.
```
[featuredImage](images/featuredImage.png)
```

So, why not just use Markdown syntax?

> And btw, I wonder, which image should be used: image, meta_image or maybe featured_image?

`featured_image` is remained for an older version of the theme. I recommend to use `image` instead.
`meta_image` is for link preview for social media

**Comment by szpak** [comment]
@zzossig Yes, I can use `![image](/images/featuredImage.ong)]`, but I need to provide the whole path again - in the header and here (which is problematic on update) and I lose an ability to set width. The shortcode could reuse "image" (or throw error if not). I would probably leverage `img` under-the-hood with all the parameters supported by it. Hmm, maybe image could try to get "src" by default from the markdown file header if not defined explicitly?

> featured_image is remained for an older version of the theme. I recommend to use image instead.
meta_image is for link preview for social media

Currently I use both `image` (for the post list) and `meta_image` (for social headers). Maybe `meta_image` could be set to the same value as `image` if not defined explicitly (to do not have to specify it twice)?

I wonder, if people may want to set only `image` and not `meta_image`? If yes, maybe if `meta_image` defined as an empty string `meta_image: ''` (could be detected in Hugo?), maybe it could prevent that automatic assignment?

**Comment by zzossig** [comment]
Ok, thanks for the detailed explanation!
I'll make `{{< featuredImage >}}` shortcode and make `image` front-matter as a default value of `meta_image`

**Comment by zzossig** [comment]
I made 3 optional parameters in the shortcode
{{< featuredImage alt="featured image" width=50 height=50 >}}
`alt`, `width` `height` are optional

**Comment by bootyocean18** [comment]
This great! thank you.

I also never thought of making the feature image the default for the meta_image but that is a really great idea.

**Comment by zzossig** [comment]
There might be an issue related to the `featuredImage` shortcode #202 
I recommend you to update the theme later on

**Comment by szpak** [comment]
Thanks @zzossig. It works as expected.

I was only surprised that `width` and `height` takes just a number (e.g. `50`) instead of a number and a unit (e.g. `50px`) as a regular `img`. However, if you think it's better, I'm fine with that (once found it out ;-) ).

**Comment by zzossig** [comment]
@szpak Oops, I didn't notice you replied here.
I made it so without much thinking.
But I don't know what's the benefit to accept unit for an image with, height.
So, I think it's fine now.

And the shortcode easily customizable by overriding the theme's shortcode file.
-> copy-paste the theme's shortcode to your root shortcode folder and customize it.
