### ISSUE TITLE
Add comments to pages on website by using Telegram Comments Widget.

### ISSUE THREAD

**Issue by LGTMXD** [zzossig/hugo-theme-zzo#201]
https://comments.app/

nice ui and totally free

**Comment by LGTMXD** [comment]
feature request 2：
open link in new tab

**Comment by zzossig** [comment]
Ok, I'll add the telegram comments widget. It looks so nice.
But since the widget is not supported the dark mode theme, I'll do some styling for this.

And I don't understand your `feature request2`.
What did you mean?

**Comment by LGTMXD** [comment]
> And I don't understand your `feature request2`.
> What did you mean?



target="_blank"

if there is an external link on page，after click it，open in a new tab by default.

**Comment by szpak** [comment]
@LGTMXD If you are talking about the markdown link [this](https://discourse.gohugo.io/t/how-to-open-link-in-new-tab-with-hugos-new-goldmark-markdown-renderer-in-v0-62-0/22540?u=szpak) might be useful for you.

**Comment by zzossig** [comment]
I added the telegram comment.
You can do like this

`params.toml`
```toml
...
[telegram]
  enable = false
  siteId = ""
  dataLimit = 5
```

I give up to adding custom color theme because of some reasons.
