### ISSUE TITLE
Setting featureImage adds a thumbnail to the post link in home page

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#202]
I tried setting the featureImage shortcode. This is what happened to post link on homepage

![Screenshot from 2020-02-24 22-33-10](https://user-images.githubusercontent.com/2096087/75193010-b0e73300-5755-11ea-97a0-5f3451b5abec.png)

Although this is not entirely wrong, what could be done here is that the thumbnail on home page should fill the square area with `cover` state in css.

Also setting `meta_image` inside post does nothing anymore.

**Comment by zzossig** [comment]
> Also setting meta_image inside post does nothing anymore.

Yes, thanks! It's a bug. It will be fixed in the next commit.

> the thumbnail on home page should fill the square area with cover state in css.

Did you mean something like this? It can be done with extra params.

![주석 2020-02-25 095657](https://user-images.githubusercontent.com/52706977/75204819-51207480-57b5-11ea-9d4e-5c1d25f86c28.png)

Unfortunately, this is the expected behavior. 
Since the image could have more width than height or more height than width, I think it's difficult to manage the image uniformly.
And the summary(description) could be a long text. In that case, we should set max height param every single post for the summary image which is not the handy way

**Comment by nisrulz** [comment]
Agreed. I think if we can provide a separate image for meta_image it would be displayed in the home page right? while keeping the featured image only for the post page.

**Comment by szpak** [comment]
> Also setting meta_image inside post does nothing anymore.

In my case, it does. `og:image` and `og:image:url` is set to `meta_image` if defined (or to `image` if not). Which is the expected behavior for me - I don't need to set the value twice and I can set different featured image for social media if needed.

**Comment by zzossig** [comment]
@szpak yes exactly.
So `image` front matter is used as the summary image, `{{< featuredImage >}}` shortcode, and meta image(if not set `meta_image` front matter)

`meta_image`(or `image`) is used for link preview like this
![IMG-0051-min](https://user-images.githubusercontent.com/52706977/75245149-80180400-5810-11ea-8402-b7b9e553ebe2.png)

**Comment by szpak** [comment]
> Agreed. I think if we can provide a separate image for meta_image it would be displayed in the home page right? while keeping the featured image only for the post page.

As I initially proposed that revolution I will join in here to try to sort it out :-/. @nisrulz So you would like to have:
 - only `image` is defined - use it everywhere (post (`featuredImage`), post list and meta)
 - `image` and `meta_image` - use `image` for post (`featuredImage`) and post list, use `meta_image` for meta (if you need to use other image in your post just don't use `featuredImage` shortcode, but regular `img` with some other image)

Would it be sufficient for you?

**Comment by nisrulz** [comment]
Ok. Maybe we can add this to the docs.

- meta_image(or image) is used for link preview
- {{< featuredImage >}} shortcode

What maybe I am trying to figure out is that
- The one on the homepage is usually a square kind of image. Now if the `image` frontmatter is used for the same then the image that is set for `featuredImage` shows up there and then its is not square i.e it shows up as I posted initially, really small and not covering the complete height.

The idea is to be able to specify another image for the summary part. So it looks like this:

<img width="703" alt="Screen Shot 2020-02-25 at 1 02 58 PM" src="https://user-images.githubusercontent.com/2096087/75246002-30fdaf00-57cf-11ea-87d1-cf15696b31d5.png">

but filling up the whole area, as much as height it has + set width + cover state, so it fills the whole square area. 

Does it make sense?

**Comment by zzossig** [comment]
Yes, it makes sense.
One thing I worry about is that there are so many options out there and people might be confused and overwhelmed by  all the parameters

**Comment by nisrulz** [comment]
I can always help in documenting things. One way to keep track is to open a new issue which you and others can pick up and help you in updating the docs. 

Let me know, if that can work out 😄

**Comment by zzossig** [comment]
> pick up and help you in updating the docs.

Yes, it could be helpful. you can make an issue here https://github.com/zzossig/zzoDocs
But I think I can do some documentation job in the middle of the march.

And I added `summary_image` front matter
```
---
title: ""
...
summary_image: 
  src: images/whoami/avatar.jpg
  maxWidth: 200
  objectFit: cover
  hwm: true # Hide When Mobile

---
```

Tell me if It does not work as expected.

**Comment by nisrulz** [comment]
It kind of works :sweat_smile: 

I had to manually set the height to 7em.

![Screenshot from 2020-02-25 20-37-06](https://user-images.githubusercontent.com/2096087/75280944-a63ca480-580e-11ea-9989-2ffe2c63128e.png)

**Comment by zzossig** [comment]
Oops, Sorry. It was not working😫
I added `height` option and make the `maxWidth`, `height` accept full text(include unit) like `50px`(not 50)

```yaml
title: 
...
summary_image: 
  src: images/whoami/avatar.jpg
  maxWidth: 220px
  height: 150px
  objectFit: cover
  hwm: true
```

Can you test it again?

**Comment by nisrulz** [comment]
I will give it a try and update here. Thank you for making the change 😄

**Comment by nisrulz** [comment]
Just tested. It works pretty well. However on mobile where it is supposed to be hidden, there is extra padding now.

Notice the left padding on 2nd item compared to 1st item.
![Screenshot from 2020-02-26 19-54-41](https://user-images.githubusercontent.com/2096087/75377357-e87aea00-58d1-11ea-8070-b4592c54bb95.png)

**Comment by zzossig** [comment]
Ok, Thanks! I fixed 2 things
1. Now, you don't need to specify `image` to use `summary_image`
2. The extra padding deleted!

**Comment by nisrulz** [comment]
This is fixed, so closing.
