### ISSUE TITLE
side title when full screen on chrome dont be centred

### ISSUE THREAD

**Issue by LGTMXD** [zzossig/hugo-theme-zzo#204]
![image](https://user-images.githubusercontent.com/30213081/75230061-1c7cdf00-57ee-11ea-8cf1-621beaf734c7.png)

![image](https://user-images.githubusercontent.com/30213081/75230325-65cd2e80-57ee-11ea-9acc-149ef0bd4557.png)

**Comment by zzossig** [comment]
Thanks for the issue!
It's fixed now!
