### ISSUE TITLE
Image placeholder could have the same size as target image

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#205]
I don't know if it could be enhanced, but currently in the blog post where `{<< img src="" width="" >>}` is used (also if `height` is precised) the placeholder displayed when a page is rendered is much bigger (higher) than the target image. Those hundreds of millisecond (depending on the network connection) when the image is being loaded doesn't look (text is moved back when the image is loaded).

Maybe it could be tweaked with some CSS magic?

**Comment by szpak** [comment]
It seems that the placeholder is also displayed for a moment if my browser has that image cached (there is request for it which returns 304). Could be the image displayed from cache right away in that case?

**Comment by zzossig** [comment]
> the placeholder displayed when a page is rendered

Did you mean this placeholder image?
![주석 2020-02-27 100020](https://user-images.githubusercontent.com/52706977/75402379-f8351580-5947-11ea-9722-e3abf7852fee.png)

I made some changes. But the placeholder image is square, and most of the image is rectangular so I think we can't avoid the mismatch of the height.

Regarding cache, I added option `lazy`

```
{{< img src="" lazy="false">}}
```

Since, I use the lazysizes for lazy loading images, the library not support serving cached image. So, if we disable lazy image load, the rest of a job for serving cached image is the responsibility of the web browser

**Comment by szpak** [comment]
> I made some changes. But the placeholder image is square, and most of the image is rectangular so I think we can't avoid the mismatch of the height.

Thanks for clarification. The rectangular image was the issue. However, having that knowledge I am able to start defining `height` instead `width` for my in-post images and now it is almost invisible (the most destructive effect was moving the text under the image back and forth).

Regarding laziness, it in fact prevents a place holder to be displayed (although, with the above finding it is less important). However, for `{{< img src="" >}}` laziness seems to be disabled by default. From your comment I understand it has to be disabled on demand. Have you done it intently?

**Comment by zzossig** [comment]
Hmm, I'll test it more after I get home.
It should be disabled on demand.
Something went wrong on the `img` shortcode

**Comment by szpak** [comment]
There might also some something on my side, but I don't see a placeholder with the clear `img` shortcode. Firefox 73.

**Comment by zzossig** [comment]
Can you check again?

**Comment by szpak** [comment]
Currently `img` by default doesn't show a placeholder. However, if I add `lazy="false"` or `lazy="true"` (it doesn't matter) it starts.

**Comment by zzossig** [comment]
I misunderstood 😅
It's fixed now

**Comment by szpak** [comment]
:+1:
