### ISSUE TITLE
[Regression] Submenu items not displayed any longr on mobile

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#206]
In the past, the submenu items were displayed in the menu on mobile. However, there are not any longer - just the main elements. It happens in the range of commits container this [one](https://github.com/zzossig/hugo-theme-zzo/commit/71e457e19efde61b5427bec7ec6c75f8951111fb).

**Comment by zzossig** [comment]
Yes, it is. It's on purpose.
Do you want the submenu also displayed on the menu?
If so, how do you think the UI should look like

**Comment by szpak** [comment]
Currently it is not possible to read/reach the submenu-linked pages from mobile (unless linked somewhere else). Having <10 menu elements in total it was perfectly fine to have them displayed in the way it had been before, so maybe it could be restored.

I don't know if there was a request to disable it, and if yes, maybe there could be a configuration parameter to turn it off on mobile? However, IMHO it should be displayed by default.

**Comment by zzossig** [comment]
Ok, I don't want more params so I'll make it as default.
And restore the UI

**Comment by zzossig** [comment]
I included child menu when mobile

**Comment by szpak** [comment]
Tested, thanks.
