### ISSUE TITLE
Display post content even with JavaScript disabled?

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#207]
I've noticed that with JavaScript disabled the post content is not displayed at all (as opposed to the home page where the post lists is displayed). I wonder, if/how it impacts SEO - "Google" doesn't see the content at all?

Maybe it would be possible to display the post content in any form (no images, formatting, etc) with the clear message at the top that JavaScript is required to see the page?

**Comment by zzossig** [comment]
Yes, we can.
But I need some of your opinions
https://github.com/zzossig/hugo-theme-zzo/issues/152#issuecomment-584099582

**Comment by szpak** [comment]
For me, it would be better to display a clearly visible warning informing user that it is recommenced to have JavaScript enabled, e.g. between "Hugo Zzo Theme -> Posts ->   Syntax highlighting" and the post title
![image](https://user-images.githubusercontent.com/148013/75433100-b740ff00-594f-11ea-8627-c92517d643c9.png)

It should be clearly visible (yellow/orange background and some not-black font?), but not offending.

Maybe that div/span could be rendered by default and hidden with the JavaScript (if enabled in a browser)?

Regarding context I don't have any preferences. Some possible messages:
This page (content?) looks best with JavaScript enabled
JavaScript is recommended to fully enjoy this page (content?)
JavaScript is recommended to view this page (content?)
Visual features of this page (content?) are limited with JavaScript disabled

**Comment by zzossig** [comment]
I confused which one is better since I never disable javascript.
So I made new param `hideSingleContentsWhenJSDisabled`

`params.toml`
```
hideSingleContentsWhenJSDisabled = false
```

**Comment by szpak** [comment]
Works great, thanks!
