### ISSUE TITLE
add RTL support for mobile nav menu

### ISSUE THREAD

**Issue by Gictorbit** [zzossig/hugo-theme-zzo#208]
Hi, since your latest commit about mobile nav menu [c4ab5ff
](https://github.com/zzossig/hugo-theme-zzo/commit/c4ab5ffeb0fed0ddecfe0eaa8fbf235a0419bcac) RTL support is missed could you add RTL support Please?

**Comment by zzossig** [comment]
The menu was center-aligned before.
So, did you mean align menu text to the right when mobile RTL mode?

**Comment by zzossig** [comment]
Can you check again?

**Comment by Gictorbit** [comment]
> The menu was center-aligned before.
> So, did you mean align menu text to the right when mobile RTL mode?

Yes I meant align

> Can you check again?

I checked It. great, thank you :1st_place_medal: 
one other enhancement for the theme could be a config parameter for the mobile nav menu center align.
because a language could be RTL or LTR and depends on these modes, the mobile menu align is left or right but what if someone wants the mobile menu with the center align? like before?

**Comment by zzossig** [comment]
> but what if someone wants the mobile menu with the center align? like before?

Since I don't know how to display child menu when centered align mobile menu, Do you have any suggestions regarding UI? How can I display a child menu when centered align?

**Comment by Gictorbit** [comment]
Hmm
Since my blog hasn't any child menu now, I didn't pay attention to it. actually this UI for the menu is nice, we keep going with it
Thank you for your response. sorry if I wasted your time
