### ISSUE TITLE
I want social svg file

### ISSUE THREAD

**Issue by Jason-cqtan** [zzossig/hugo-theme-zzo#21]
steam and telegram,thx

**Comment by zzossig** [comment]
![icons8-steam-30](https://user-images.githubusercontent.com/52706977/69962106-a3544f80-1550-11ea-8aa4-cc81740abe05.png)
I couldn't file a circular one. I'll upload this square one. But in the future, I'll upload a circular one.

**Comment by Jason-cqtan** [comment]
ok,and telegram,dont forget

**Comment by zzossig** [comment]
Yes, I'll upload maybe 4 hours later before I go to sleep😁

**Comment by Jason-cqtan** [comment]
very good,love u like real friend🙃
