### ISSUE TITLE
linenos=false in syntax highlighting breaks post formatting

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#210]
To reproduce just add `{linenos=false}` in `syntax-highlight.md` for any code snippet, e.g.
```
``` makefile {linenos=false}
CC=gcc
...
```
Then the header is improperly moved to the top:
![image](https://user-images.githubusercontent.com/148013/75539742-0e5fd600-5a1b-11ea-85d0-417dd1cac057.png)

(if fixed, you could just leave one that example in `syntax-highlight.md` for a reference)

**Comment by zzossig** [comment]
It's fixed now

**Comment by szpak** [comment]
Thanks.
