### ISSUE TITLE
Next/Prev post formatting glitch for long titles

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#212]
A minor, however I've noticed that for long post names the right title is somehow misplaced:
![image](https://user-images.githubusercontent.com/148013/75591921-50bbfe00-5a81-11ea-8b16-100492ad5f35.png)

For slightly shorter titles - where they fit one line, it is ok:
![image](https://user-images.githubusercontent.com/148013/75591912-4b5eb380-5a81-11ea-9032-9d51b17227d3.png)

**Comment by zzossig** [comment]
It's fixed now
