### ISSUE TITLE
Search is broken?

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#214]
Not sure if it is just me, but I just tried the search and apparently it is broken.

#### Chrome: 
![Screenshot from 2020-03-01 03-05-44](https://user-images.githubusercontent.com/2096087/75618152-2e51df80-5b6a-11ea-9a01-2d7fa3f9ead6.png)

![Screenshot from 2020-03-01 03-10-37](https://user-images.githubusercontent.com/2096087/75618158-3c9ffb80-5b6a-11ea-89d7-12a7be2805ab.png)

#### Firefox: 
![Screenshot from 2020-03-01 03-13-49](https://user-images.githubusercontent.com/2096087/75618183-cf409a80-5b6a-11ea-9588-fbf3f7e541ea.png)

I tried fixing it but couldn't figure out. Maybe some one can help here? 

Also, not sure if this error is related to this or causing this problem?
```
Access to XMLHttpRequest at 'https://crushingcode.github.io/index.json' from origin 'https://crushingcode.nisrulz.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
(index):582 GET https://crushingcode.github.io/index.json net::ERR_FAILED
```

**Comment by nisrulz** [comment]
Should mention, the search works in development i.e via localhost.

**Comment by Asjas** [comment]
Search isn't broken - especially not if it works in development.

Your issue is that you are hosting on Github Pages and you are using a Custom Domain linked to it. It's trying to access a file on the Github domain from your Custom domain and that won't be allowed by the browser - it's seen as cross-origin requests and those are blocked by default. I don't personally use Github Pages but are you sure everything for the domain is configured on Github?

**Comment by nisrulz** [comment]
Yes everything is configured properly. There wasn't any issue earlier, but there is now.

Just to add to this, the search worked before when it got live. I tested all functionality before moving to this theme.

**Comment by zzossig** [comment]
Hello,
I'm busy recently working in a company. 
I'll look into it after I got home

**Comment by nisrulz** [comment]
No problem. Nothing is urgent. Opened up the issue for reference. 😺

**Comment by zzossig** [comment]
I found that Git Pages designed to redirect `username/github.io` to `custom-domain.com` so this happened.
Can you change the baseURL to `https://crushingcode.github.io` in the `config.toml` file and check again?

![주석 2020-03-02 214908](https://user-images.githubusercontent.com/52706977/75677830-aa196c80-5ccf-11ea-8e9e-1a0a75259721.png)

**Comment by nisrulz** [comment]
Will check in a few hours when I am back. I think that could be it 🤔 

However it used to work before without any change 😅 

Will try it anyways!

**Comment by nisrulz** [comment]
>  baseURL to https://crushingcode.github.io

This was set like that.

However I set:

`baseURL = "https://crushingcode.nisrulz.com/"`

and published it. Now search works.

Closing as resolved. :smile:

**Comment by perymerdeka** [comment]
im tried search is not work im hosted in netlify im i change the BaseURL to 
`baseURL = 'picode.netlify.app'`
a search cannot work

**Comment by gr33nm0nk2802** [comment]
![image](https://user-images.githubusercontent.com/55975790/120433379-c6a3c900-c398-11eb-938f-780410d4925a.png)

The search seemes to be broken on my localhost as well. Not totally sure what may be the reason. 

Also getting this url http://busuanzi.ibruce.info/busuanzi?jsonpCallback=BusuanziCallback_558727397759 gives some sort of BAD Request error when tried to access from the browser
