### ISSUE TITLE
Caption attribute doesn't work in featuredImage shortcode.

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#216]
Likewise the `position` one too.

**Comment by zzossig** [comment]
The `featuredImage` shortcode not intended to use `caption`, `position`.
Use `img` shortcode instead.
The `featuredImage` shortcode used for limited use-case, and most of the time, it's not needed because we have `img` shortcode.

**Comment by nisrulz** [comment]
Makes sense. I actually prefer the `img` shortcode.

Closing this.
Thank you for the explaination.
