### ISSUE TITLE
Meta tag keywords support for SEO, RSS feeds seems not working

### ISSUE THREAD

**Issue by Jason-cqtan** [zzossig/hugo-theme-zzo#22]
Can you add friend chain function.thx 思密达

**Comment by zzossig** [comment]
What is the friend chain? I've never heard about that

**Comment by zzossig** [comment]
![z](https://user-images.githubusercontent.com/52706977/70052458-aade2c00-1616-11ea-94dd-7ffc22252afb.png)
Did you mean something like this one?

**Comment by Jason-cqtan** [comment]
是的是的，还有我发现头部没有keywords，不利于seo

**Comment by zzossig** [comment]
![bsd](https://user-images.githubusercontent.com/52706977/70053135-22f92180-1618-11ea-900f-eb557a347938.png)
You are a good gamer

**Comment by Jason-cqtan** [comment]
about keywords,in themes/zzo/layouts/partials/head/meta.html put like this
```
<meta name="keywords" content="{{if .IsHome}}{{ $.Site.Params.keywords }}{{else}}{{.Keywords}}{{end}}">
```
and  article head add like this
```
keywords:
- hugo
- zzo
- zzossig 
- something
```
but will show 
```html
<meta name="keywords" content="[hugo zzo 网zzossig something]">
```
u can Optimization.：）

**Comment by zzossig** [comment]
Ah ok~

**Comment by Jason-cqtan** [comment]
oh，collect more but:),now play little

**Comment by zzossig** [comment]
I just committed the changes. Now you are good to go

**Comment by Jason-cqtan** [comment]
ok,i prefer use
```
<meta name="keywords" content="{{if .IsHome}}{{ $.Site.Params.keywords}}{{else}}{{range .Keywords}}{{.}},{{end}}{{end}}">
```
by the way,i found another bug.in themes/zzo/layouts/partials/sidebar/site-bio.html 38 line
change to 
```
  {{ if .Site.Params.location }}
```

**Comment by Jason-cqtan** [comment]
and themes/zzo/layouts/partials/footer/links-feed.html seems does't work well

**Comment by fandean** [comment]
嗨，兄die

**Comment by zzossig** [comment]
@Jason-cqtan thank you for the bug report! I’ll fix it soon

**Comment by zzossig** [comment]
It's fixed now!

**Comment by Jason-cqtan** [comment]
very nice！
