### ISSUE TITLE
[Question][Publication page] how does cite button work?

### ISSUE THREAD

**Issue by sim590** [zzossig/hugo-theme-zzo#220]
On the official [documentation page](https://zzodocs.netlify.com/docs/pages/publication/), there is no mention of the cite button and how to make it work. When one clicks on it, a message appears saying simply "cite.bib not found" which is not sufficiently self-explanatory.

**Comment by zzossig** [comment]
What do you mean by ‘cite button’?
Can you explain more detail?
It was a month ago that I made the publication page. I forgot much of things.
Can you provide me a screenshot?
What is the expected behavior?

**Comment by sim590** [comment]
Here is the screenshot of the button:

![cite](https://user-images.githubusercontent.com/4147254/75929364-6e50e500-5e3e-11ea-89f3-d0d7c559c4bc.png)

It is a button appearing next to the URL button when browsing a publication entry. I guess that it is supposed to provide a `cite.bib` file for the associated publication. That is what I was expecting, but otherwise, I'm not sure what it does.

**Comment by zzossig** [comment]
Ok, thanks! Now I understand.
It is expecting the .bib file at the same position of the md file
Do you have your .bib file?

**Comment by sim590** [comment]
Well, I'm a bit puzzled. I put the file with the same name and the extension ".bib", but the displayed content is the same.

![fichiers](https://user-images.githubusercontent.com/4147254/75931964-419fcc00-5e44-11ea-8b43-9d6008fbbd3a.png)

Does the file need be named `cite.bib`? It doesn't work in that case either.

**Comment by zzossig** [comment]
I’ll check after I arrived office.
The file name should be cite.bib

**Comment by zzossig** [comment]
How did you make the publication page?
Did you use `zzo-bibtex-parser` library?

![주석 2020-03-05 091341](https://user-images.githubusercontent.com/52706977/75935095-a9e0c300-5ec1-11ea-8ce6-fefe4dbd4356.png)

You may need to make the folder structure like `content/publication/article/fully-distributed.../cite.bib`

**Comment by sim590** [comment]
> How did you make the publication page?
Did you use zzo-bibtex-parser library?

I did follow the instructions for the manual approach on [the page that I linked before][page].

> You may need to make the folder structure like content/publication/article/fully-distributed.../cite.bib

Now I have paths

```
content/fr/publication/article/fully-distributed-indexing-over-a-distributed-hash-table/cite.bib
content/fr/publication/article/fully-distributed-indexing-over-a-distributed-hash-table/index.bib
```

I did name `index.md` as `_index.md` before because I thought to be consistent with other files in the structure, but I think that it doesn't work accordingly if you don't use `index.md` here, so I went back to `index.md`. The file `cile.bib` is right next to the other file. I don't get the content inside the cite box (after pressing the cite button). :confused: 

[page]: https://zzodocs.netlify.com/docs/pages/publication/

**Comment by zzossig** [comment]
Sorry for the trouble.
I'll update the example site so that you can get an idea of how to make it work.

**Comment by sim590** [comment]
> I'll update the example site so that you can get an idea of how to make it work.

Great. I guess that instructions changed then! Thank you.

> Sorry for the trouble.

By no means have I been troubled. We are very fortunate that you work very quickly.

**Comment by zzossig** [comment]
You can get an idea of how to make some publication pages.
https://github.com/zzossig/hugo-theme-zzo/tree/master/exampleSite/content/en/publication

**Comment by sim590** [comment]
@zzossig: I'm sorry to insist again if I'm doing something really wrong, but I don't see it. Here, look at my code:

https://github.com/sim590/sim590_github_io/tree/master/content/fr/publication/article

The result is there:

http://sim590.github.io/fr/publication/article/fully-distributed-indexing-over-a-distributed-hash-table/

**Comment by zzossig** [comment]
I think we can close this issue now
https://github.com/sim590/sim590_github_io/pull/1
