### ISSUE TITLE
markdown formatting removed from _index.md pages

### ISSUE THREAD

**Issue by rgr19** [zzossig/hugo-theme-zzo#223]
Hi!
I would like to render markdown in _index.md as in index.md. Now all formatting seems to be removed in _index.md. Could You give any advice how to set it up?

**Comment by zzossig** [comment]
Can you update the theme and check again?

**Comment by rgr19** [comment]
Hi! 

I mean for `_index.md` like

```md
---
title: Test Index _index.md
---

Ala ma kota:

- white
- black
```

The result will be

![image](https://user-images.githubusercontent.com/54042766/76256637-91b9cc80-6250-11ea-8009-5d6abef20892.png)

And similar stuff.

**Comment by zzossig** [comment]
Did you update the theme?

**Comment by zzossig** [comment]
It works fine for me.
Update the theme and check again
![주석 2020-03-10 090208](https://user-images.githubusercontent.com/52706977/76267360-d758b280-62ad-11ea-874b-ecd502ff1053.png)

**Comment by rgr19** [comment]
Ok! So I have copied Your blog to have proper settings, then cloned zzo theme to there and did 

![image](https://user-images.githubusercontent.com/54042766/76298137-4c7db500-62b9-11ea-8b26-7254bb5fee24.png)

but result is as

![image](https://user-images.githubusercontent.com/54042766/76298179-5c959480-62b9-11ea-9028-3ba5840b0c19.png)

It somehow still broken.

I'm using hugo 0.60.1, is it ok?

**Comment by zzossig** [comment]
> I'm using hugo 0.60.1, is it ok?

Yes, it is ok.

> It somehow still broken.

No, it's not broken.
Can you try this?
```markdown
- blue
- black
    - re ## 4 spaces
```
or
```markdown
- blue
- black
        - re ## 8 spaces
```
