### ISSUE TITLE
how to include sections-tree in index pages?

### ISSUE THREAD

**Issue by rgr19** [zzossig/hugo-theme-zzo#224]
Hi! I would like to use this `partials/widgets/sections-tree.html` 

```html
{{ define "sections-nav" }}
<ul>
    {{ range sort .Pages "value" "desc" }}

    {{if gt (len .LinkTitle) 0}}
        <li><a href="{{ .Permalink}}"> {{ .LinkTitle }} </a></li>
    {{else if gt (len .Title) 0}}
        <li><a href="{{ .Permalink}}"> {{ .Title }} </a></li>
    {{end}}

    {{ end }}
</ul>
{{ end }}

<div class='container sep-after'></div>

{{ define "current-section_pages" }}
<ul>
    {{ range sort .Pages "value" "desc" }}

    {{if gt (len .LinkTitle) 0}}
        <li><a href="{{ .Permalink}}"> {{ .LinkTitle }} </a></li>
    {{else if gt (len .Title) 0}}
        <li><a href="{{ .Permalink}}"> {{ .Title }} </a></li>
    {{end}}

    {{ end }}
</ul>
{{ end }}

<div>
    <ul>
        {{ if ne .IsHome true }}
        <h4>Articles:</h4>
        {{ template "sections-nav" . }}
        {{end}}
        <hr>
        {{ if gt (len .Sections) 0}}
        <h4>Subcategories</h4>
        {{ template "sections-tree-nav" . }}
        {{end}}
    </ul>
</div>
```

but I could not find good place to inject it so that it would be rendered at each _index page. Could You please suggest where to include it?

**Comment by zzossig** [comment]
First of all, you need to explain what is `partials/widgets/sections-tree.html` is.
Where it is coming from?
I didn't make it.

**Comment by rgr19** [comment]
Hi! I have made it and wish to use it with that theme as it helps to deal with nested content that is sometimes deeper than wider.

So I would like to create some layout `my_layout.html` with that code included 

```html
<div>
    <ul>
        {{ if ne .IsHome true }}
        <h4>Articles:</h4>
        {{ template "sections-nav" . }}
        {{end}}
        <hr>
        {{ if gt (len .Sections) 0}}
        <h4>Subcategories</h4>
        {{ template "sections-tree-nav" . }}
        {{end}}
    </ul>
</div>
```

and  use it like 

```md
---
title: Test Index _index.md
layout: my_layout
---
```
But because there is no `md` formatting in `_index.md` at this theme, it wont work. Is there any setting I could switch off to turn on standard formatting? I think the problem is the same as with [issue](https://github.com/zzossig/hugo-theme-zzo/issues/223)

**Comment by zzossig** [comment]
No, this theme doesn’t support layout front matter
