### ISSUE TITLE
Longer blog name breaks mobile in post list

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#225]
Settings longer `xx.title` in `languages.toml` causes incorrect page width on `/posts/`. It seems that the breadcrumb is not properly limited according to the window size (especially visible on mobile - swipe left):
https://blog.solidsoft.pl/posts/

The problem doesn't occur on the single post view, where the breadcrumb behaves correctly:
https://blog.solidsoft.pl/2020/03/02/enable-java-14-preview-features-in-gradle-maven-and-idea/

Btw, it just a version, WITHOUT changes from from #221.

**Comment by zzossig** [comment]
> incorrect page width

What do you mean the `incorrect page width`?
I checked the blog but the width seems to look normal
![주석 2020-03-09 182840](https://user-images.githubusercontent.com/52706977/76199826-ec90fb00-6233-11ea-88e5-76170c6bc813.png)

**Comment by szpak** [comment]
Yes, the whitespace, but not only in the screenshot. In the Firefox mobile I can just swipe right to see it. And without that not the whole text is visible.

![image](https://user-images.githubusercontent.com/148013/76200467-f98cfa80-61f1-11ea-8d8d-29691fffc6cc.png)

![image](https://user-images.githubusercontent.com/148013/76200484-01e53580-61f2-11ea-96f9-94f81519dee5.png)


With Firefox desktop (with the narrow window) I cannot swipe, but the problem with text out-of-the-screen it present.

**Comment by szpak** [comment]
The same breadcrumb (which is missing in your screenshots for some reason), in the single post view behaves correctly:
![image](https://user-images.githubusercontent.com/148013/76200708-61dbdc00-61f2-11ea-80bb-0acd2450a365.png)

**Comment by zzossig** [comment]
Yes, when I made `display: none`, it works as expected.
I'll update soon

**Comment by zzossig** [comment]
Can you check again?
I just truncated the long site name to `150px`

**Comment by szpak** [comment]
Not really :-/

On desktop:
![image](https://user-images.githubusercontent.com/148013/76203498-06f8b380-61f7-11ea-8d07-86b860f3da41.png)

Maybe I will just shorten the name of my blog ;-)

**Comment by zzossig** [comment]
I just come across that it would be good if we made it scrollable

**Comment by zzossig** [comment]
> Maybe I will just shorten the name of my blog ;-)

Yes, I think it is the best way for now.
I tried some things but the CSS not working uniformly over cross-browser.
I'm closing this issue as I won't fix it.
