### ISSUE TITLE
The tags in the post single page do not show Chinese characters

### ISSUE THREAD

**Issue by heyunan** [zzossig/hugo-theme-zzo#227]
I love this theme and I want to use it for my blogs. But I met a problem.
If I set the tags in Chinese characters, the post page only gives me the tag icon (🏷️) without any content. But if it is English, it works well. Could you tell me how to solve this problem?

**Comment by zzossig** [comment]
Can you show me your markdown file so that I can reproduce it?
There is nothing I can do without your seeing your code.

**Comment by heyunan** [comment]
Here is the front matter

```
---
title: "This is a test page"
date: 2020-01-23 10:39:41 +0900
description: 
draft: false
hideToc: false
enableToc: true
enableTocContent: true
authorEmoji: 👺
tags: 
- 测试
- test
---
```
And it renders the page like
![Picture1](https://user-images.githubusercontent.com/23273563/76377234-af408080-638d-11ea-917f-f321132d109e.png)
Only the tag "test" there but no "测试"

**Comment by zzossig** [comment]
I have confirmed that this is a bug.
It will be fixed soon

**Comment by zzossig** [comment]
I fixed the bug.
The latest version needs minimum Hugo 0.65.0.
So update the zzo theme first and then update Hugo version(if you are behind 0.65.0)
