### ISSUE TITLE
hmm,Can you add a website visit statistics function

### ISSUE THREAD

**Issue by Jason-cqtan** [zzossig/hugo-theme-zzo#23]
like this
<img width="321" alt="截屏2019-12-0420 40 09" src="https://user-images.githubusercontent.com/17697213/70143342-4682a180-16d6-11ea-9619-4df970868461.png">

use this [lib](http://busuanzi.ibruce.info/)

and in article footer add reward func
<img width="735" alt="截屏2019-12-0420 41 59" src="https://user-images.githubusercontent.com/17697213/70143492-bb55db80-16d6-11ea-8239-a6b035f06218.png">

**Comment by zzossig** [comment]
Ok. I'll try it. I've heard about the Busuanzi before but I have to search more about it.

**Comment by zzossig** [comment]
Hey~ check out the readme.md! I added your requests

**Comment by Jason-cqtan** [comment]
Awesome, but this  donation image is too small😅

**Comment by zzossig** [comment]
you can add your image with your proper size

**Comment by Jason-cqtan** [comment]
hmm,use custom_css

**Comment by zzossig** [comment]
Actually, I don’t know much about the QR code donation. You have your own QR code image?

**Comment by Jason-cqtan** [comment]
yea,i hava wechat and alipay

**Comment by Jason-cqtan** [comment]
but i hate css🤯

**Comment by zzossig** [comment]
Can you give it to my email? I wanna check in local environment. How it is look like?

**Comment by zzossig** [comment]
I don’t recommend you to use custom css

**Comment by Jason-cqtan** [comment]
<img width="356" alt="截屏2019-12-0519 54 12" src="https://user-images.githubusercontent.com/17697213/70233757-274d4800-179a-11ea-9d0f-8b73ede8394e.png">

**Comment by Jason-cqtan** [comment]
i don't know ur email addr

**Comment by zzossig** [comment]
Haha, it's so small. How many pixels do you want to increase the image size?

**Comment by Jason-cqtan** [comment]
<img width="1076" alt="截屏2019-12-0520 07 07" src="https://user-images.githubusercontent.com/17697213/70234171-046f6380-179b-11ea-9599-c45b668de850.png">

**Comment by zzossig** [comment]
Ah ok, that much

**Comment by zzossig** [comment]
@Jason-cqtan I adjusted the image size! Check it out

**Comment by Jason-cqtan** [comment]
thx,pretty well
