### ISSUE TITLE
About-like pages with nested structure

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#230]
It's more Hugo related stuff, but maybe you could advice me how to achieve it in the simpler way with Hugo and ZZO.

Currently I have the `content/training.md` page (with a type `about`) which is accessible as `/training/`. It is fine. However, ultimately, I would like to have `/training/` as the base page for training and some subpages with specific programs: `/training/program1/`, `/training/program2/`. Therefore, it would be best to put there into `content/training/program1.md`, `content/training/program2.md`, ... with `content/training/index.md` serving as `/training/`. The page type could be `about`, but it could be also the new one `training` with the partial taken after `about`. However, currently, other elements, expect for `index.md`, are not visible (not generated at all).

What would be the easiest to bring it to life? What else would be needed to configure to play it nicely with the ZZO theme?

**Comment by rgr19** [comment]
thats due to difference of _index.md and index.md, so do training/_index.md, training/program1.md

**Comment by zzossig** [comment]
Maybe, I do not fully understand what you mean.
The about page is designed to use single page.
![주석 2020-03-13 091819](https://user-images.githubusercontent.com/52706977/76578319-99f16080-650b-11ea-9a69-40402f9ddadb.png)

If you want to add more files using `type=about`, you need to add  `list.html` file in `layouts/about/list.html`
But I didn't make `list.html` file so that happened.
Do you have a specific UI design(about page listing) in mind?

**Comment by szpak** [comment]
> thats due to difference of _index.md and index.md, so do training/_index.md, training/program1.md

Thanks @rgr19. It worked. It started to use default `list.html` which would be nice to list all of programs, etc (in the similar way to talks). However, in my case, I would like to just simplify where to put those files and have nice links. However, it give me a conception, extended by zzossig...

> If you want to add more files using type=about, you need to add list.html file in layouts/about/list.html

Yes, having a dedicated `list.html` for about pages allows me to decide what to display on the main training page. Having the same content of `list.html` as `about.html` is sufficient for me. I still have nice "about page", sublink and I can manually (with `ref`) link to those subdocuments from the main page. Currently, I don't see a need to create a dedicated page type `training` for that. Thanks.
