### ISSUE TITLE
Tabs-like shortcode with automatic switch (carousel)

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#232]
I like the `tabs` shortcode that you added some time ago. I wonder if it would be possible to make it switch automatically? Or, even better, in general to have an ability to create a [carousel](https://getbootstrap.com/docs/4.0/components/carousel/)-like shortcode/component with custom content.

My precise use case is display testimonials regarding my training (e.g. 3 markdown formatted entries changed automatically placed somewhere on the training subpage), but a generic component could be used also in one other places by different people.

**Comment by zzossig** [comment]
Ok, I'll try

**Comment by zzossig** [comment]
@szpak Can you check if this shortcode meet your needs?
It is using `swiperjs` https://swiperjs.com/

```markdown
{{< swiper loop=false enableNavigation=true enablePagination=true >}}
  {{< swiperItem align=left >}}
markdown
  {{< /swiperItem >}}
  {{< swiperItem align=right >}}
  markdown2
  {{< /swiperItem >}}
  {{< swiperItem align=center >}}
  markdown3
  {{< /swiperItem >}}
  {{< swiperItem >}}
  markdown4
  {{< /swiperItem >}}
{{< /swiper >}}
```

**Comment by szpak** [comment]
Thanks @zzossig! I gave it a try and it works nicely. I have just a few suggestions.

1. I wasn't able to enable autoplay without the shortcode modification which requires:
```
      autoplay: {
        delay: 2500,
        disableOnInteraction: false,
      },
```
There is `var options = JSON.parse({{ $options | jsonify }});`, but it didn't work to put it inline: `{{< swiper ... autoplay="{delay: 2500,disableOnInteraction: false}" >}}`. Later on, I have found that [thread](https://discourse.gohugo.io/t/variables-in-shortcodes/20637/) and I don't know if it is supported that way.

2. When the navigation buttons are enabled, there could be used a style that add some padding on the left/right.

![image](https://user-images.githubusercontent.com/148013/76852481-b400ab00-684b-11ea-9cc2-a8b0709934ad.png)

**Comment by zzossig** [comment]
I suspect that Hugo shortcode does not support passing nested(complex) data structure(At least it is not documented).

So, here is my suggestion.
1. Make a json file at `root/data/swiper.json` and use this file to specify options.
```
{
  "option1": {
    "loop": true
  },
  "option2": {
    "loop": false
  }
}
```
2. And then use the options like this
```
{{< swiper option=option1 enableNavigation=true enablePagination=true >}}
```

**Comment by szpak** [comment]
Nice idea with `option`. It works pretty well. Thanks for implementing it!
