### ISSUE TITLE
Error building site: TOCSS failed to to transform "main_parsed.scss"

### ISSUE THREAD

**Issue by 39roc** [zzossig/hugo-theme-zzo#235]
examplesite에서 config, content, static 디렉토리를 루트 디렉토리에 복사한후 휴고 서버를 작동하였을때 오류가 납니다. 

배경지식 없이 가이드만보고 따라한 경우라 해결방법이 궁금합니다.

![image](https://user-images.githubusercontent.com/60119867/76813716-2ec1ca00-683c-11ea-8a79-d48f7e78ecd0.png)

**Comment by zzossig** [comment]
hugo extended 버전으로 설치셨나요?
커맨드창에 `hugo version` 하셨을 때 `v0.67.1/extended` 처럼 나와야하는데 확인해보시겠어요?

**Comment by 39roc** [comment]
> hugo extended 버전으로 설치셨나요?
> 커맨드창에 `hugo version` 하셨을 때 `v0.67.1/extended` 처럼 나와야하는데 확인해보시겠어요?

해결됬습니다 감사합니다!!
