### ISSUE TITLE
Improved character set declaration

### ISSUE THREAD

**Issue by fandean** [zzossig/hugo-theme-zzo#237]
When I use Baidu-tongji to diagnose the speed of the website, I get the following tips

> There is a problem with the character set declaration. If the character set is not defined in the `<head>` section, it will increase the page rendering times and slow down.

And obtained the following modification suggestions

change 
```html
<meta charset="utf-8">
```
 to 
```html
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
```
How to look at this suggestion?

**Comment by zzossig** [comment]
Ok, I'll follow the Baidu-tongji instruction.
I think nothing seems to be a problem.
