### ISSUE TITLE
Why is Shortcodes still expanded in the code block?

### ISSUE THREAD

**Issue by fandean** [zzossig/hugo-theme-zzo#24]
for example
````
```
    {{< ref "document.md" >}}
    {{< ref "#anchor" >}}
    {{< ref "document.md#anchor" >}}
    {{< ref "my-post" >}}
    {{< ref "my-post.md" >}}
    {{< relref "document.md" >}}
    {{< relref "#anchor" >}}
    {{< relref "document.md#anchor" >}}
```
````
Will be expanded like this

````
```
    http://localhost:1313/en/posts/document/
    #anchor
    http://localhost:1313/en/posts/document/#anchor
    http://localhost:1313/en/posts/my-post/
    http://localhost:1313/en/posts/my-post/
    /en/posts/document/
    #anchor
    /en/posts/document/#anchor
```
````

**Comment by zzossig** [comment]
Hi, fandean😁,
I didn't think about this.
I have to investigate if this is a Hugo issue first.
Of if this is a ref shortcode specific.
Can you give me the "ref" shortcode?

**Comment by fandean** [comment]
Like I'm using the Expand Shortcodes you gave.

{{%expand "Expand me" %}}Good job{{% /expand%}}


![mkcert03](https://user-images.githubusercontent.com/25637720/70207751-9c9f2580-1766-11ea-9988-d74f302407b0.gif)

Logically, it should look like this

```
{{%expand "Expand me" %}}Good job{{% /expand%}}
```

**Comment by fandean** [comment]
I always check whether you have to reply on this [page](https://github.com/zzossig/hugo-theme-zzo/issues), but I did not see until I refresh the page. 
我真是傻得可以

**Comment by zzossig** [comment]
How about just doing syntax escaping? Something like this.
```
{{%/* expand "Expand me" */%}}Good job{{%/* /expand */%}}
```
Test this code. This is what you want? Or ..?

**Comment by fandean** [comment]
![image](https://user-images.githubusercontent.com/25637720/70208967-ed644d80-1769-11ea-8ab8-891f27ee1d51.png)


[Expand :: Documentation for Hugo Learn Theme](https://learn.netlify.com/en/shortcodes/expand/)

**Comment by zzossig** [comment]
I checked that the article is also using syntax escaping method
![syntax escaping](https://user-images.githubusercontent.com/52706977/70209163-dd04a080-1772-11ea-9950-0ff0084db049.png)

**Comment by fandean** [comment]
Do you mean this? ` /* */`

**Comment by zzossig** [comment]
yes. Hugo that part

**Comment by fandean** [comment]
I got it. thanks 😁

**Comment by zzossig** [comment]
Ok, If it's not the one that you mean to, you can suggest another approach. I'm not fully understood the use-case of using shortcodes in a code block. Actually, I found some code doing same thing but a different approach
