### ISSUE TITLE
get selectedtheme variable for use in embed twitter-timeline

### ISSUE THREAD

**Issue by camilomarquez** [zzossig/hugo-theme-zzo#240]
Hi all, please help me...

I am noob with html/hugo codes. I need change twitter timeline theme dynamicaly with zzo.

Twitter timeline has two themes options "dark" o "light" 

I can include themeOption dynamic selected in my twitter-timeline?
Which is the name of "selected theme" variable? localtheme? selectedthemevariant? I cannot access them. :(

Help please

**Comment by zzossig** [comment]
Hi 
I added shortcode named `twitterTimeline`
You can use it like this
```
{{< twitterTimeline href="https://twitter.com/TwitterDev/timelines/539487832448843776?ref_src=twsrc%5Etfw" >}}
placeholder
{{< /twitterTimeline >}}
```

Tell me if it's not working as expected
