### ISSUE TITLE
Search function failed

### ISSUE THREAD

**Issue by ilyusha71** [zzossig/hugo-theme-zzo#241]
Why can't I search?

![001](https://user-images.githubusercontent.com/13597264/77845571-81a76400-71e2-11ea-81d3-c141b5ab04b9.png)

![003](https://user-images.githubusercontent.com/13597264/77845569-7fdda080-71e2-11ea-8360-ffc6bcaaf37d.png)

but, http://localhost:1313/  can work well
![002](https://user-images.githubusercontent.com/13597264/77845570-810ecd80-71e2-11ea-9451-1f4bcf918acf.png)

**Comment by Asjas** [comment]
Hi, @ilyusha71 
This is the same issue as #214. Check their solution and it will fix it for you as well :)

**Comment by ilyusha71** [comment]
> Hi, @ilyusha71
> This is the same issue as #214. Check their solution and it will fix it for you as well :)

thank u
I find the my mistake
and solved

my config.toml  
baseURL = "http://ilyusha71.github.io/"
fix
baseURL = "https://ilyusha71.github.io/"

ref 
https://segmentfault.com/q/1010000005872734

**Comment by camilomarquez** [comment]
its better this baseURL="/"
work locally and online
