### ISSUE TITLE
Single page meta info style is broken

### ISSUE THREAD

**Issue by Jason-cqtan** [zzossig/hugo-theme-zzo#25]
![231575550243_ pic_hd](https://user-images.githubusercontent.com/17697213/70236990-09371600-17a1-11ea-8e13-80677fd9e69a.jpg)
in my phone（Nokia 7 plus） view site

**Comment by zzossig** [comment]
Oh, Good! Thank you for the bug report. It will be fixed in the next commit. Anyway, I just checked your blog.
![bz](https://user-images.githubusercontent.com/52706977/70237126-c9286100-17a9-11ea-9be7-dcfb3db9cbe9.png)
Do you want a bigger size?

**Comment by Jason-cqtan** [comment]
Enough size, that's it.

**Comment by zzossig** [comment]
@Jason-cqtan It's fixed now😋
