### ISSUE TITLE
deploy file is too big

### ISSUE THREAD

**Issue by iamwlb** [zzossig/hugo-theme-zzo#251]
when run hubo command
1. every article folder has same file named index.json.
2. tag folder is too big,500MB.

**Comment by szpak** [comment]
I don't know much about the search engine used in that theme, but if it is not the crucial feature for you, it can be disabled with `enableSearch = false` (which maybe also will stop creating those files).

**Comment by zzossig** [comment]
I have noticed that as more posts we have, the index file grows exponentially.
I will do something for it.

**Comment by zzossig** [comment]
I made changes to it.
The big file was because search indexes made for every page.
You have to update the zzo theme first
And then delete the `outputs.page` variable in `config.toml` file.
That variable is the cause of the big file.

```diff
[outputs]
  page = ["HTML", "SearchIndex"]
```
