### ISSUE TITLE
How to modify the background color of the markdowm code fragment

### ISSUE THREAD

**Issue by menggus** [zzossig/hugo-theme-zzo#259]
How to modify the background color of the markdowm code fragment
The background of my page rendering is black, it seems to make me feel strenuous
thank！

**Comment by zzossig** [comment]
What do you mean by `markdown code fragment`?
Did you mean one backtick like this 

case 1: `this is one backtick`

Or Did you mean triple backtick like this 
case 2: 
```javascript
var a=1;
```

In case 1, unfortunately, we can not change the background of the code block.
In case 2, read this page https://zzodocs.netlify.app/docs/customization/customsyntax/
