### ISSUE TITLE
Hugo's built-in figure shortcode title appears in toc

### ISSUE THREAD

**Issue by nocquidant** [zzossig/hugo-theme-zzo#26]
I couldn't find an easy way for my figure titles not to be in the toc.

![image](https://user-images.githubusercontent.com/217054/70322879-9b83fc00-182b-11ea-96fc-b12c22e3cf64.png)

Maybe using h5 for figure titles as default ? Or give the opportunity for the user to configure the depth of the toc?

Thank you for your work!
--nick

**Comment by zzossig** [comment]
Hi, thank you for using the Zzo theme. I'll investigate for this

**Comment by zzossig** [comment]
Hey~ I want to know how did you import the image. Did you use the shortcode that this theme provides?

**Comment by nocquidant** [comment]
Actually I used the "native" Hugo shotcode,  {{< figure src=
"/media/spf13.jpg" title="Steve Francia" >}}

I saw the custom "img" shortcode but I couldn't manage to get it work... I
will try again soon!

**Comment by nocquidant** [comment]
Actually I used the "native" Hugo shotcode: `{{< figure src="/media/spf13.jpg" title="Steve Francia" >}}`

I saw the custom `img` shortcode but I couldn't manage to get it work... I will try again soon!

**Comment by nocquidant** [comment]
OK, my bad, the following works: `{{< img src="../../images/whoami/avatar.jpg" title="Image4" caption="Image description" alt="image alt" >}}`.

But not with the absolute path in `src`, because of my baseURL with a path (`baseURL = "https://host.fr/blog/"`)?

And also I really miss a way to customize the size of the image width/height attribute from the figure shortcode: `{{< figure src="/media/spf13.jpg" width="100x" title="Steve Francia" >}}`

**Comment by zzossig** [comment]
Do you want to use an absolute path? I don't have a solution right now. I'll think about it why the absolute path is not working. And I'll add width and height property to the image shortcode soon😋

**Comment by nocquidant** [comment]
No, it's OK for me for the path ;) Great to hear that you'll add width and height property to the image shortcode soon.

Thanks!

**Comment by zzossig** [comment]
I just added width and height property. You can do like this
```bash
{{< img src="../../images/whoami/avatar.jpg" title="Image4" caption="Image description" alt="image alt" width="100px" height="100px" >}}
```
