### ISSUE TITLE
비공개 포스팅

### ISSUE THREAD

**Issue by hoontaeklee** [zzossig/hugo-theme-zzo#263]
안녕하세요.

혹시 hugo로 빌드는 하지만, **나만 볼 수 있게**하는 것도 가능할까요?
front matter의 **draft**와 비슷하지만, draft는 아직 작성 중이라 빌드 자체가 안 되는 것이고 저는 빌드는 하되 저만 볼 수 있기를 원합니다. 네이버에서 이웃공개, 비공개 이런 것처럼요(이렇게 여러 단계로도 설정 가능하지는 잘 모르지만 가능하다면 물론 좋을 것 같습니다).
[이런 의견](https://discourse.gohugo.io/t/how-to-exclude-content-from-list/24358/2)도 찾아봤는데, 이해는 잘 되지 않았습니다.

감사합니다

**Comment by zzossig** [comment]
안타깝지만 그런 기능은 hugo처럼 static한 사이트 만드는 곳에서는 좀 힘들어요.
예전에 휴고 커뮤니티에서 이런 논의가 있었던거 같은데
이게 현재 접속한 사람이 누군지 알아야 되는거면 서버를 또 따로 돌리던가 해야할텐데(접속한 사람이 누구인지 알려면 회원가입도 해야지 않을까요?)
휴고 테마 차원에서는 지원할 수 있는 범위가 아니라서 ㅠㅠ

**Comment by hoontaeklee** [comment]
안 되는군요 ㅜㅜ 
답변 감사드립니다.
