### ISSUE TITLE
Always getting Error: Error building site

### ISSUE THREAD

**Issue by yvza** [zzossig/hugo-theme-zzo#265]
im new in hugo, and started to use zzo theme. after following this instruction [here](https://zzodocs.netlify.app/docs/gettingstarted/quickstart/). i got this error:

![Image 4](https://user-images.githubusercontent.com/25668079/80376444-0362de00-88c4-11ea-8734-bf582f6cd450.png)

**Comment by fandean** [comment]
#1

**Comment by zzossig** [comment]
As @fandean pointed,
I suspect you are using external API or something.
