### ISSUE TITLE
Inline verbatim gets too much margin and padding

### ISSUE THREAD

**Issue by cpbotha** [zzossig/hugo-theme-zzo#266]
In the screenshot below, the margin and padding added by zzo to inline `<code>` elements, the result of backtick-surrounded inline keywords in the source markdown, results in the unwanted indentation that you see.

Why does zzo add this padding and margin to inline `<code>`? Is there a way to deactivate it without having to override the theme CSS?

You can view the site [here](https://orgmode-exocortex.com/2020/04/27/cite-consistently-between-org-ref-and-ox-hugo/#what-exactly-is-the-issue), and below is also the source markdown.

```markdown
## What exactly is the issue?

`org-ref` expects citations of the form `cite:surname2011` or
`cite:surname2011,otherref2012`. Depending on the bibliography
configuration, `citep:` and `cite:` can result in different output,
e.g. parenthetical or inline.

`ox-hugo` first converts org mode to blackfriday-flavour markdown, and
then, if if the relevant metadata is found, passes that markdown through
pandoc and pandoc-citeproc to have [pandoc-style
`[@surname2011;otherref2012]`
citations](https://pandoc.org/MANUAL.html#citations) resolved.
```

![image](https://user-images.githubusercontent.com/937871/80420464-192fcd80-88db-11ea-895f-c0bd38dc2642.png)

**Comment by cpbotha** [comment]
I commented out the relevant padding and margin settings in `_single.scss` to fix those inline keywords.

I would still like to know if there's a better way though. :)

**Comment by yangchuansheng** [comment]
> I commented out the relevant padding and margin settings in `_single.scss` to fix those inline keywords.
> 
> I would still like to know if there's a better way though. :)

Can you explain it in detail？

**Comment by cpbotha** [comment]
> > I commented out the relevant padding and margin settings in `_single.scss` to fix those inline keywords.
> > I would still like to know if there's a better way though. :)
> 
> Can you explain it in detail？

I searched for all occurrences of `code:not([class^=language])` in `_single.scss` and commented out the padding declaration.

**Comment by zzossig** [comment]
Thank you for point me it out!
I fixed it.
