### ISSUE TITLE
Website width and image size

### ISSUE THREAD

**Issue by 997volt** [zzossig/hugo-theme-zzo#268]
Is there any easy way to change page width (to use more space with higher resolution)? 
Also I would like the post images on the homepage to be bigger - is it customizable?

**Comment by szpak** [comment]
Yes, see [this commit](https://github.com/zzossig/hugo-theme-zzo/commit/0dc9e52ff720b5ce82a49c024f75a678e3d832ee) or consult the README file:
> viewportSize = "normal" # widest, wider, wide, normal, narrow

**Comment by 997volt** [comment]
Thanks, I switched viewporst size to wide and summaryshape to card and it looks exacly as I wanted.
Is there any chance to globally increase the font size? I would love that.
