### ISSUE TITLE
Top navigation bar hides section title when reached via external links

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#269]
A minor issue, but if the URL to a given section in the blog post is first time visited (e.g. from the external link) - see [this](https://themes.gohugo.io//theme/hugo-theme-zzo/en/posts/markdown-syntax/#tables) - the "Table" title is hidden by the top navigation bar:
![image](https://user-images.githubusercontent.com/148013/81175273-8e6a6500-8fa3-11ea-84bb-4c570d8e7c10.png)

Unfortunately, it might be tricky to fix as clicking the link in the TOC, just scrolls down to that place (which hides the bar) and it works correctly:
![image](https://user-images.githubusercontent.com/148013/81175398-c376b780-8fa3-11ea-9460-ab0f92d331dc.png)

Firefox 75.

**Comment by zzossig** [comment]
fixed in 5acd052

**Comment by szpak** [comment]
Cool, thanks!
