### ISSUE TITLE
I like your work very much and hope to add Chinese support

### ISSUE THREAD

**Issue by Codeapes666** [zzossig/hugo-theme-zzo#27]

**Comment by zzossig** [comment]
@Codeapes666 Hi, I really glad to hear that. I'm also thankful that my Chinese friends find many bugs and tested this repository.

Ok! I really want to support the Chinese language but how?
Do you mean that i18n translation file? Or the Chinese version of the README.MD file?

**Comment by fandean** [comment]
对的，我也想问，你说的添加中文支持具体指什么？ 😄

**Comment by fandean** [comment]
I think he means support for Chinese search

**Comment by zzossig** [comment]
I'm using lunr.js for a site searching library. It seems that the Chinese language not supported yet.
There is a [pull request](https://github.com/MihaiValentin/lunr-languages/pull/53) for supporting Chinese. But I don't know why the repository owner does not merge the pull request.

I'll think more about how to support Chinese

**Comment by fandean** [comment]
I've also thought about lunr.js not supporting Chinese search, and I've considered using Google, Baidu, Bing's in-station search, but I don't feel the style is right.

I hope the search features used in this [blog](https://www.flysnow.org/)  below will give you some inspiration.

**Comment by zzossig** [comment]
@fandean Thank you for spent time with me! I'll add a Chinese search in the future! I'll make a new issue regarding this.

**Comment by Codeapes666** [comment]
@zzossig  I means support for Chinese search, and also see that lunr does not support Chinese at present.

**Comment by Codeapes666** [comment]
@zzossig But I see that this link(https://github.com/nandy007/lunr.js) solves the problem of Chinese search, but I don't understand his meaning at present. I'm a rookie.

**Comment by zzossig** [comment]
Thanks for the information! I'll investigate more about it. I promise the Chinese search supported in the future

**Comment by zzossig** [comment]
@Codeapes666 Update your blog with the latest version of the Zzo theme. I have added support for Chinese. 
使用最新版本的Zzo主题更新您的博客。我增加了对中文的支持

**Comment by Codeapes666** [comment]
It's very nice. Perfect supports Chinese search.

**Comment by zzossig** [comment]
@Codeapes666 You finally did it. I'm proud of you
