### ISSUE TITLE
Netlify deploy failed.

### ISSUE THREAD

**Issue by harkanatta** [zzossig/hugo-theme-zzo#270]
Here is the deploy log from netlify. The first error: "...Theme does not support Hugo version" can be fixed by changing the "min_version" in "theme.toml" but the same error is repeated five times and has to do with "tags.html". Can somebody assist me with this?

12:34:33 AM: Waiting for other deploys from your team to complete
12:34:44 AM: Build ready to start
12:34:46 AM: build-image version: 6dfe19d15f524c85d6f9bf7df9fb30b0a9f0a61a
12:34:46 AM: build-image tag: v3.3.10
12:34:46 AM: buildbot version: 6bb3f784302b4ad90de13035b247a363a8bee34a
12:34:46 AM: Fetching cached dependencies
12:34:46 AM: Starting to download cache of 254.9KB
12:34:46 AM: Finished downloading cache in 70.740469ms
12:34:46 AM: Starting to extract cache
12:34:46 AM: Failed to fetch cache, continuing with build
12:34:46 AM: Starting to prepare the repo for build
12:34:46 AM: No cached dependencies found. Cloning fresh repo
12:34:46 AM: git clone https://github.com/harkanatta/biopolhugo
12:34:47 AM: Preparing Git Reference refs/heads/master
12:34:48 AM: Starting build script
12:34:48 AM: Installing dependencies
12:34:49 AM: v10.20.1 is already installed.
12:34:50 AM: Now using node v10.20.1 (npm v6.14.4)
12:34:50 AM: Attempting ruby version 2.6.2, read from environment
12:34:51 AM: Using ruby version 2.6.2
12:34:52 AM: Using PHP version 5.6
12:34:52 AM: 5.2 is already installed.
12:34:52 AM: Using Swift version 5.2
12:34:52 AM: Started restoring cached go cache
12:34:52 AM: Finished restoring cached go cache
12:34:52 AM: go version go1.12 linux/amd64
12:34:52 AM: go version go1.12 linux/amd64
12:34:52 AM: Installing missing commands
12:34:52 AM: Verify run directory
12:34:52 AM: Executing user command: hugo
12:34:52 AM: ERROR 2020/05/08 23:34:52 HUGO-THEME-ZZO theme does not support Hugo version 0.54.0. Minimum version required is 0.69.2
12:34:52 AM: Building sites …
12:34:58 AM: ERROR 2020/05/08 23:34:58 render of "page" failed: execute of template failed: template: _default/single.html:20:9: executing "main" at <partial "body/tags" ...>: error calling partial: "/opt/build/repo/themes/hugo-theme-zzo/layouts/partials/body/tags.html:6:10": execute of template failed: template: partials/body/tags.html:6:10: executing "partials/body/tags.html" at <.GetTerms>: can't evaluate field GetTerms in type *hugolib.PageOutput
12:34:58 AM: ERROR 2020/05/08 23:34:58 render of "page" failed: execute of template failed: template: _default/single.html:20:9: executing "main" at <partial "body/tags" ...>: error calling partial: "/opt/build/repo/themes/hugo-theme-zzo/layouts/partials/body/tags.html:6:10": execute of template failed: template: partials/body/tags.html:6:10: executing "partials/body/tags.html" at <.GetTerms>: can't evaluate field GetTerms in type *hugolib.PageOutput
12:34:58 AM: ERROR 2020/05/08 23:34:58 render of "page" failed: execute of template failed: template: _default/single.html:20:9: executing "main" at <partial "body/tags" ...>: error calling partial: "/opt/build/repo/themes/hugo-theme-zzo/layouts/partials/body/tags.html:6:10": execute of template failed: template: partials/body/tags.html:6:10: executing "partials/body/tags.html" at <.GetTerms>: can't evaluate field GetTerms in type *hugolib.PageOutput
12:34:58 AM: ERROR 2020/05/08 23:34:58 render of "page" failed: execute of template failed: template: _default/single.html:20:9: executing "main" at <partial "body/tags" ...>: error calling partial: "/opt/build/repo/themes/hugo-theme-zzo/layouts/partials/body/tags.html:6:10": execute of template failed: template: partials/body/tags.html:6:10: executing "partials/body/tags.html" at <.GetTerms>: can't evaluate field GetTerms in type *hugolib.PageOutput
12:34:58 AM: ERROR 2020/05/08 23:34:58 render of "page" failed: execute of template failed: template: _default/single.html:20:9: executing "main" at <partial "body/tags" ...>: error calling partial: "/opt/build/repo/themes/hugo-theme-zzo/layouts/partials/body/tags.html:6:10": execute of template failed: template: partials/body/tags.html:6:10: executing "partials/body/tags.html" at <.GetTerms>: can't evaluate field GetTerms in type *hugolib.PageOutput
12:34:58 AM: Total in 6133 ms
12:34:58 AM: Error: Error building site: failed to render pages: render of "taxonomyTerm" failed: "/opt/build/repo/themes/hugo-theme-zzo/layouts/_default/terms.html:10:23": execute of template failed: template: _default/terms.html:10:23: executing "main" at <.Page.RelPermalink>: can't evaluate field Page in type hugolib.WeightedPages
12:34:58 AM: Skipping functions preparation step: no functions directory set
12:34:58 AM: Caching artifacts
12:34:58 AM: Started saving pip cache
12:34:58 AM: Finished saving pip cache
12:34:58 AM: Started saving emacs cask dependencies
12:34:58 AM: Finished saving emacs cask dependencies
12:34:58 AM: Started saving maven dependencies
12:34:59 AM: Finished saving maven dependencies
12:34:59 AM: Started saving boot dependencies
12:34:59 AM: Finished saving boot dependencies
12:34:59 AM: Started saving go dependencies
12:34:59 AM: Finished saving go dependencies
12:35:04 AM: Error running command: Build script returned non-zero exit code: 255
12:35:04 AM: Failing build: Failed to build site
12:35:04 AM: Failed during stage 'building site': Build script returned non-zero exit code: 255
12:35:04 AM: Finished processing build request in 18.294576126s

**Comment by szpak** [comment]
Set:
```
HUGO_VERSION = "0.69.2"
```
in your `netlify.toml` to enforce higher hugo version. See [this documentation](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify).

**Comment by harkanatta** [comment]
Hi. Thanks. I didn't even know about toml files. Started out on the wrong end of this. Am reading up on the documentation :)
