### ISSUE TITLE
Clicking a footnote's "return" button loads the content too far up because header is animated late

### ISSUE THREAD

**Issue by RheingoldRiver** [zzossig/hugo-theme-zzo#278]
[Here's](https://river.me/beta/blog/vscode-1/#fnref:1) the example post I'm working on right now, if you click to return, it's displayed like this:
![image](https://user-images.githubusercontent.com/18037011/82872489-bdb42800-9ef8-11ea-8600-af8ab95c30ee.png)

If I display:none; the navbar (didn't scroll at all), you can see it's positioned correctly:

![image](https://user-images.githubusercontent.com/18037011/82872573-d8869c80-9ef8-11ea-8fac-a80c257882d8.png)

But since the navbar does exist, the line with the footnote is scrolled too far up.

Thanks!

**Comment by szpak** [comment]
Related to #269.

**Comment by RheingoldRiver** [comment]
ah makes sense, could you make this case behave similarly to TOC section jumping as at least a temporary fix?

**Comment by szpak** [comment]
Unfortunately, I'm not familiar with CSS/JS. Probably @zzossig would need to fix it.

I've just noticed that it is a wider case with the top navigation bar.

**Comment by zzossig** [comment]
fixed in 5acd052
