### ISSUE TITLE
Toggle reading time info OFF

### ISSUE THREAD

**Issue by shrysr** [zzossig/hugo-theme-zzo#281]
zzo is a great theme and I am in the process of switching over to zzo from the academic theme. Thank you for your creation!

Is there a method to globally toggle the reading time that is displayed under each item?

**Comment by szpak** [comment]
Looking at [the implementation](https://github.com/zzossig/hugo-theme-zzo/blob/f82edf80dec12b53e5b7f126cbffe528e6095ea3/layouts/partials/summary/classic.html#L26) there is none. However, if you need it, you can surround it with the `with` section and check the presence of some new site variable (defaulting to showing the value if not explicitly disabled).

**Comment by zzossig** [comment]
No, we don't have that option.
You may need to override the summary file in `layouts/partials/summary/(classic or card or compact).html`
