### ISSUE TITLE
Hiding bio on pages

### ISSUE THREAD

**Issue by prashanth1k** [zzossig/hugo-theme-zzo#283]
Great work with this theme! 🙏

I had a question on the `enableBio` param and how it differs from `enableWhoami`. 

[`Showcase` page documentation](https://themes.gohugo.io/hugo-theme-zzo/#showcase-page) mentions a frontmatter param called `enableBio`.
```
---
title: "Showcase overview" # For SEO
enableBio: true # Set to false if you want to hide the bio component.
---
```

I was under the impression that this is applicable across the board, but I was wrong. Instead, we have another param called `enableWhoami` which controls whether the bio partial is displayed on the page. Are these two params intended to be distinct and serve different purposes? 

If not, I can create a PR to change `partials/body/whoami.html` to use the same param name (`enableBio` is more clear :)).

**Comment by zzossig** [comment]
The two params have different purposes.
The enableBio front-matter used on the Showcase is a special case.

![bio](https://user-images.githubusercontent.com/52706977/84348503-128db900-abf0-11ea-87fd-b4b2c3f53cb6.png)

![whoami](https://user-images.githubusercontent.com/52706977/84348451-e8d49200-abef-11ea-9819-ccd6beda2056.png)

I think it is fine as it is
