### ISSUE TITLE
Build site JSON parse error

### ISSUE THREAD

**Issue by Jia35** [zzossig/hugo-theme-zzo#285]
Hello
I encountered the following problem while building Site.
```
$ hugo --minify
Building sites … ERROR 2020/06/09 20:56:12 JSON parse error: unexpected comma character on line 9 and column 20
    9:     "description": ,
                          ^
ERROR 2020/06/09 20:56:12 JSON parse error: unexpected comma character on line 9 and column 20
    9:     "description": ,
                          ^
Total in 8639 ms
Error: Error building site: failed to render pages: JSON parse error: unexpected comma character on line 9 and column 20
    9:     "description": ,
                          ^
```
But there are no errors when testing with other themes.
How can I fix it?

Thanks!

----------
OS: Windows 10
Hugo: v0.72.0/extended
Hugo Theme: Zzo 4c77300

**Comment by Jia35** [comment]
Later I discovered that it might be caused by `content > en > publication`.
Because I removed this folder and it works.

**Comment by zzossig** [comment]
I have test with `hugo` commend and it worked.
I don't know why `hugo --minify` did not work.
I think it's the best choice to use `hugo` comment for building site now
