### ISSUE TITLE
Questions on galleries (and potential featue requests)

### ISSUE THREAD

**Issue by woolwood** [zzossig/hugo-theme-zzo#288]
I have two questions on galleries:

1. The zzo theme supports galleries in two modes, one-by-one and at-once. If I read the documentation right, it's not possible to use image captions when using at-once mode? So if I have a lot of images and only some need captions, I must specify them all?
2. Is it possible to use the gallery inside a blogpost as a shortcode? To load a bunch of images I want to post in a blog post automatically.

**Comment by Toriniasty** [comment]
I'll chuck in one question if that's fine with you.  
Is it possible to hide gallery post from the main page?

**Comment by szpak** [comment]
> Is it possible to hide gallery post from the main page?

Add "gallery" to the `notAllowedTypesInHome` list in `params.toml` (see the README file).

**Comment by ttnghia** [comment]
Hi! 

I also have a question regarded to the gallery: 

Problem: In "all-at-once" mode, the gallery shows all images. If I have several thousand images, that would cause a lot of bandwidth throttle. 

Question: Is there a way to split a gallery into multiple pages, each page contains at max (some number) of images?

Thank you.

**Comment by Mangaman2** [comment]
ttnghia wrote:
> 
> Hi!
> 
> I also have a question regarded to the gallery:
> 
> Problem: In "at-once" mode, the gallery shows all images. If I have several thousand images, that would cause a lot of bandwidth throttle.
> 
> Question: Is there a way to split a gallery into multiple pages, each page contains at max (some number) of images?
> 
> Thank you.

I have the very same question.

**Comment by zzossig** [comment]
@woolwood
1. yes
2. You can't use the gallery as a shortcode.
@ttnghia @Mangaman2
Each gallery page doesn't have a max of images. Just make multiple folders in the gallery folder like the posts folder.
![화면 캡처 2020-10-16 124929](https://user-images.githubusercontent.com/52706977/96210975-12dafe00-0fae-11eb-9875-02f37f819400.png)
