### ISSUE TITLE
Questions on Adsense integration

### ISSUE THREAD

**Issue by wariored** [zzossig/hugo-theme-zzo#289]
I am trying to add Google Adsense and I have seen no documentation talking about that. I have tried to override `layouts/partials/service/google-adsense.html` but it's not working.

**Comment by Puliyo** [comment]
It's not documented however working for me after taking below steps:

1. Add field to config.toml
`disableAdsense = false`

2. Insert partial to where-ever you want it to make it appear
`{{ partial "service/google-adsense" . }}`

**Comment by zzossig** [comment]
I think @Puliyo explained well enough.

But if you don't want to touch the `themes/zzo` folder (for a future update) you may have to insert `{{ partial "service/google-adsense" . }}` to custom HTML file.

We have 4 custom HTML file to override.
- body/custom-header.html
- header/custom-header.html
- sidebar/custom-home.html
- sidebar/custom-list.html

So, If you want to insert the Adsense shortcode to the home page sidebar,
1. Override the `root/themes/zzo/layouts/partials/sidebar/custom-list.html` by making file at `root/layouts/partials/sidebar/custom-list.html`
2. Insert the shortcode `{{ partial "service/google-adsense" . }}` to the file(custom-list.html)

If you want to insert AdSense shortcode to another position, you may need a different HTML file to override. Then, make a new issue for it
