### ISSUE TITLE
Social icons customization, baseURL problem

### ISSUE THREAD

**Issue by Codeapes666** [zzossig/hugo-theme-zzo#29]
I want to add Chinese social icons, but there is a problem with the svg picture display.

**Comment by zzossig** [comment]
What social icon do you need?

**Comment by Codeapes666** [comment]
Like csdn(https://www.csdn.net/), jianshu(https://www.jianshu.com/), zhihu(https://www.zhihu.com/), weibo(https://weibo.com/), cnblogs(https://www.cnblogs.com/), etc. I know a website(https://www.iconfont.cn/) , these icons can be found on it, but I ca n’t figure out the size and color of the icons.Oh, there is another problem. When the mobile terminal enters the Posts in this topic, it is obvious that there is a process that the PC adapts to the mobile terminal.

**Comment by zzossig** [comment]
> When the mobile terminal enters the Posts in this topic, it is obvious that there is a process that the PC adapts to the mobile terminal.

I don't understand what this means. Do you want to write a post on a mobile phone? How did you try?

**Comment by Codeapes666** [comment]
**Open the article on mobile, and it  like this** 
 [![QUv0sJ.md.jpg](https://s2.ax1x.com/2019/12/08/QUv0sJ.md.jpg)](https://imgse.com/i/QUv0sJ)  

**The page format will be normal after a while**
  [![QUvrZR.md.jpg](https://s2.ax1x.com/2019/12/08/QUvrZR.md.jpg)](https://imgse.com/i/QUvrZR)

**Comment by zzossig** [comment]
You can customize the social icons by overriding the theme folder.
For example, If you want to change the social icons in the sidebar, 
make file at 

root/layouts/partials/sidebar/site-bio.html 
root/layouts/partials/svgs/social/mySocialIcon.svg

and then replace the icon to yours.

before
```html
root/layouts/partials/sidebar/site-bio.html
...
<div class="bio__social">
{{ range $name, $path := $.Param "socialOptions" }}
  {{ if (and $path (ne $name "email")) }}
    <a href="{{ $path | safeURL }}" title="{{ $name }}" aria-label="{{ $name }}">
      {{ partial (print "svgs/social/" $name ".svg") (dict "width" 25 "height" 25) }}
    </a>
  {{ end }}
{{ end }}
</div>
...
```

after
```html
root/layouts/partials/sidebar/site-bio.html
...
<div class="bio__social">
<a href="{{ $path | safeURL }}" title="{{ $name }}" aria-label="{{ $name }}">
   {{ partial (print "svgs/social/" $name ".svg") (dict "width" 25 "height" 25 "color" "#123456") }}
</a>
</div>
...
```

edit your svg icon

```svg
root/layouts/partials/svgs/social/mySocialIcon.svg
<svg xmlns="http://www.w3.org/2000/svg" width="{{ .width }}" height="{{ .height }}" viewBox="0 0 24 24">
<path fill="none" d="M0 0h24v24H0V0z"/>
<path fill="{{ .color }}" d="M19 11H7.83l4.88-4.88c.39-.39.39-1.03 0-1.42-.39-.39-1.02-.39-1.41 0l-6.59 6.59c-.39.39-.39 1.02 0 1.41l6.59 6.59c.39.39 1.02.39 1.41 0 .39-.39.39-1.02 0-1.41L7.83 13H19c.55 0 1-.45 1-1s-.45-1-1-1z"/>
</svg>
```

**Comment by zzossig** [comment]
Oh, I see what you mean. I'll check if I can do something for it.
Anyway, do you understand how to customize the social icons?

**Comment by Codeapes666** [comment]
Thank you very much, I have customized the social icons. I also modified the baseURL.

**Comment by Codeapes666** [comment]
I have modified the baseURL in config.toml, but the search still shows the following error.
```JavaScript
Access to XMLHttpRequest at 'https://codeapes666.github.io//zh/index.json' 
from origin 'https://www.codeapes.cn' has been blocked by CORS policy: 
No 'Access-Control-Allow-Origin' header is present on the requested resource.
```
```JavaScript
 Uncaught TypeError: Cannot read property 'search' of null
    at search ((index):63)
    at HTMLInputElement.<anonymous> ((index):135)
    at HTMLInputElement.dispatch (jquery.min.0925e8ad7bd971391a8b1e98be8e87a6971919eb5b60c196485941c3c1df089a.js:2)
    at HTMLInputElement.v.handle 
```

**Comment by zzossig** [comment]
@Codeapes666 What value did you set the baseURL?

**Comment by Codeapes666** [comment]
baseURL = "https://www.codeapes.cn/"

**Comment by zzossig** [comment]
I think baseURL = ""  will solve the problem

**Comment by Codeapes666** [comment]
However this does not help. I build everything locally is normal.

**Comment by zzossig** [comment]
@Codeapes666 In case you don't want to change baseURL in the config file, there is one another option. You can override the scripts.html file. But I don't understand there is no reason not to change the baseURL variable.

And I just updated the issue you mentioned above. Can you update the theme and check it works as expected?

**Comment by Codeapes666** [comment]
Still won’t do, I feel like the link (https://codeapes666.github.io//zh) has a ‘/‘ after io, not two.

**Comment by zzossig** [comment]
也许，有些误解了。
您是否在root / config / default / config.toml处更改了baseURL？

**Comment by Codeapes666** [comment]
已经更改了，我现在都懵了，不清楚baseURL应该填什么

**Comment by zzossig** [comment]
只需将其设置为空值
```toml
baseURL = ""
```

**Comment by Codeapes666** [comment]
OK，我再尝试下。

**Comment by zzossig** [comment]
@Codeapes666 
抱歉给你带来不便. 
我对此做了一些更改。
提交代码后，我会再告诉您。

**Comment by Codeapes666** [comment]
我试了设置为baseURL = ""，还是不行。您说的完全没关系，我非常高兴使用您制作的主题，真的很棒。

**Comment by zzossig** [comment]
我弄清楚了为什么它不起作用。

**Comment by zzossig** [comment]
首先再次下载主题。
And in the file at root/themes/layouts/head/scripts.html, 将其更改为以下值：

before (line 17~)
```
{{ if .Site.IsMultiLingual }}
        var baseurl = "{{.Site.BaseURL}}{{.Site.LanguagePrefix}}";
    {{ else }}
        var baseurl = "{{.Site.BaseURL}}";
    {{ end }}
```

after (line 17~)
```
{{ if .Site.IsMultiLingual }}
        var baseurl = "//www.codeapes.cn{{.Site.LanguagePrefix}}";
    {{ else }}
        var baseurl = "//www.codeapes.cn";
    {{ end }}
```
我很确定，如果您这样做，它应该可以工作。

**Comment by zzossig** [comment]
It is also possible to override the theme's scripts.html file.
Make file at root/layouts/head/scripts.html
And copy-paste the theme's scripts.html
And change the value like the above.

**Comment by Codeapes666** [comment]
真的很厉害，搜索可以正常使用了，但下面的报错还是会出现
```JavaScript
ccess to resource at 'https://codeapes666.github.io/zh/webmanifest.webmanifest' from origin 

'https://www.codeapes.cn' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' 

header is present on the requested resource.
```
而且，我发现在params.toml启用baiduAnalytics后会出现下面的错误：
```JavaScript
 GET https://hm.baidu.com/hm.js?1538507a5372feb11f32dd5531754645 

net::ERR_SSL_PROTOCOL_ERROR
```

**Comment by zzossig** [comment]
如果您发现cors错误，则搜索将起作用。
您可以轻松修复此错误。
Make a file at root/layouts/home.webmanifest 
And copy-paste code from root/themes/zzo/layouts/home.webmanifest
然后像这样编辑home.webmanifest文件。

before
```bash
{
  "name": "{{site.Title}}",
  "short_name": "{{site.Title}}",
  "lang": "{{site.Language.Lang}}",
  "theme_color": "#FF6188",
  "background_color": "#2D2A2E",
  "icons": [{
      "src": "{{ .Site.BaseURL }}{{ "logo-192.png" }}",
      "sizes": "192x192",
      "type": "image/png"
    }, {
      "src": "{{ .Site.BaseURL }}{{ "logo-512.png" }}",
      "sizes": "512x512",
      "type": "image/png"
    }],
  "display": "standalone",
  "start_url": "{{ "/" | relLangURL }}?utm_source=web_app_manifest"
}

```

after
```bash
...
"icons": [{
      "src": "//www.codeapes.cn{{ "logo-192.png" }}",
      "sizes": "192x192",
      "type": "image/png"
    }, {
      "src": "//www.codeapes.cn{{ "logo-512.png" }}",
      "sizes": "512x512",
      "type": "image/png"
    }],
...
```

**Comment by zzossig** [comment]
您可以打开有关baiduAnalytics的新问题吗？
这个线程太长了。 我必须调查更多有关BaiduAnalytics的信息。
这里的对话记录太长。

**Comment by Codeapes666** [comment]
好的

**Comment by zzossig** [comment]
We can close this issue now
