### ISSUE TITLE
Config param to disable animations

### ISSUE THREAD

**Issue by VictorZakharov** [zzossig/hugo-theme-zzo#291]
I am fairly certain that page load could be improved by at least 2x if I disable "slide in" animation for page title and then content.
Would it be possible to add configuration param to disable it? Thanks.

Example page: https://www.neolisk.blog/posts/2020-05-17-blazor-qa-with-tim-corey/

**Comment by szpak** [comment]
Have you tried `enableUiAnimation = false` in `params.toml`?

**Comment by VictorZakharov** [comment]
Thanks @szpak, my local config does not have this param (and many others that were added since my initial deployment). It works well, much faster now.
