### ISSUE TITLE
[Feature Req] Image dimming when on dark themes

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#301]
I saw this recently: https://www.producthunt.com/posts/image-dimmer

Was thinking would be nice to dim the images in the blog when it is using say a dark theme.

Suggestion:
1. Each theme can be marked as dark or light theme.
2. In the config, we have dimImageInDarkTheme = true
3. When enabled, an extra css is applied which reduces the opacity to 25%. On hover of the image, the opacity is brought back to 100% (so user is still able to see the full opacity image when they put their mouse over it).

Thoughts?

**Comment by zzossig** [comment]
Sorry, I don't think we need it.
