### ISSUE TITLE
How to change the default site logo to my own logo?

### ISSUE THREAD

**Issue by harshvardhan-shah** [zzossig/hugo-theme-zzo#303]
I'm a newbie to website making. 
How can I replace the default theme logo to the logo I want? I have placed logo.png in the static/images/ directory. It didn't work.
Another thing, I want to show only logo, not the text. How do I do that?

Thanks.

**Comment by zzossig** [comment]
You should place the `logo.png` file to `static` directory. not `static/images` directory

And insert `logoText = ""` or just delete this param in your `params.toml` file.
