### ISSUE TITLE
사진 클릭하면 나타는 주소 없애기

### ISSUE THREAD

**Issue by hoontaeklee** [zzossig/hugo-theme-zzo#304]
안녕하세요.
게시글에 포함한 사진을 클릭하면 가운데 사진이, 그리고 그 아래에 주소가 같이 나타납니다. 저 주소가 모바일에서는 사진을 가리는 경우가 자주 있어서 혹시 주소를 없앨 수 있다면 정말 좋을 것 같습니다.

**Comment by zzossig** [comment]
img 라는 shortcode를 이용해 보시겠어요?
caption 쪽 속성을 바꾸면 될거같아요 
https://zzodocs.netlify.app/docs/shortcodes/img/

**Comment by hoontaeklee** [comment]
감사합니다! 그게 캡션이었군요.
게다가 img shortcode를 사용한 것들은 caption을 지정하기 전에도 이미 주소가 %ADF124%숫자%알파벳% 등.. 으로 길지 않고 제가 아는 경로대로 간략하게 나오네요.
