### ISSUE TITLE
The Cat

### ISSUE THREAD

**Issue by MarkJThomas** [zzossig/hugo-theme-zzo#305]
Hi, thanks for the amazing theme, however, I can't seem to replace the image of the cat, I amended the author.md file in archetypes but the image never changes

All the best!
Mark

**Comment by zzossig** [comment]
You can replace the cat image.
Make a folder at `root/static/images/whoami` and then put your image there. Your image filename should be `avatar`.(jpg or png)

You can set image URL or can use gravatar. Those params are `bioImageUrl` and `useGravatar`. Search them in the READEM.md file

**Comment by rahatzamancse** [comment]
I do not know if I should create a new issue for this, but is there any way to change the whoami names for other languages? I can see that it is static for all the languages as set from the config.toml only
