### ISSUE TITLE
打开baiduAnalytics后出错

### ISSUE THREAD

**Issue by Codeapes666** [zzossig/hugo-theme-zzo#31]
我发现在params.toml启用baiduAnalytics后会出现下面的错误：

 GET https://hm.baidu.com/hm.js?************************************** 

net::ERR_SSL_PROTOCOL_ERROR

说明：这个错误会在google中出现

**Comment by zzossig** [comment]
I think this issue is related more to your web hosting service. You have to search more on this. I have tested it locally but works well on my end. I don't think I can do something for this.
我认为这个问题与您的网络托管服务更多有关。您必须对此进行更多搜索。我已经在本地测试了BaiduAnalytics，但效果很好。

**Comment by Codeapes666** [comment]
ok
