### ISSUE TITLE
Archive page shows error when there are 0 posts

### ISSUE THREAD

**Issue by ArjitS1** [zzossig/hugo-theme-zzo#314]
Hello I am relatively new to open source ,excuse me for any mistakes
I noticed when I deleted all posts or were set in draft mode 
Archive pages was showing error. 
_layouts/archive/list.html_
I looked into the code and all I could take away was  `range .Pages` was showing error
So I assumed that when there were 0 pages after filtering it shows error
When I added some pages there was no error
Thank you

**Comment by firmart** [comment]
Same issue. The error message is precisely

```shell
ERROR 2020/09/11 10:42:31 Rebuild failed:

ERROR 2020/09/11 10:42:31 Failed to render pages: render of "section" failed: 
"/path/to/themes/zzo/layouts/archive/list.html:21:25": execute of template failed: template: archive/list.html:21:25: executing 
"main" at <($paginator).PageGroups>: error calling PageGroups: runtime error: invalid memory address or nil pointer dereference
```
