### ISSUE TITLE
Optinal position of search box, language selector, social buttons

### ISSUE THREAD

**Issue by AndreyAkinshin** [zzossig/hugo-theme-zzo#317]
I want to keep the search box, the language selector, and the social buttons on the top navbar as in [zzoDocs](https://github.com/zzossig/zzoDocs):
![image](https://user-images.githubusercontent.com/2259237/90170326-90b13c00-dda8-11ea-8d6a-f31c26f9128f.png)
It would be awesome to have such an option in `params.toml`.

**Comment by zzossig** [comment]
Update the theme first.
You can set params in `params.toml`
- appbarSearchIcon = true
- appbarLangIcon = true

I didn't make a social button because I don't think it's necessary

**Comment by rahatzamancse** [comment]
I there any way to move the search icon and language icon to the right of the navigation menu?
