### ISSUE TITLE
RSS link on main page is broken

### ISSUE THREAD

**Issue by VictorZakharov** [zzossig/hugo-theme-zzo#318]
Site: https://www.neolisk.blog/

RSS link looks like this (incorrect): https://index.xml/.
Correct link should be: https://www.neolisk.blog/index.xml.

Only broken on the main page, other pages are fine.

I tried the following baseUrls:
```
baseURL = "/"
baseURL = ""
```

Same result. I cannot hard code domain name in there, because then it would not work in the staging environment. Also HTTP/HTTPS should be resolved automatically, and not hard coded in baseUrl. Please advise if this was recently fixed, I haven't updated for a few months.

**Comment by szpak** [comment]
Set `baseURL` to your production domain and on the staging environment you can use `-b` to override it.

E.g. (for Netlify): `-b $DEPLOY_PRIME_URL`

**Comment by VictorZakharov** [comment]
@szpak I did, it doesn't work.
```
baseURL = "https://www.neolisk.blog/"
```
Then on my staging all URLs navigate me away. Staging lives under *.netlify.app.

netlify.toml:
```
[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
```

**Comment by szpak** [comment]
Strange. I have followed the [official guide](https://gohugo.io/hosting-and-deployment/hosting-on-netlify/) and I had no problem at all. `https://preview--xxx.netlify.app/` works (`baseURL` is set to my production domain). I have no idea why it's broken in your case.

Sure, it would be good to automatically resolve it, but the links are resolved at the build time, so it might be tricky.

**Comment by VictorZakharov** [comment]
I changed my `links-feed.html` in `layout/partials/footer` to this:

```
{{ if $.Param "showFeedLinks" }}
  {{ if not (in ($.Param "notAllowedTypesInHomeFeed") .Type) }}
  {{ $exclude := slice "tags" "series" "categories" }}    
    <a href="/index.xml" type="application/rss+xml" title="RSS" aria-label="RSS Feed Link">
      {{ partial "svgs/etc/rss.svg" (dict "width" 32 "height" 32) }}
    </a> 
  {{ end }}
{{ end }}
```

Basically constant RSS page regardless of where user is located. It works for me, I only have a single posts collection.

@szpak

**Comment by zzossig** [comment]
@VictorZakharov
If it worked, then I think we can close this issue.
I don't know much about Netlify.
@szpak Thanks for the comments
