### ISSUE TITLE
Add Contact form page

### ISSUE THREAD

**Issue by Lemania** [zzossig/hugo-theme-zzo#32]
Hi, 
Would it be possible adding a contact form using formspree.io like the quick-start theme ? 

https://themes.gohugo.io/gohugo-theme-ananke/

Thanks
Best regards
Seb

**Comment by zzossig** [comment]
Ok. I'll give it a try.
It maybe looks like this
![cc](https://user-images.githubusercontent.com/52706977/71005831-b3ab2380-2127-11ea-9fe0-46a3218e8267.png)
Sorry for horrible picture

**Comment by Lemania** [comment]
yes that's exactly it, thank you very much

**Comment by zzossig** [comment]
@Lemania I updated [readme](https://github.com/zzossig/hugo-theme-zzo#contact-page) file.
Update the Zzo theme first, and then follow the instructions in the readme.
I didn't test it, because I didn't join the Formspree site. 
If it's not working, tell me.

**Comment by Lemania** [comment]
It Works ! 

Thanks a lot :)
