### ISSUE TITLE
$theme-map: null   Error Hugo v0.75

### ISSUE THREAD

**Issue by craigccfl** [zzossig/hugo-theme-zzo#323]
Getting the following error during Hugo loading

themes/zzo/assets/sass/abstracts/_mixins.scss:
!global assignments won't be able to declare new variables in future versions.
Consider adding `$theme-map: null` at the top level.

It's not breaking anything

**Comment by zzossig** [comment]
No, it's breaking everything.
Just leave it as is. It is not harmful.
It seems the warning message is because Hugo updated the LibSASS to the newest one.
https://github.com/gohugoio/hugo/issues/7138#issuecomment-692481772

**Comment by zzossig** [comment]
Yes, you were right. I fixed it as you recommended.
