### ISSUE TITLE
any plans to add subtitle?

### ISSUE THREAD

**Issue by icf20** [zzossig/hugo-theme-zzo#327]
is this a planed feature?

_i dont really want to modify the template then to get all mixed after a update_

**Comment by zzossig** [comment]
What do you mean by the subtitle? What feature!

**Comment by zzossig** [comment]
I don't understand what you mean. Sorry

**Comment by icf20** [comment]
here https://en.wikipedia.org/wiki/Subtitle_(titling)

**Comment by icf20** [comment]
@zzossig  also dont close issue if u dotn understand .Site.Params.subtitle have some patience for few days dont be so trigger happy
