### ISSUE TITLE
A handy way of applying a logo icon with one SVG file.

### ISSUE THREAD

**Issue by Lemania** [zzossig/hugo-theme-zzo#33]
HI,

Would it be possible to use only one overridable logo.svg file ?

it could also be used for the icon

for the moment I have replaced it in :
themes\zzo\layouts\partials\navbar\site-nav.html

thanks

**Comment by zzossig** [comment]
I don't understand clearly what you mean. 
Do you want to use an svg file instead of a png file?

**Comment by Lemania** [comment]
yes only one svg file which would serve as logo for any size, and also favicon

a file could place out of the theme, which we cannot today

**Comment by Lemania** [comment]
after these two issues, your theme will be perfect :)

**Comment by zzossig** [comment]
As for the favicon, It's not in my code. Hugo controls the favicon. If you put your favicon.ico file in your root/static folder, it should work. So, I think you should generate your favicon.ico file.
And, if you want to use an svg file for the logo, I recommend you to override Zzo theme's partial folder.
In your case, make file at root/layouts/partials/navbar/site-nav.html and then copy-paste code from 
themes\zzo\layouts\partials\navbar\site-nav.html
and then edit the file name as you want. You got it?

**Comment by zzossig** [comment]
Hey~, I have searched what you requested. I found that there is no magical way to serve logo icons with just one SVG file. I have added the feature to use logo.svg file as a favicon, but not all browsers would support the SVG file. I have tested it in Chrome, Firefox, but Chrome doesn't seem to support it.

You should see [this article](https://stackoverflow.com/a/48969053/11747951) for more detailed information. - The one-size-fits-all myth

[SVG favicon supported browser](https://caniuse.com/#feat=link-icon-svg)

As to the navbar logo, If you want to use logo.svg file, you should override or edit directly the navbar.html file as I explained above.

**Comment by Lemania** [comment]
Thanks, I overide navbar.html for the moment
