### ISSUE TITLE
Unable to locate Config file.....

### ISSUE THREAD

**Issue by brinst07** [zzossig/hugo-theme-zzo#333]
안녕하세요?
zzo theme으로 개발블로그를 구축하고 잘 사용하고 있다가, 포맷을 하는 바람에 깃 clone을 받아서 실행을 해보려고했으나,

![image](https://user-images.githubusercontent.com/60083557/96542612-71b9b380-12dd-11eb-9de8-61b906152470.png)

다음과 같은 에러가 발생하고 있습니다....

config 폴더를 examplesite 안에있는 config 파일들로 붙여넣어도 같은 현상이 발생되고 있습니다.

또한 zzossig님의 블로그는 검색기능이 활성화 되어있는데 제 블로그는 활성되지 않더군요.

혹시 그 방법도 가르쳐주시면 정말 감사하겠습니다...

좋은하루되세요 ^^

**Comment by zzossig** [comment]
로컬환경에서 안된다는건가요?
이미지에 보이는 바로는 public 폴더에서 `hugo server` 명령어를 입력하셨는데
프로젝트의 root 폴더에서 명령어 입력하셔야합니다.

검색은
config.toml 파일에서
```config.toml
defaultContentLanguageInSubdir = false
```
설정 해주시고 
```config.toml
baseURL = "https://brinst07.github.io"
```
해주시면 될거같아요

**Comment by brinst07** [comment]
로컬환경에서 안되고 예전에 올려놓은 사이트는 정상적으로 구동이 되고 있습니다.

![image](https://user-images.githubusercontent.com/60083557/96547937-eabe0880-12e7-11eb-9fc4-e48b03f8b9e7.png)

root폴더에서도 config 파일을 찾을 수 없다고 하면서 에러가 발생하네요....

**Comment by zzossig** [comment]
이것만 봐서는 뭐가 문제인지 알 수 없네요.
clone 받아서 실행한다는게, 현재 이 레포지토리를 받아서 그걸 root 폴더로 사용한다는건가요?
이 레포지토리는 
```bash
hugo new site mysite
```
로 사이트를 만든 후에
```
mysite/themes/zzo
```
폴더를 만드시고 `zzo` 폴더에 넣으셔야 하는데요

http://localhost:1313/zzo/gettingstarted/quickstart/ 참고하셔요

**Comment by brinst07** [comment]
원래 잘 구동이 되었는데, 포맷을 하고 난 뒤
제가 원래 만들어 놓은 blog 레파지토리와 public 레파지토리를 clone 받아서 사용하려고 했었습니다.
그럼 이런 상황에서는 ```hugo new ~~``` 로 만드는 수밖에 없는건가요??

**Comment by zzossig** [comment]
public 폴더는 `hugo` 명령어를 치면 자동으로 생성되는 폴더인데, 그걸 clone 해서 다시 사용 할 필요가 없을거 같아요.
일단 `hugo new ~~` 로 새 프로젝트 만드시고
기존에 만들어 놓은 프로젝트에서 root 디렉토리의 content, static, config 폴더 정도만 새 프로젝트 루트에 복사하시고
root/themes/zzo 폴더에 이 레포지토리를 풀어 넣으시면 될거같아요

**Comment by brinst07** [comment]
아 이해했습니다... ㅎㅎ
도움주셔서 정말 감사합니다!

좋은하루 보내세요^^
