### ISSUE TITLE
Failed to get JSON resource

### ISSUE THREAD

**Issue by odunayo12** [zzossig/hugo-theme-zzo#342]
Hello @zzossig , thanks for the good and free job. I followed the [installation guide](https://zzo-docs.vercel.app/zzo/gettingstarted/installation/), cd'd to `themes/zzo/exampleSite` and ran  `hugo server --themesDir ../..` as displayed. The following was what was the response

![image](https://user-images.githubusercontent.com/19196838/97921946-fab00080-1d5b-11eb-89ff-1570f48c1cb1.png)

and on clicking on the link in the logged error, I got:

![image](https://user-images.githubusercontent.com/19196838/97923167-dc4b0480-1d5d-11eb-8f39-a699c37049cc.png)

Please, your assistance or advice is well appreciated in advance.

**Comment by SathyaBhat** [comment]
See #339 tldr; Instagram changed their API and Hugo will need an update (prolly remove /move the instagram shortcode to a plugin).

**Comment by odunayo12** [comment]
Thanks. Deleted the Instagram shortcode in `content/en/posts/rich-content.md` according to #339 and that was it.

**Comment by odunayo12** [comment]
Thanks. Deleted the Instagram shortcode in `content/en/posts/rich-content.md` according to #339 and that was it.
