### ISSUE TITLE
how can I use image on internet?

### ISSUE THREAD

**Issue by zhongfly** [zzossig/hugo-theme-zzo#343]
I try to use image url in post like this:
`{{< img src="https://i.loli.net/2020/11/03/h7ACPlKRJG2yONz.png" >}}`
but it faild,image didn't show in website.
so I realy want to kown how to use image url in this theme.

**Comment by zzossig** [comment]
Use markdown syntax
https://www.markdownguide.org/basic-syntax/#images
Or make your own shortcode for the URL-image.
The `img` shortcode supported in this theme is for local images
