### ISSUE TITLE
Could you please add a normal page archetype?

### ISSUE THREAD

**Issue by zu1k** [zzossig/hugo-theme-zzo#345]
I want to create a normal page with title wrapping like about page. When I set the page type to 'about', the style of table in the page is different from which in a post. Could you please add a archetype for normal page, with title wrapping and post style?

**Comment by zzossig** [comment]
This issue fixed in d694f16
Update the theme first and use page type 'about'.
This should be fine now

**Comment by zu1k** [comment]
Thanks for your quick response, the problem has been solved perfectly. Thank you!
