### ISSUE TITLE
img src shortcode - works on localhost, not when deployed to gitlab pages

### ISSUE THREAD

**Issue by tangodev** [zzossig/hugo-theme-zzo#347]
# issue description

When working on a blog post I've noticed, that not all images are displayed.

## desired behavior

Images added with `{{ <img src >}}` short-code should be displayed.

## actual behavior

Images added with `{{ <img src >}}` short-code are not displayed.

![hugo-zzo-theme-img-shortcode-tshooting-m](https://user-images.githubusercontent.com/12778629/98462629-fbaabd00-21b5-11eb-82a9-ea92047ab7f5.png)

### featuredImage

Works! Generated URL is `http://localhost:1313/HUGO_INSTANCE_NAME/images/stock/pixabay/solar-eclipse-2684387_640.jpg`

### img src
Works! Generated URL is `http://localhost:1313/HUGO_INSTANCE_NAME/images/stock/pixabay/solar-eclipse-2684387_640.jpg`

### featuredImage

Works! Generated URL is `https://tangodelta.gitlab.io/cabbage/images/stock/pixabay/solar-eclipse-2684387_640.jpg`

### img src

Broken. Generated URL is `https://tangodelta.gitlab.io/images/stock/pixabay/solar-eclipse-2684387_640.jpg`

The second URL is missing one segment after the end of the domain. This isn't IMHO because of me dynamically changing the baseURL during build with `hugo --baseURL foo`. I think this because all other image URLs are OK.

I'm following this piece of documentation: https://zzo-docs.vercel.app/zzo/shortcodes/img/

### blog post file
```
---
[truncated]
image: "images/stock/pixabay/solar-eclipse-2684387_640.jpg"
---

[truncated]
{{< featuredImage >}}

{{< img src="/images/stock/pixabay/solar-eclipse-2684387_640.jpg" title="A solar eclipse" caption="Image courtesy of AmyBingham6 from Pixabay.com" alt="A solar eclipse" width="700px" position="center" >}}
```

### static content location

```
HUGO_ROOT_FOLDER/static/images/stock/pixabay/solar-eclipse-2684387_640.jpg
```

**Comment by pastalian** [comment]
I couldn't reproduce this issue. I just cloned master and made some settings (baseURL, defaultContentLanguageInSubdir, contentdir).
@tangodev Are you using master / latest hugo image?

![20-11-10_224447](https://user-images.githubusercontent.com/28638872/98682508-59522b80-23a7-11eb-9976-0aa78558af02.jpg)

**Comment by tangodev** [comment]
## hugo versions

On desktop I'm using:
```
hugo version
Hugo Static Site Generator v0.78.1/extended linux/amd64 BuildDate: 2020-11-05T14:07:22Z
```

On gitlab I'm using their container image:
```
$ hugo version
30Hugo Static Site Generator v0.78.1-347F2DE6/extended linux/amd64 BuildDate: 2020-11-05T09:47:54Z
```

## my setup

Maybe I did something with my configuration that broke the theme? I used to use this in my `config.toml`:
```
baseURL = "https://tangodelta.gitlab.io/HUGO_INSTANCE_NAME"
```

I'd then update this with `sed`. But I moved to passing the baseURL on build time with the `--baseURL` flag. I just commented out the above mentioned line from `config.toml` and left this one:
```
baseURL = ""
```

This is how I'm building my sites (`gitlab-ci.yml`):
```
    - hugo --baseURL "https://tangodelta.gitlab.io/$HUGO_INSTANCE_NAME" --verbose
```

GitLab CI injects the desired variable.

The full raw run from gitlab:
```
[0KRunning with gitlab-runner 13.5.0 (ece86343)
[0;m[0K  on docker-auto-scale fa6cab46
[0;msection_start:1605101195:prepare_executor
[0K[0K[36;1mPreparing the "docker+machine" executor[0;m
[0;m[0KUsing Docker executor with image registry.gitlab.com/pages/hugo/hugo_extended:latest ...
[0;m[0KAuthenticating with credentials from job payload (GitLab Registry)
[0;m[0KPulling docker image registry.gitlab.com/pages/hugo/hugo_extended:latest ...
[0;m[0KUsing docker image sha256:5133a8a0541195d9e6f51aff00f4c258a071b86f105a541d2ad1719de40a914d for registry.gitlab.com/pages/hugo/hugo_extended:latest with digest registry.gitlab.com/pages/hugo/hugo_extended@sha256:c26c3f1b72ef10db4556e56c967adb3d09faee7c77e1aa99db0f1269022b9abd ...
[0;msection_end:1605101209:prepare_executor
[0Ksection_start:1605101209:prepare_script
[0K[0K[36;1mPreparing environment[0;m
[0;mRunning on runner-fa6cab46-project-22382438-concurrent-0 via runner-fa6cab46-srm-1605101151-f8b4aa22...
section_end:1605101210:prepare_script
[0Ksection_start:1605101210:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m
[0;m[32;1m$ eval "$CI_PRE_CLONE_SCRIPT"[0;m
[32;1mFetching changes with git depth set to 50...[0;m
Initialized empty Git repository in /builds/tangodelta/donut/.git/
[32;1mCreated fresh repository.[0;m
[32;1mChecking out 0151c18f as donut...[0;m

[32;1mUpdating/initializing submodules recursively...[0;m
Submodule 'themes/zzo' (https://github.com/zzossig/hugo-theme-zzo.git) registered for path 'themes/zzo'
Cloning into '/builds/tangodelta/donut/themes/zzo'...
Submodule path 'themes/zzo': checked out '200be8c310fad13c57af7cb4b7515e21b128542d'
Entering 'themes/zzo'
section_end:1605101213:get_sources
[0Ksection_start:1605101213:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m
[0;m[32;1m$ echo $HUGO_INSTANCE_NAME[0;m
donut
[32;1m$ echo $CI_COMMIT_BRANCH[0;m
donut
[32;1m$ hugo version[0;m
Hugo Static Site Generator v0.78.1-347F2DE6/extended linux/amd64 BuildDate: 2020-11-05T09:47:54Z
[32;1m$ hugo --baseURL "https://tangodelta.gitlab.io/$HUGO_INSTANCE_NAME" --verbose[0;m
INFO 2020/11/11 13:26:54 Using config file: 
Start building sites â€¦ 
INFO 2020/11/11 13:26:54 syncing static files to /builds/tangodelta/donut/public/
INFO 2020/11/11 13:26:54 Data for key 'title_font' in path 'font.toml' is overridden by higher precedence data already in the data tree
INFO 2020/11/11 13:26:54 Data for key 'content_font' in path 'font.toml' is overridden by higher precedence data already in the data tree

                   | KO  | EN   
-------------------+-----+------
  Pages            |  16 |  64  
  Paginator pages  |   0 |   0  
  Non-page files   |   0 |   3  
  Static files     | 136 | 136  
  Processed images |   0 |   0  
  Aliases          |   3 |  17  
  Sitemaps         |   2 |   1  
  Cleaned          |   0 |   0  

Total in 6171 ms
section_end:1605101220:step_script
[0Ksection_start:1605101220:upload_artifacts_on_success
[0K[0K[36;1mUploading artifacts for successful job[0;m
[0;m[32;1mUploading artifacts...[0;m
public: found 354 matching files and directories  [0;m 
Uploading artifacts as "archive" to coordinator... ok[0;m  id[0;m=843295715 responseStatus[0;m=201 Created token[0;m=[REDACTED]
section_end:1605101222:upload_artifacts_on_success
[0Ksection_start:1605101222:cleanup_file_variables
[0K[0K[36;1mCleaning up file based variables[0;m
[0;msection_end:1605101223:cleanup_file_variables
[0K[32;1mJob succeeded
[0;m
```


### local configuration

#### directory contents

```
td@emerald:~/devel/website-0.2.0-alpha$ ll
total 68
drwxrwxr-x 12 td td 4096 lis 10 14:20 ./
drwxrwxr-x 18 td td 4096 lis  6 20:48 ../
drwxrwxr-x  2 td td 4096 lis  7 20:32 archetypes/
drwxrwxr-x  4 td td 4096 lis 10 14:20 assets/
drwxrwxr-x  3 td td 4096 paź 30 20:46 config/
-rw-rw-r--  1 td td   83 lis  1 14:15 config.toml
drwxrwxr-x  3 td td 4096 paź 30 20:54 content/
drwxrwxr-x  2 td td 4096 lis 10 14:20 data/
drwxrwxr-x  9 td td 4096 lis 11 14:40 .git/
-rw-rw-r--  1 td td   20 lis  1 14:57 .gitignore
-rw-rw-r--  1 td td 1256 lis 10 14:20 .gitlab-ci.yml
-rw-rw-r--  1 td td   97 paź 30 20:46 .gitmodules
drwxrwxr-x  2 td td 4096 paź 30 20:45 layouts/
drwxrwxr-x  3 td td 4096 paź 30 20:46 resources/
-rwxrwxr-x  1 td td  713 paź 30 20:48 r-switch.sh*
drwxrwxr-x  6 td td 4096 lis 10 14:20 static/
drwxrwxr-x  3 td td 4096 paź 30 20:45 themes/
```

#### git

Are those generated assets in `_gen` important here?
```
git status
On branch donut
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
        modified:   resources/_gen/assets/scss/hugo_instance_name/sass/main.scss_b4f67ac5085b89b62b54c1923e5a9145.content
        modified:   themes/zzo (modified content, untracked content)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        resources/_gen/assets/css/
        static/images/stock/pixabay/silo-2684340_640.jpg

no changes added to commit (use "git add" and/or "git commit -a")
```

The reason for why my setup is like this is because **gitlab ci uses a container to build the website and pulls the latest upstream version of zzo from github. All my customizations have to be outside of the submodule. Once the artifacts are built and pushed to  hosing, the container implodes**.

What you wrote intrigued me @pastalian : what did you set in baseURL, defaultContentLanguageInSubdir and contentdir?

**Comment by pastalian** [comment]
Have you tried this with a clean master repo?
It seems like you're overwriting the theme quite a bit, so that may be affecting it.

> Are those generated assets in _gen important here?

I don't know exactly how hugo works but I think you should either add `_gen` to .gitignore or add the latest locally generated one to the repository (no old files). It shouldn't affect the raw html though.

> what did you set in baseURL, defaultContentLanguageInSubdir and contentdir?

config.toml
```
baseURL = "https://pastalian.gitlab.io/cabbage/"
defaultContentLanguageInSubdir = false
```
languages.toml
```
[en]
  #contentdir = "content/en"  # default: "content"
```
I did this language setting becasuse I thought you were doing it too, but it wouldn't matter much either.

**Comment by tangodev** [comment]
I prepared a fresh, clean repo to help with troubleshooting.

https://tangodelta.gitlab.io/clean/en/posts/my-thoughts-on-eclipse-and-what-happens-next/

![zzo-theme-img-tshoot-clean-install](https://user-images.githubusercontent.com/12778629/99145714-5ab67900-2671-11eb-911a-01731f43907c.png)

Steps:

1. Created fresh hugo site
1. Installed zzo theme via git submodule
1. Copied my blog post from the website I'm working on
1. Added the image to static/image/stock

I've added you @pastalian as a guest to the `clean` repo, so you can see the code. There's very little in terms of changes, so either it's a bug, or I'm doing something unsupported.

**Comment by zzossig** [comment]
It seems like a bug.
This happened because you are using a subdomain.
I'll fix it soon

**Comment by zzossig** [comment]
@tangodev 
Can you update the theme and check again?

**Comment by tangodev** [comment]
**Works!**

```
Submodule 'themes/zzo' (https://github.com/zzossig/hugo-theme-zzo.git) registered for path 'themes/zzo'
20Cloning into '/builds/tangodelta/clean/themes/zzo'...
21Submodule path 'themes/zzo': checked out '9a5a692aabea0609387d3d6b11347011a526a0a0'
22Entering 'themes/zzo'
```

![zzo-img-works](https://user-images.githubusercontent.com/12778629/99150958-24402480-2698-11eb-937a-9c1dbb6b6d16.png)

Thank you! :)

**Comment by pastalian** [comment]
Hmm... I don't know why the bug didn't occur to me, but glad it was fixed!
