### ISSUE TITLE
Changing site title from config.toml didn't work

### ISSUE THREAD

**Issue by rizkyzhang** [zzossig/hugo-theme-zzo#348]
I try to change the default site title "Hugo Zzo Theme" to my own multiple times by setting the title variable inside config.toml, but it still didn't change. Any help would be appreciated.

**Comment by zzossig** [comment]
Did you try to change it in languages.toml file?
https://github.com/zzossig/hugo-theme-zzo/blob/0d433124fe4a9fd781f383fe33a2c18979d9ba1e/exampleSite/config/_default/languages.toml#L2

**Comment by rizkyzhang** [comment]
I just figured it out, instead of setting it from config.toml, I set it from languages.toml.
