### ISSUE TITLE
Add article update time

### ISSUE THREAD

**Issue by fandean** [zzossig/hugo-theme-zzo#35]
Please add the update time of the article, Consider the following ways
![mkcert05](https://user-images.githubusercontent.com/25637720/71408600-c7034500-2679-11ea-8002-45b2eabd2dd8.gif)

You can refer to this link <https://gohugo.io/variables/git/#lastmod>

**Comment by zzossig** [comment]
Hi,
I think it’s a good feature! I’ll make it soon after I got home

**Comment by fandean** [comment]
Merry Christmas Eve 😀

**Comment by zzossig** [comment]
What are you doing on Christmas Eve! Go out dating😤

**Comment by fandean** [comment]
I'm waiting for you to update 😂😂

**Comment by zzossig** [comment]
😂 Ok~ 
I want to know if this is what you are asking for?
![주석 2019-12-24 220359](https://user-images.githubusercontent.com/52706977/71414277-8287a180-2699-11ea-8d60-28d84bde23d6.png)

**Comment by fandean** [comment]
I think this will lead to a bad end mobile display

**Comment by zzossig** [comment]
I considered the mobile view. You can check it locally I committed now

**Comment by fandean** [comment]
By the way, change `min read` to  `{{ i18n "reading-time" }}`

**Comment by zzossig** [comment]
OMG, you are right! How about update time? It's what you are expected?

**Comment by fandean** [comment]
I think it's better to call 分钟 directly

**Comment by zzossig** [comment]
@fandean Updated just now! tell me if something wrong

**Comment by fandean** [comment]
Is the update time set like this?
config.toml
```
enableGitInfo = true
```
Front Matter
```
lastmod: [':git',':fileModTime', ':default']
```
But it doesn't show

**Comment by zzossig** [comment]
@fandean Wait I have more update for you

**Comment by fandean** [comment]
I've added it to front matter in most articles 😂

**Comment by zzossig** [comment]
Now, I'm figuring out how to solve this error. This error makes the search not working.
![주석 2019-12-24 235053](https://user-images.githubusercontent.com/52706977/71417352-3e4fcd80-26a8-11ea-970d-16a4ddf2da8f.png)

**Comment by fandean** [comment]
I was going to ask you about this

**Comment by zzossig** [comment]
@fandean I fixed it! One more update please~

**Comment by zzossig** [comment]
@fandean Can you give me a hint for translating this.
```toml
[contact-name]
other = "Name"

[contact-email]
other = "Email"

[contact-message]
other = "Message"

[contact-send]
other = "Send"
```

**Comment by fandean** [comment]
OK

But the update time is still not displayed

**Comment by zzossig** [comment]
Not a cache problem I think. The update time is not displayed even on your local environment?

**Comment by fandean** [comment]
In the local environment, only a small number of articles show the update time normally, while in the production environment, another small number of articles show the update time and all at the same time, but this is a wrong time

My hugo site host on Render

**Comment by zzossig** [comment]
I suspect that there is no git modified date history exist

**Comment by fandean** [comment]
You are right, I did not find the corresponding file change history, why did this happen?I'm confused

**Comment by zzossig** [comment]
One possible story is that you copy-pasted your content files from your notes repository and your copy-pasted files are not modified yet. So this happened maybe. But I'm not sure.

**Comment by fandean** [comment]
When I open this repository using git GUI, I am prompted as follows.
![image](https://user-images.githubusercontent.com/25637720/71446389-a6142000-275d-11ea-866d-e4be690fa3ad.png)

And one of the files has the following prompt.
![image](https://user-images.githubusercontent.com/25637720/71446392-b0ceb500-275d-11ea-9e45-63b445366cde.png)

After I re-cloned the remote repository to another local directory, the update times in the local environment appeared normal. However, this issue has not been resolved in Render, I think the reason is that the final `public` directory was generated in Render , not locally

**Comment by zzossig** [comment]
You said that the last modified time not displayed or incorrect time is displayed even in your local environment. Is it still like so? Before we suspect the Render behavior, we should fix this issue in the local environment.

**Comment by fandean** [comment]
This sentence may not be translated well. It's OK in the local environment

**Comment by zzossig** [comment]
I think we need to set some variables in the hosting service config file.
For example, I use Zeit now for hosting my blog and I have now.json config file in my blog repo.
Netlify also has a config file named netlify.toml

So, maybe there is a config param exist that we don't know currently and that can solve this issue.
I'll ask about this on the Hugo community.

**Comment by fandean** [comment]
thank you
Render has a configuration file called render.yaml, but I don't know how to use it yet

**Comment by zzossig** [comment]
I believe the git-info feature is not supported in Render.
And any other hosting service seems to support git-info except Netlify.
Netlify has a config param named `HUGO_ENABLEGITINFO`

**Comment by zzossig** [comment]
Hey~ @fandean 
I just confirmed that Netlify is the only option for using the `enableGitInfo` feature.
this is the config file that I use 
`netlify.toml`
```toml
[context.production.environment]
  HUGO_VERSION = "0.62.1"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[build]
  publish = "public"
  command = "hugo --gc --minify"
```

We can close this issue now. You can move the hosting service to Netlify or waiting Render to update for the `enableGitInfo` feature
![netlify](https://user-images.githubusercontent.com/52706977/71655227-3d3e3080-2d79-11ea-9d3f-d1111e305f10.png)

**Comment by zzossig** [comment]
@fandean Hello~
I just got an email from the Render team.
They said that just set the `enableGitInfo` param to `true` and no more need to setup.
If you set the `enableGitInfo` to true and still get in trouble, it may be your git repo is something wrong.
