### ISSUE TITLE
Error building site: render of "404" failed: execute of template failed:

### ISSUE THREAD

**Issue by odunayo12** [zzossig/hugo-theme-zzo#357]
@zzossig @bep Having explored all online answers to this issue and raising it [here](https://github.com/zzossig/hugo-theme-zzo/issues/197#issuecomment-727542340) without response, nothing seems to work still. 

I have downgraded and upgraded to many version and have decided to stick with version `0.78.2/extended`. It is so frustrating. My work has been halted for more than 2 weeks. 

Kindly find attached the error log when I run `hugo` or `hugo server` from the root directory of my project. Thanks

![image](https://user-images.githubusercontent.com/19196838/100480491-b5c88100-30f1-11eb-804e-41f1a09cafdf.png)

**Comment by zzossig** [comment]
Can I check your repository?
I can't reproduce this issue on my end.
Your blog repository link would be appreciated

**Comment by odunayo12** [comment]
I have sent you an invite since it is a private repo. Kindly verify that you have gotten it. Thanks

**Comment by zzossig** [comment]
Exclude me from your private repository since the issue solved now

**Comment by odunayo12** [comment]
I message d you, please respond before you go. Thanks.
