### ISSUE TITLE
Pages are listed on summary page

### ISSUE THREAD

**Issue by ironcladmerc** [zzossig/hugo-theme-zzo#36]
Are the menu pages (contact, archive, about) supposed to be listed on the summary page (aka home page)? It would be better if they were not listed, the summary page should just be a list of blog posts.

**Comment by zzossig** [comment]
It's Hugo's default behavior.
Ok, I agree with you. It's better not listed on the summary page.

**Comment by zzossig** [comment]
@ironcladmerc I fixed it.

**Comment by kvandenbrande** [comment]
> @ironcladmerc I fixed it.

How did you fix this?

**Comment by zzossig** [comment]
Your params.toml file
```toml
...
notAllowedTypesInHome = ["contact", "talks", "about"] 
...
```
You can find this on the doc
