### ISSUE TITLE
Responsiveness issue

### ISSUE THREAD

**Issue by ohidurbappy** [zzossig/hugo-theme-zzo#362]
When the ToC is too long, it overlaps the footer. It's not scrollable.
Live: https://www.ohidur.com/posts/free-developer-resources/

![toc-not-responsive](https://user-images.githubusercontent.com/22405409/101282156-97ebd200-37fd-11eb-8f15-35d7b92e5d50.png)

**Comment by zzossig** [comment]
fixed in 621c83a
