### ISSUE TITLE
The anchor behind the title gives wrong url link when we click it.

### ISSUE THREAD

**Issue by Delta-in-hub** [zzossig/hugo-theme-zzo#369]
![Snipaste_2020-12-11_14_36_27](https://user-images.githubusercontent.com/53047182/101872528-5b82f200-3bc0-11eb-913e-b717261be6a4.jpg)

It gives the url `https://www.deltablog.xyz/posts/%25E6%25AD%25A3%25E5%2588%2599%25E8%25A1%25A8%25E8%25BE%25BE%25E5%25BC%258F/#正则表达式-in-c11`,but that is wrong which leads to `404 Page` . There are too many `%25` in the url.
The correct should be `https://www.deltablog.xyz/posts/%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F/#正则表达式-in-c11`

**Comment by Delta-in-hub** [comment]
I found that is because the filename of `root/content/posts` is Chinese and If I change the filename to English characters, this bug will not appear, it will give the correct url.

But how could we fix it when we use Chinese filename?

**Comment by zzossig** [comment]
Fixed in 290800d
Update the theme and all should be fine

**Comment by Delta-in-hub** [comment]
> Fixed in [290800d](https://github.com/zzossig/hugo-theme-zzo/commit/290800d19a793d00808910cfaa3d9ec5eeff39e5)
> Update the theme and all should be fine

Thanks for your working! Have a nice day!
