### ISSUE TITLE
Changelog in new zzo-docs?

### ISSUE THREAD

**Issue by szpak** [zzossig/hugo-theme-zzo#371]
I've come back some time to update the theme on my blog, but I had a problem to find what new features/incompatible changes were introduced and what should I adjust in the configuration.

In [this commit](https://github.com/zzossig/hugo-theme-zzo/commit/f09f6d8a1e51151cd63a26d9682c1ecadaa044db#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) you seemed to remove information about new features from README. I visited https://zzo-docs.vercel.app/zzo , but I wasn't able to find there some kind of changelog.

I wonder is there any better way right now to get know about new things than dig up the commits looking for the `[new feature]` tag?

**Comment by zzossig** [comment]
I'll update the doc this weekend

**Comment by zzossig** [comment]
I added change log page in the document
https://zzo-docs.vercel.app/zzo/changelog/
Actually, nothing much added.
I omitted minimal fixes.

**Comment by szpak** [comment]
Thanks @zzossig!

Reading that, I've come across the Netlify Forms support, which I didn't know before.
