### ISSUE TITLE
layout go wrong when theres a long line in code block 

### ISSUE THREAD

**Issue by m9810223** [zzossig/hugo-theme-zzo#373]
![Screenshot_20201218-091824_Chrome](https://user-images.githubusercontent.com/39259397/102562467-199f0200-4112-11eb-9346-150dbc351eff.jpg)
that line is long and no space

**Comment by zzossig** [comment]
This is not a bug.
You should search for closed issues.
Quick answer: Add space to the content.
Or, add your custom css
```CSS
word-wrap: break-all;
```

**Comment by m9810223** [comment]
# I try it today,  but got ERROR
---
## first time

### `config\_default\params.toml`
`custom_css = ["css/custom.css"]`

### `assets\css\custom.css`
`code { word-wrap: break-all; }`


### error msg
```
Change of config file detected, rebuilding site.
2020-12-23 15:38:24.038 +0800
ERROR 2020/12/23 15:38:24 TOCSS: failed to transform "css/custom.css" (text/css): resource "css/css/custom.css_b95b077eb505d5c0aff8055eaced30ad" not found in file cache
```

---

## second time

### `config\_default\params.toml`
`custom_css = ["custom.css"]`

### same `assets\css\custom.css`

### no error msg, but it didnt work. is that  correct ?

**Comment by m9810223** [comment]
` !important` fail , too

**Comment by alekc** [comment]
@m9810223 ensure that you have the extended version of hugo (`hugo version`)

It should be something like 
```
hugo version
Hugo Static Site Generator v0.81.0-DEV/extended darwin/amd64 BuildDate: unknown
```
