### ISSUE TITLE
How to change site title?

### ISSUE THREAD

**Issue by atdx** [zzossig/hugo-theme-zzo#375]
How to change 
[this](https://ibb.co/T1sGBXs) ?

**Comment by szpak** [comment]
See [this](https://github.com/zzossig/hugo-theme-zzo/issues/298#issuecomment-652636564) or [that](https://github.com/zzossig/hugo-theme-zzo/issues/348#issuecomment-724969354).

@zzossig Maybe it is worth to clarify that in documentation?

**Comment by atdx** [comment]
> See [this](https://github.com/zzossig/hugo-theme-zzo/issues/298#issuecomment-652636564) or [that](https://github.com/zzossig/hugo-theme-zzo/issues/348#issuecomment-724969354).
> 
> @zzossig Maybe it is worth to clarify that in documentation?

oh thanks, I didn't expect it to be set in languages.toml
