### ISSUE TITLE
Request feature

### ISSUE THREAD

**Issue by mrfoxie** [zzossig/hugo-theme-zzo#378]
I use netlify to host my site, it would be easy to have netlify CMS login integrated to site to login and handle it propelly.

**Comment by zzossig** [comment]
No, it is user's duty to integrate such a thing. Sorry

**Comment by mrfoxie** [comment]
> No, it is user's duty to integrate such a thing. Sorry

can you send me documentation link and I have problem with share post usernames

**Comment by mrfoxie** [comment]
> No, it is user's duty to integrate such a thing. Sorry

I have added netlify cms in my site but is there any configuration for `config.yml` means posts, gallery, showcase etc.
