### ISSUE TITLE
Gitlab and mastodon social icons

### ISSUE THREAD

**Issue by hefistion** [zzossig/hugo-theme-zzo#38]
Hello, it would be possible to add social icons for mastodon and gitlab, thanks

**Comment by zzossig** [comment]
It's possible

**Comment by zzossig** [comment]
@hefistion I added the social icons. Update the Zzo theme and you can find it.

**Comment by fandean** [comment]
Hi, add @codeapes666 added: jianshu

**Comment by kvandenbrande** [comment]
> @zzossig is Signal or just a phone icon also possible?

**Comment by zzossig** [comment]
Any icon would be possible but can you show me a screenshot that you want?

**Comment by kvandenbrande** [comment]
A regular phone call icon would be great, you can forget about Signal

**Comment by zzossig** [comment]
Ok, I'll add it soon

**Comment by zzossig** [comment]
You can use it by adding the `socialOptions` config param

`params.toml`
```toml
...
[socialOptions]
  email = ""
  phone = ""
...
```

**Comment by kvandenbrande** [comment]
if I do that I get a build error calling partial: partial
"svgs/social/phone.svg" not found

**Comment by zzossig** [comment]
Did you update the theme?

**Comment by kvandenbrande** [comment]
and solved :-)  thx a lot!
