### ISSUE TITLE
Images not working

### ISSUE THREAD

**Issue by adarshbm82** [zzossig/hugo-theme-zzo#381]
I have created a directory inside the themes\zdoc\static\images\payroll-images and called in my md as below

    {{< img src="/images/payroll-images/img_01..jpg" >}

But this is not working. I tried placing the images folder at other locations as well. Please help!

**Comment by zzossig** [comment]
You should not touch the theme folder.
Make a folder at `root/static/images`  and there put your image files

**Comment by adarshbm82** [comment]
Thank you!!!

**Comment by milaiai** [comment]
How to use markdown default methods: ![](img.png) ???
