### ISSUE TITLE
Changing the default highlighting color for custom syntax

### ISSUE THREAD

**Issue by toto-co** [zzossig/hugo-theme-zzo#39]
Hello
I use zzo. Thank you.

In the dark theme of zzo, when the syntax is emphasized, the text is hard to see.
Please, can you change the color to emphasize?

The reason is that the highlighting color `#ffffcc` and the syntax text color are very bright.

I am using `custom.scss` setting and changing it to `#ff6188`.
The reason is that it is the same color as the table of contents.
But this color is not very good.

Many styles have a dark background and white or near-white text.
api, dracula, fruity, monokai, native, paraiso-dark, rrt, swapoff, solarized-dark256, vim, solaized-dark (?
)

I think you are busy, but please check it out.

**Comment by zzossig** [comment]
Can you provide me some screenshots?

**Comment by zzossig** [comment]
@toto-co Did you set in the data/skin.toml file, chroma_theme = "default? Or something else?

**Comment by toto-co** [comment]
chroma_theme is default.
![191220_chroma-color2](https://user-images.githubusercontent.com/59129387/71474982-8d6d3e00-2821-11ea-8067-771aaa6701fd.png)
![191220_chroma-color3](https://user-images.githubusercontent.com/59129387/71474988-9231f200-2821-11ea-91be-3fbecc0839d6.png)
![191220_chroma-color5](https://user-images.githubusercontent.com/59129387/71474997-96f6a600-2821-11ea-88f8-ee2a4cc65f7f.png)

**Comment by zzossig** [comment]
Ah! Now I understand clearly. I’ll think about it more. It will be fixed soon

**Comment by toto-co** [comment]
Thank you !

**Comment by zzossig** [comment]
@toto-co I changed the highlighting line background color to black.

**Comment by toto-co** [comment]
Splitting parameters is a good idea.
 Thank you!
