### ISSUE TITLE
When switching to bright theme, code highlighting seems to be in trouble

### ISSUE THREAD

**Issue by fandean** [zzossig/hugo-theme-zzo#40]
When switching to a bright theme (light,solarized,custom theme), the code highlighting seems to have a problem.It looks like this.
![image](https://user-images.githubusercontent.com/25637720/71455844-d39ab100-27d1-11ea-97a6-31b56f0426d2.png)
Switch to a bright theme
![image](https://user-images.githubusercontent.com/25637720/71455848-d7c6ce80-27d1-11ea-8e38-5b5bb05d0571.png)

 I don't know if it's a personal problem. Can you check it?

**Comment by zzossig** [comment]
Oh, I see. Something is wrong. This was not used to happen before. Maybe after some updates, I mistakenly changed something.

**Comment by zzossig** [comment]
@fandean Did you set in the data/skin.toml file,  `chroma_theme = "default`?

**Comment by fandean** [comment]
I set `chroma_theme = "monokai"`

**Comment by zzossig** [comment]
set the params to `"default"` and it will be fixed

**Comment by fandean** [comment]
Hi, add @codeapes666 added: jianshu

_Originally posted by @fandean in https://github.com/zzossig/hugo-theme-zzo/issues/38#issuecomment-568951179_

**Comment by zzossig** [comment]
We can solve this problem by setting chroma for each of the themes.

**Comment by zzossig** [comment]
@fandean I divided chroma_theme param to separate 5 params
```
...
theme_light_chroma = "default"
theme_dark_chroma = "default"
theme_hacker_chroma = "default"
theme_solarized_chroma = "default"
theme_custom_chroma = "default"
```

You can override this file at your root/data/skin.toml

**Comment by fandean** [comment]
Ah, how to say, and I expect the effect is not the same

**Comment by fandean** [comment]
Can we match 
```
    content-pre-main-color: #607d8b,
    content-pre-color: #344952,
    content-pre-number-color: #aaa,
    content-pre-background-color: #F5F2F0,
    content-pre-border-background-color: darken(#F5F2F0, 7%),
    content-pre-header-background-color: darken(#F5F2F0, 3%),
    content-pre-header-color: #344952,
```
to some of the values in  
```
  /* Background */ .chroma { color: #f8f8f2; background-color: #171f2e }
  /* LineHighlight */ .chroma .hl { display: block; width: 100%;background-color: black }
  /* LineNumbersTable */ .chroma .lnt { margin-right: 0.4em; padding: 0 0.4em 0 0.4em;color: #7f7f7f }
  /* LineNumbers */ .chroma .ln { margin-right: 0.4em; padding: 0 0.4em 0 0.4em;color: #7f7f7f }
```
of the currently selected chrome, rather than fixing it?

That is to say, let chrome theme color and zzo theme color be completely independent.

**Comment by zzossig** [comment]
Now I understand what you mean.
Actually, I think it's a good idea.
I'll investigate more about it on how to achieve that concept.

**Comment by zzossig** [comment]
@fandean Thank you for the good suggestion.
Now, we have another option variable in the skin.toml file

```toml
...
theme_light_chroma_background = "default"
theme_dark_chroma_background = "default"
theme_hacker_chroma_background = "default"
theme_solarized_chroma_background = "default"
theme_custom_chroma_background = "default"
```

**Comment by fandean** [comment]
I'm sorry, I was not clear enough expression 😨

>  I've been on a long trip today

**Comment by zzossig** [comment]
The updated version is not what you expected?

**Comment by fandean** [comment]
The way I think about it is this
![image](https://user-images.githubusercontent.com/25637720/71544890-53d23980-29bf-11ea-9d98-b5751991a5e3.png)
![image](https://user-images.githubusercontent.com/25637720/71544892-5af94780-29bf-11ea-846b-9d0ca90151ab.png)
![image](https://user-images.githubusercontent.com/25637720/71544894-62b8ec00-29bf-11ea-9d06-8ccb1b73aca7.png)

**Comment by zzossig** [comment]
Want to completely customize code block color by setting color codes?

**Comment by fandean** [comment]
Feasibility is also a consideration, I can compromise on it

**Comment by zzossig** [comment]
I don't understand what this means
> Feasibility is also a consideration, I can compromise on it

**Comment by fandean** [comment]
I think you should know more about zzo and related matters than I do. There may be situations I didn't take into account.

**Comment by zzossig** [comment]
I'm afraid if we make 35 variables to accomplish the goal, it will slow down the web performance. And it makes the Zzo theme more complicated.

I think setting the color one by one is not a good idea. 
But we can make more chroma background color packs.
We currently have 5 color packs(dark, light, hacker, solarized, custom).
But if necessary, we make more pack something like darkorange, darksolarized, something like that

**Comment by fandean** [comment]
I am relieved, ha ha, looking forward to your results.

Do you see this?
![image](https://user-images.githubusercontent.com/25637720/71545211-85e59a80-29c3-11ea-9235-4d9a32ad0cda.png)

**Comment by zzossig** [comment]
Yes, I'm fixing it currently

**Comment by fandean** [comment]
That's exactly what I meant

**Comment by zzossig** [comment]
@fandean I uploaded for fixing the code block color.

Do you have any color suggestions for the code block? I'll add it if you have

```scss
content-code-color: #fcfcfa,
    content-pre-main-color: #FFA7C4,
    content-pre-color: #eee,
    content-pre-number-color: #666,
    content-pre-background-color: #171f2e,
    content-pre-header-background-color: darken(#011627, 1.5%),
    content-pre-border-background-color: #3a3a3a,
    content-pre-header-color: #FCFCFA,
```

**Comment by zzossig** [comment]
Bro,
I think this session is too long. We can close this issue now.
We can talk further by making a new issue!
And I really welcome any issue that makes the Zzo theme better. You know I deeply appreciate your keep interest.
