### ISSUE TITLE
Search json file is 370k, how to exclude content from indexing?

### ISSUE THREAD

**Issue by VictorZakharov** [zzossig/hugo-theme-zzo#403]
Search json file is getting bigger and it's likely to be loaded on every request (for most users anyway).
370k actual size = 120k compressed, but still a lot (regular page load is 25k or less - compressed).
Is it possible to exclude content from indexing? Would make sense to leave only title and description, this should reduce it by 17x, for below article link (7027 bytes index with content, 406 bytes without content property - for a single post).
![image](https://user-images.githubusercontent.com/8978766/113418125-def46900-9392-11eb-9399-c30220a4ad5b.png)
[Link to my blog](https://www.neolisk.blog/), for testing.

**Comment by mmiots9** [comment]
Hi Victor, can I ask you how you can index content? in my zzo theme site it index only the title and the description, but I need to index also the content when I have to search set in the site. Can you explain me how have you done?

**Comment by VictorZakharov** [comment]
I didn't do anything there, this is how it worked initially. I just never realized the json file includes content.

**Comment by mmiots9** [comment]
ah ok, I don't know why but I don't have the content. I am very a beginner, but I don't understand where I'm wrong. 
Even in their example site it did not index the content

**Comment by VictorZakharov** [comment]
Which site do you mean?
![image](https://user-images.githubusercontent.com/8978766/113429795-1836d400-93a7-11eb-954f-10089663dfe6.png)

**Comment by mmiots9** [comment]
https://themes.gohugo.io/theme/hugo-theme-zzo/en/

I'm sorry, maybe I misunderstood your post. 
What I meant is that, even in this site, when you search something, it does not take into account the content of the posts, but only the title and the description. For example, searching for "blockquotes" does not return anything, even if in a post it appears. 
Did I misunderstood the post? If I did, I'm sorry for that. I'm trying to understand why in this theme it does not search into the content of the posts.

**Comment by VictorZakharov** [comment]
Then it's a bug. Look for index.json in the F12/dev tools -> Network tab. It has content. If this content is not actually used, it's a bug that needs fixing.

**Comment by VictorZakharov** [comment]
@mmiots9 You are right, I can reproduce. Then definitely should not include content in the json file.
![image](https://user-images.githubusercontent.com/8978766/113433720-b9c12400-93ad-11eb-836a-4c59f3e1f910.png)

**Comment by mmiots9** [comment]
Ok, thank you for the feedback. 
I hope they can fix it, beacuse having a site in which is impossible to search through the content of the post is not very useful.
Do you have an idea of how to fix it?

**Comment by VictorZakharov** [comment]
@mmiots9 Nope, I'm not an author, and not familiar with how build or scripting works here.
I can only do basic CSS fixes and use existing partials, such as this [404 issue](https://github.com/zzossig/hugo-theme-zzo/issues/404).

Regarding useful or not - it's a tradeoff. On one hand you want to search everything. On the other you want to keep page size low. Even at my blog size which is roughly 150 posts, I can definitely see the need to avoid searching through content.

**Comment by mmiots9** [comment]
Okok, I see. 
Maybe with longer and better descriptions, the user could find what he needs also without searching in everything.
Thank you :)

**Comment by zzossig** [comment]
@VictorZakharov I added new param for this in the latest commit.
You might want to do this.
In your `params.toml` file,
```toml
...
searchContent = false
...
```
