### ISSUE TITLE
Post content not in search

### ISSUE THREAD

**Issue by mmiots9** [zzossig/hugo-theme-zzo#405]
Hi, 
I'm writing because the search command does not search into the content of any post/page. It only search the words in titles and descriptions. 
Is there anything that could be done to change it? I need to search words into posts.
Thank you

**Comment by zzossig** [comment]
I added a new search option in the last commit.
You might want to do this.
Update the theme first and
in your `params.toml` file,
```toml
...
searchDistance = 100 // default 100
...
```
set the `searchDistance` to whatever you want.
