### ISSUE TITLE
Table of contents default state

### ISSUE THREAD

**Issue by dishanrajapaksha** [zzossig/hugo-theme-zzo#41]
Hello! First of all, thank you for developing this theme; it is beautiful.

I have a feature suggestion for Table of Contents for its default state. 

Can we have another configuration, such as `enableToc`, to set the default state? May be `tocDefaultState`. When that is false, single page is ToC is enabled but turned off by default.

Let me know if you need any help; I'm new to Go, though.

Thanks again.

**Comment by zzossig** [comment]
Did you mean that you want to enable the Toc conditionally?

**Comment by dishanrajapaksha** [comment]
> Did you mean that you want to enable the Toc conditionally?

Yes., As in to set a default state, whether it is open or not. Currently, when it is enabled, it is open by default.

**Comment by zzossig** [comment]
I think it could be done by setting the front matter.
First, update the Zzo theme. I fixed a bug.
Next, set the enableToc Param at the front matter something like this

content/posts/mypost.md
---
title: "my post"
date: 2019-12-26T12:00:24+09:00
description: post desc
tags:
- 
series:
-
categories:
-
enableToc: false
---

In this way, you can disable / enable the single page Toc

**Comment by dishanrajapaksha** [comment]
Ah yes, I found that, thanks. What I'm talking about is another matter I'm afraid because it disables the Toc. Let me show you.

When we enable Toc and open a page, it looks like this right?

![tocOn](https://user-images.githubusercontent.com/9119289/71459514-e57a5500-27cd-11ea-988b-92717d512664.png)

What I'm talking about is opening the page like this, so that a user can toggle the Toc.

![tocOff](https://user-images.githubusercontent.com/9119289/71459580-35f1b280-27ce-11ea-86cd-c27b94c11d7b.png)

**Comment by zzossig** [comment]
Ok, It makes sense.
I'll add a param named `hideToc` on params.toml file.

**Comment by fandean** [comment]
Hi,Can you use common parameters here, such as `toc:false`

**Comment by zzossig** [comment]
@fandean Did you mean change the enableToc to toc?

**Comment by fandean** [comment]
yes

**Comment by zzossig** [comment]
Actually, I do want to change some param names to another,
Why I can't do this is because if I change the params, other people who use the Zzo theme may conflict with their Hugo site until they change the params as we changed.

**Comment by fandean** [comment]
The way I think about it is that some of the jekyll site themes I've used before support `toc` to control the display of the TOC, so I think `toc` is more general, and this is the first time this parameter has been discussed in a zzo theme

**Comment by zzossig** [comment]
I think that change the existing param name is not a good idea. Someone will get in trouble by the param. In case that if the toc is more general naming, then we can keep enableToc and toc both of them that behave the same role.

**Comment by fandean** [comment]
OK

**Comment by zzossig** [comment]
@dishanrajapaksha I added param named hideToc. Maybe you want to set this param like this

params.toml file
```toml
...
hideToc = true
...
```

@fandean Bro, I added the toc. You can replace enableToc to toc in params.toml file. Something like this. Now, enableToc and toc params are logically the same.

params.toml file

<s>enableToc = true</s>
toc = true

You can also use toc at front matter in your content md file.
```md
---
...
tags:
- javascript
- programming
series:
- 
categories:
-
toc: true
---
```

**Comment by dishanrajapaksha** [comment]
@zzossig Thank you, that was fast 😄 I just checked, and it works just as I expected. Maybe we can close this issue?
