### ISSUE TITLE
How to set custom logo  in the site navigation bar ?

### ISSUE THREAD

**Issue by dushaoshuai** [zzossig/hugo-theme-zzo#412]
It seems that logo has been hard-coded somewhere, and there're only there options that are related to logo :
```
logoText = "Zzo" # Logo text that appears in the site navigation bar.
logoType = "short" # long, short -> short: squre shape includes logo text, long: rectangle shape not includes logo text
logo = true # Logo that appears in the site navigation bar.
```
How can I set a custom logo ?

**Comment by szpak** [comment]
Just add your logo as `static/logo.png` and it will be used.

**Comment by dushaoshuai** [comment]
> Just add your logo as `static/logo.png` and it will be used.

That's brilliant! Thank you!
