### ISSUE TITLE
My site not showing article after build

### ISSUE THREAD

**Issue by uluumbch** [zzossig/hugo-theme-zzo#413]
my site not showing article after build with `hugo` command. If i run `hugo server disableFastRender` it happens too.
this is from my local
![image](https://user-images.githubusercontent.com/49960993/116794165-3f430b80-aaf5-11eb-8b1b-ab179ac359d7.png)
and this is form my public folder after run `hugo` 
![image](https://user-images.githubusercontent.com/49960993/116794196-6f8aaa00-aaf5-11eb-870c-9bc5a6f25fa3.png)
I still got nothing, but if i run command `hugo server` it is normal and my articel was show up
![image](https://user-images.githubusercontent.com/49960993/116794226-9c3ec180-aaf5-11eb-8dec-3f5c5999cf66.png)
How do i fix this?

**Comment by mistrysiddh** [comment]
use `hugo server -D -v`
