### ISSUE TITLE
How to add CC BY-NC-SA  license

### ISSUE THREAD

**Issue by fandean** [zzossig/hugo-theme-zzo#42]
I changed copyright 
```toml
copyright = "除非另有声明，本网站内容采用 CC BY-NC-SA 4.0 授权"
```
But do I need to add a link for `CC BY-NC-SA 4.0`

![image](https://user-images.githubusercontent.com/25637720/71468044-ac5ad880-27ff-11ea-8ee8-b6a9eeebe109.png)

**Comment by zzossig** [comment]
Do you mean this kind of link?
![license](https://user-images.githubusercontent.com/52706977/71468180-78d07c00-2808-11ea-865d-a6744635a6a6.png)

Are you made the license here? [https://creativecommons.org/choose/](https://creativecommons.org/choose/)

**Comment by fandean** [comment]
Like this 

除非另有声明，本网站内容采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh) 授权 

Pictures are optional

**Comment by zzossig** [comment]
I think we should add 2 params for the copyright link specific.
- copyrightLinkImage
- copyrightLinkText

**Comment by fandean** [comment]
I agree with you

**Comment by zzossig** [comment]
@fandean I uploaded just now. Check it out if it works as you expected

**Comment by fandean** [comment]
I think it's good.
