### ISSUE TITLE
Google Search Console unable to fetch sitemap

### ISSUE THREAD

**Issue by mistrysiddh** [zzossig/hugo-theme-zzo#422]
its shows me this error when i add my sitemap to google search console

![google search console](https://user-images.githubusercontent.com/25217451/121001573-0d366080-c7a9-11eb-8c79-8c4db79af094.png)

but where as for bing webmaster it is eaisly able to fetch sitemap

![image](https://user-images.githubusercontent.com/25217451/121001937-6acaad00-c7a9-11eb-8ea5-3eb6ef93b1ef.png)

**Comment by Touexe** [comment]
@mrfoxie have you solved the issue? maybe all you have to do is rename the sitemap name from sitemap.xml to sitemap_index.xml

**Comment by mistrysiddh** [comment]
i tried both the methods but still showing me the same issue

**Comment by Touexe** [comment]
@mrfoxie it works for me when i change baseurl in config to my own domain url, then let hugo generate your sitemap for you

**Comment by mistrysiddh** [comment]
> @mrfoxie it works for me when i change baseurl in config to my own domain url, then let hugo generate your sitemap for you

i just change my domain and it worked
