### ISSUE TITLE
Ask for help: How to remove the duplicate language subdirectory `zh/` in route ? 

### ISSUE THREAD

**Issue by jacklanda** [zzossig/hugo-theme-zzo#446]
- As this description, I bump into this issue without any clues to solve it. I can run `hugo server -D` to try to build a draft, however, the route api appears with duplicate `zh/`(zh/ is one of my i18n dir). As the following image shows:
- <img width="206" alt="图片" src="https://user-images.githubusercontent.com/54089835/133889200-27ddd6e8-0dcc-4f09-afb7-e0de5b6669f6.png">
- Because of this problem, I can not access my `about page` by `localhost:1313/zh/about` but can access it by `localhost:1313/zh/zh/about`.
- I have try to set these three params `defaultContentLanguage` `defaultContentLanguageInSubdir` `hasCJKLanguage`, but it didn't work.

Anyway, it's weired and I would like to ask you if there are some items in config file I should have a try, or any other ways to figure it out?

**Comment by szpak** [comment]
@jacklanda Having your problem solved (I hope), you could write the solution for people reaching out this issue sometime in the future.

**Comment by jacklanda** [comment]
> @jacklanda Having your problem solved (I hope), you could write the solution for people reaching out this issue sometime in the future.

Thanks for reminding.
- The reason is some parts of my new blog files(i.e. a copy of old blog files) which were broken when I make a temp for it.
- So I just change to use the old version of my blog files, and everything go well. I don't need to set any configs to handle it, because my new copy is incomplete or broken.

**Comment by szpak** [comment]
Thanks @jacklanda!
