### ISSUE TITLE
How to highlight one of line in code block ?

### ISSUE THREAD

**Issue by jacklanda** [zzossig/hugo-theme-zzo#453]
viz. I would like to highlight this line in code blok `asm`, how can I implement it ?
<img width="600" alt="图片" src="https://user-images.githubusercontent.com/54089835/135034091-7158d695-80d7-45ea-9d48-ee42376ddd11.png">

**Comment by szpak** [comment]
Check the source of the example page with syntax highlighting distributed with the zzo theme:

```
``` diff {hl_lines=[4,"6-7"]}
*** /path/to/original   ''timestamp''
--- /path/to/new        ''timestamp''
***************
*** 1 ****
! This is a line.
--- 1 ---
! This is a replacement line.
It is important to spell
-removed line
+new line
```
```

**Comment by jacklanda** [comment]
> Check the source of the example page with syntax highlighting distributed with zzo theme:
> 
> ```
> ``` diff {hl_lines=[4,"6-7"]}
> *** /path/to/original   ''timestamp''
> --- /path/to/new        ''timestamp''
> ***************
> *** 1 ****
> ! This is a line.
> --- 1 ---
> ! This is a replacement line.
> It is important to spell
> -removed line
> +new line
> ```

It's my carelessness when read doc, thank you !
