### ISSUE TITLE
Hi ,zzo is a great theme, can you improve full text search？

### ISSUE THREAD

**Issue by Briy09** [zzossig/hugo-theme-zzo#46]
Hi,zzo is a great theme, and wish you a happy new year!
Can you improve instant full text search？ Because current search without keyword highlighting and context.
refer:
https://koirand.github.io/blog/  ,search "vim" for example.
https://github.com/koirand/pulp

https://simpleyyt.com/ ,search "is" for example.
https://github.com/simpleyyt/jekyll-theme-next

https://blog.tmaize.net/pages/search.html ,search "ssh" for example.
https://github.com/TMaize/tmaize-blog

![snipaste_20191230_113706](https://user-images.githubusercontent.com/49552463/71567561-f17e5380-2afa-11ea-8732-19a869669033.png)

**Comment by zzossig** [comment]
Hello, happy new year 😋. so what you want is to highlighting the text you typed in. Is that right?

**Comment by Briy09** [comment]
yes.

**Comment by zzossig** [comment]
Thanks, good suggestion. It will be updated soon

**Comment by zzossig** [comment]
Done, update the Zzo theme and it should work
