### ISSUE TITLE
found no layout file for "searchindex" for kind "page"

### ISSUE THREAD

**Issue by santosh** [zzossig/hugo-theme-zzo#461]
Getting this warning when staring the dev server. 

```
WARN 2022/01/12 14:34:42 found no layout file for "searchindex" for kind "page": You should create a template file which matches Hugo Layouts Lookup Rules for this combination.
```

This warning seems to be appearing for each of the posts I have. I can confirm this because the warning pops up on page reload.

How to troubleshoot and fix this warning?

**Comment by jomarmar** [comment]
Same here, any solution to fix the warning?

**Comment by santosh** [comment]
I have still not found the answer. I'm closing this issue as this issue does not seems to be of importance. It's just a warning. 🤷🏼‍♂️
