### ISSUE TITLE
How to automatically generate  archive page content

### ISSUE THREAD

**Issue by wangdongming007** [zzossig/hugo-theme-zzo#47]
How to automatically generate  archive page content, just like the [hugo-theme-zzo demo archive url](https://themes.gohugo.io//theme/hugo-theme-zzo/en/archive). I try to read all the configuration of hugo-theme-zzo, but can't find where to change the configuration to make it work.

**Comment by zzossig** [comment]
Did you set the the archive menu in your menu.toml  config file? https://github.com/zzossig/hugo-theme-zzo/blob/6704205fab4975b72f26e1c98000af8fe41d7384/exampleSite/config/_default/menus.en.toml#L7

 Also you need to make archive folder and _index.md file there.

**Comment by wangdongming007** [comment]
> Did you set the the archive menu in your menu.toml config file?
> 
> https://github.com/zzossig/hugo-theme-zzo/blob/6704205fab4975b72f26e1c98000af8fe41d7384/exampleSite/config/_default/menus.en.toml#L7
> 
> Also you need to make archive folder and _index.md file in root/content/archive/_index.md

thank you so mush, it work.
