### ISSUE TITLE
Add talks page

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#50]
I really like the way the archive page is setup and styled (grouping by year). Thank you for putting in the effort in that.

I would also like to have a similar page for Talks/Sessions. The idea is to be able to provide a list of items with their url, something like the `menu.en.toml` file which is then rendered grouped by year/year-month. The links don't need to be relative to the blog, but rather open as new page.

Some relative fields for talks would be:
- title
- video url
- presentation link
- event link

I appreciate your work and would like to know how I can help here. If you can point me in the right direction, I can contribute back whenever I have the time.

**Comment by zzossig** [comment]
Ok, I can make it but can you provide me some example site? or a picture?
Maybe, I can misunderstand what you mean.

**Comment by nisrulz** [comment]
Yes, maybe I can edit the html for taking a screenshot. Will add here.

Thank you :smile_cat:

**Comment by zzossig** [comment]
No Problem😸

**Comment by nisrulz** [comment]
I was able to quickly put this together. I hope it helps.

![Screenshot from 2019-12-30 14-40-28](https://user-images.githubusercontent.com/2096087/71584306-572a0a00-2b12-11ea-94bf-e0024069239b.png)

Ignore the top spacing between the year and the talk title.

If the url is empty, the link shouldn't show up. i.e
If say videoUrl="", it doesn't show in the sub list.

**Comment by zzossig** [comment]
Can you suggest to me how the data structure will look like if we set it in javascript?
```javascript
[
 {
  date: "1111-11-11",
  eventLinks: [],
   videoLinks: [],
   ptLinks: [],
 }
]
```

something like this?

**Comment by nisrulz** [comment]
I imagined it to be a `.toml` config file.
```toml
[[talk]]
  date = "1111-11-11"
  title = "My awesome talk title"
  videoLink = "https://www.youtube.com/video"
  pptLink = "https://www.speakerdeck.com/ppt"
  eventLink = "https://www.meetup.com/event"
```

something similar in `json` would be like:

```json
[
 {
  date: "1111-11-11",
  title : "My awesome talk title",
  videoLink : "https://www.youtube.com/video",
  pptLink : "https://www.speakerdeck.com/ppt",
  eventLink : "https://www.meetup.com/event"
 },
{
  date: "1111-11-11",
  title : "My awesome talk 2 title",
  videoLink : "https://www.youtube.com/video",
  pptLink : "https://www.speakerdeck.com/ppt",
  eventLink : "https://www.meetup.com/event"
 },
...
]
```

**Comment by zzossig** [comment]
By using this data structure, it seems we can add at most 3 links per one title right?

**Comment by nisrulz** [comment]
Yes. This is the common use case.

Most people will not have more than one link per type. If they do, it will be a different date.

**Comment by zzossig** [comment]
Ok, I understand. I'll take care of this issue first, and then Ubuntu next

**Comment by zzossig** [comment]
Update the Zzo theme and check it if the talks page looks what you expected.

**Comment by nisrulz** [comment]
This is soooooooooo cool. :rocket:  Thank you soo much.

I am in the process of migrating my existing blog and this was huge blocker. :+1: 

Let me know if you need any help and I can also try helping you out. Cheers :tada:
