### ISSUE TITLE
Favicon only works when there is favicon.png

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#51]
I noticed favicon change only works with `favicon.png`. I had `favicon.ico` and it wouldn't pick it up, unless I added `favicon.png`.

Ideally it should pick `.ico` first and then `.png`.

**Comment by zzossig** [comment]
Yes, you are right. It should be fixed!

**Comment by nisrulz** [comment]
I could take a look!

**Comment by zzossig** [comment]
I tested it. but seems .ico file seems to work well.
What browser are you using? what Hugo version? 
macOS or Windows10?

**Comment by nisrulz** [comment]
Ubuntu Budgie 18.0.4 LTS

Chrome: Version 79.0.3945.88 (Official Build) (64-bit)

Hugo Static Site Generator v0.62.0/extended linux/amd64

**Comment by zzossig** [comment]
I didn't test it on the Ubuntu environment.
But in windows10, it works fine even though the favicon.png file does not exist.

**Comment by nisrulz** [comment]
I could try on a Macbook Air, I have one. I will add my findings here too!

Thank you!

**Comment by zzossig** [comment]
I tested it on Ubuntu but seems to work well.
Did you try to force reload the browser?
`ctrl + shift + r`

**Comment by nisrulz** [comment]
I updated the git submodule and now everything works.Weird. :thinking: 

Anyways, looks like it is fixed. So we can close this issue.

Thank you!
