### ISSUE TITLE
The social media icons don't wrap

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#52]
When you have more than 6 social media links in the sidebar, the icons overflow the container.

![Screenshot from 2019-12-30 14-48-32](https://user-images.githubusercontent.com/2096087/71584630-c7855b00-2b13-11ea-84b3-50ebfa4fd3e9.png)

**Comment by zzossig** [comment]
Thanks!

**Comment by zzossig** [comment]
It's fixed now
