### ISSUE TITLE
Cannot add upcoming talks

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#56]
Basically, what it means is ability to add talks that will be happening in the future i.e are upcoming.

Usually speakers would get selected and will have a talk in a few months. This will allow them to list those talks up on the page too.

Thank you!

**Comment by zzossig** [comment]
I updated to list talks up on the home page.
But you cannot set the date to a future date.

For example,
```
---
...
date: 2030-12-31
...
---
```
Hugo will treat this post as a draft. So this post will not on the list.
related issue
- [https://github.com/gohugoio/hugo/issues/3854](https://github.com/gohugoio/hugo/issues/3854)
- [https://github.com/gohugoio/hugo/issues/3977](https://github.com/gohugoio/hugo/issues/3977)

**Comment by nisrulz** [comment]
This works! Thank you :+1: 

Quick question: Why is the `publishDate` date required? Everything works the same with `date`.
> Inside  md file at root/content/talks/myLinks.md

**Comment by zzossig** [comment]
We are using ‘date’ front matter for sorting list in the home page, terms page, section page.

So if we use the ‘date’ for talks page, it will always show up at the top of the list

**Comment by nisrulz** [comment]
That makes sense. I was actually going to ask about those showing up on the home page. I will make the fix so they don't show.

Thank you for explaining it to me.

**Comment by zzossig** [comment]
Oh, you don’t want the talks showing up on the home page? Actually it was not displayed on the home page but I deleted that part. I’ll rollback that code

**Comment by nisrulz** [comment]
That would be nice.

Essentially this is blog. So only posts should show up on the home page. Anything else should show in its own page.

**Comment by zzossig** [comment]
Yes I misunderstood some words.

**Comment by nisrulz** [comment]
I think you meant this commit: 9c21e922e1215051bb2019cbfcfdd51decaa3dd7

Maybe what would be better is to have it behind a flag. This would make it dynamic and you don't need to filter it. 

So putting in a config, which by default does not show in home page, but when set to true will show in home page. It can be any page.

**Comment by nisrulz** [comment]
..or it can be a field that takes an array. i.e

showInHomePageTypes = [posts, talks]

This way if someone doesn't want to show talks they just set it to:

showInHomePageTypes = [posts]

and your logic would be something like:

if(pageType is in showInHomePageTypes array){
then show in home page
}

What do you think?

**Comment by zzossig** [comment]
I’ll think about it more.
But if we add this feature, ‘dontShowInHomePage’ would be better name I think.

**Comment by nisrulz** [comment]
`dontShowInHomePage` also works :+1:

**Comment by zzossig** [comment]
No add new issue . It’s better
