### ISSUE TITLE
Making certain pages not show in Home Page list

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#58]
Ideally only the posts pages should be shown in the Home page list. 

However sometimes it is required to not show some pages i.e talks pages shouldn't be shown in the Home Page list.

There should be a way to set this up in configuration.

Some discussion regarding this was done in issue #56

**Comment by zzossig** [comment]
Now, we have another param named `notAllowedTypesInHome` in root/config/_default/params.toml file. 
```toml
...
notAllowedTypesInHome = ["contact", "talks", "about"]
...
```

The type name default value would be the folder name(the folder that contains the MD file).Refer this link - [assign-a-content-type](https://gohugo.io/content-management/types/#assign-a-content-type)

**Comment by nisrulz** [comment]
Will try this tonight.

**Comment by nisrulz** [comment]
This works perfectly. Thank you!
