### ISSUE TITLE
Click on image does not always display the image

### ISSUE THREAD

**Issue by nocquidant** [zzossig/hugo-theme-zzo#59]
I have an issue with my images when I click on them, but it doesn't look like I can reproduce using: https://themes.gohugo.io/theme/hugo-theme-zzo/en

Anyway, this is what I get :

* image not clicked (OK)
![image](https://user-images.githubusercontent.com/217054/71732997-d0926700-2e48-11ea-99c7-8956052533d4.png)

* image clicked (KO)
![image](https://user-images.githubusercontent.com/217054/71733032-e738be00-2e48-11ea-884a-eeb490d77e0b.png)

Note: it looks like it works sometimes so I don't think it is a path issue but maybe an async load issue?

**Comment by zzossig** [comment]
Yes, I know it sometimes happen. That is because photoswipe is not supporting dynamic size image and I forced to do that behavior so this happened. Anyway I was planning to solve this issue. 

I have another big issue that is to remove dependency of jquery. After doing it, I’ll take care of this issue

**Comment by zzossig** [comment]
I have done the rebuilding gallery.
Now we use Micromodal(1.8kb minified and gzipped), Swipe(6kb minified) library for the gallery.

**Comment by zzossig** [comment]
Feel free re-open this issue if the gallery is not working as expected after you updated the Zzo theme

**Comment by nocquidant** [comment]
OK, just tried now and it looks good! But I thought it would displayed the image in its original size.

My small image in text: 
![image](https://user-images.githubusercontent.com/217054/71880086-d54c6900-312f-11ea-9ec6-dc9257709632.png)

Should be bigger when clicked (621x394):
![image](https://user-images.githubusercontent.com/217054/71880115-e2695800-312f-11ea-9999-8c19b48ba2a9.png)

--nick

**Comment by zzossig** [comment]
Are you intentionally make the image small in the text by setting the width, height?

**Comment by nocquidant** [comment]
Yes, as my text could contains several images, I generally set a size for each image for a nice global looking...

**Comment by zzossig** [comment]
How do you think which one is more natural behavior?

1. Always show the original image
2. At first, show the modified size. if we click the image, magnify it to the original size.

**Comment by zzossig** [comment]
Many photo swipe library has the feature to magnify the image.
![bbbb](https://user-images.githubusercontent.com/52706977/71881500-bffa2d80-3175-11ea-84e6-52a4098fc48a.png)

**Comment by nocquidant** [comment]
For my case, I would prefer 1 (less clicks).

**Comment by zzossig** [comment]
Ok, I'll find a way to solve this problem.

**Comment by nocquidant** [comment]
If easier, go for 2. Even if it looks more appropriate for big jpg images which my posts don't have, it would be fine for me too ;)

**Comment by zzossig** [comment]
I did 1. Hope this time works

**Comment by nocquidant** [comment]
Great, thanks!
