### ISSUE TITLE
add a "draft: true/false" option to the header

### ISSUE THREAD

**Issue by brimwats** [zzossig/hugo-theme-zzo#60]
most hugo blogs do this and it would be be helpful!

**Comment by zzossig** [comment]
Are you start Hugo by typing this?
```bash
hugo server -D
```

-D is a shortcut of `--buildDrafts`

Actually, I don't understand what you mean.
Can you explain more specific?

**Comment by zzossig** [comment]
I highly suspect that you may start the Hugo with ‘-D’ flag.

Hugo takes care of the draft. If it’s not working, it should be the Hugo issue

**Comment by brimwats** [comment]
Sorry for the delay! Been traveling. Many other Hugo themes have a draft: true/false in their header (yaml?) I figured out that in zzo you can put a hashtag in front of the date to take the post off the front page which works kinda the same! Just didn't see it as an option in docs! :)

On Jan 5, 2020 11:21 PM, zzossig <notifications@github.com> wrote:

I highly suspect that you may start the Hugo with '-D' flag.

Hugo takes care of the draft. If it's not working, it should be the Hugo issue

-
