### ISSUE TITLE
[Suggestion] A different talk index page design

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#62]
I know I suggested a design earlier, but as I started populating that page with more talks, it doesn't look good as the `Archive` page does (which was the inspiration mostly for the talk page.)

This is how it looks now:
![Screenshot from 2020-01-06 01-52-34](https://user-images.githubusercontent.com/2096087/71788953-929f6980-3027-11ea-9b3e-36073d480e93.png)

Looking at this and also considering that one can actually click on the title of the talk to open its own page, where one can list all the other links, I was thinking that it would be nice if the talk page index looked more like the archive page. Something like this:

![Screenshot from 2020-01-06 01-52-16](https://user-images.githubusercontent.com/2096087/71788977-d2fee780-3027-11ea-9156-3004f4afa069.png)

Maybe the date can be first and the the event name. Here the other links are now gone and reader's would click on the talk title to get to its own page which can have other links. The theme shouldn't bother about those links.

What do you think about this?

I feel like this is a much clean design and also falls in place for the theme since it is similar to the archive page.

**Comment by zzossig** [comment]
I welcome design suggestions!
Did you mean that the talks page has to be the same design as the archive page?

**Comment by nisrulz** [comment]
Yes, but only the index page. Instead of it showing Video, PPT, Event links it shows only the talk title.

The end result should look like this:
![image](https://user-images.githubusercontent.com/2096087/71789349-de9fdd80-302a-11ea-9d1c-9e13c68f46f3.png)

However, maybe you can remove the event name too. Just Keep the date. So you will not have any "Droidcon Berlin" or "Droidcon Vienna" fields in the above screenshot.

**Comment by zzossig** [comment]
Thanks for the detailed explanation! I'll make it like that.
I'm currently working on making a gallery and removing jquery.
It may take some time but not too long.

**Comment by nisrulz** [comment]
That sounds good. I am sure many people would want to get rid of jquery. Gallery is important for my use case too (I used to be a designer/freelancer so have some work to put up on my blog). So your work will benefit me too.

Let me know if you need any help :)

Thank you for all the work on this theme 😸

**Comment by zzossig** [comment]
Actually, I need some design advice.
I want to talk more about the talks page design after I finished the gallery, jquery issue.

**Comment by zzossig** [comment]
```yaml
---
title: "My Awesome links"
...
links: # delete all links
  ...
---
```
How about deleting the links in Front Matter? If you do that, the talks page UI roughly the same as you mentioned above.

And I'm thinking about to make a talks detail page template. If almost all of the talks detail page UI is the same, it make sense to make the template.

**Comment by nisrulz** [comment]
I did that and it worked :tada: 

But do you want todo some cleanup for this?

My talk detail page is iframes, that allow me to display the ppt and videos inline of the page, so readers don't leave my blog to goto youtube or google slides.

**Comment by zzossig** [comment]
Oh, ok.
If you need some modifications of the talks UI, tell me.

**Comment by nisrulz** [comment]
For now everything works for me. I have ported most of my content to this theme. Thanks to your support.

Will close this issue, unless I have something new from design perspective.

Thank you :tada:
