### ISSUE TITLE
Zombie `` show up below code block defined inside a list and indented.

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#65]
![Screenshot from 2020-01-07 00-50-46](https://user-images.githubusercontent.com/2096087/71857450-dfe31000-30e7-11ea-89d2-0f060355eb82.png)

Example of markdown used:

```md
1. Edit the content of the replace.txt file created as below
	```
	Copyright (c) 2015 - 2016 CompanyName, Inc.==>Copyright (C) 2016 Nishant Srivastava
	```
	some text(
1. Now go ahead clone a mirror of your project repo.

	```bash
	git clone — mirror https://github.com/username/your-project.git
	```
```

**Comment by zzossig** [comment]
Can you try 4 spaces for the indentation? 
It's strange.

before
```bash
  git clone — mirror https://github.com/username/your-project.git // 2 spaces
```

after
```bash
    git clone — mirror https://github.com/username/your-project.git // 4 spaces
```

**Comment by nisrulz** [comment]
You are right. However I was using tabs for indentation. It doesn't work with that either.

When I do 3 spaces manually, the zombie `` are gone.

**Comment by zzossig** [comment]
Maybe your tab is set to occupy 2 spaces in the vscode.
Since there is no international standard for rendering markdown, sometimes this kind of thing happens I think.

**Comment by zzossig** [comment]
I found another bug here. Will be fixed
![bik](https://user-images.githubusercontent.com/52706977/71858460-ae416780-312e-11ea-9561-90be9c5981ff.png)

**Comment by nisrulz** [comment]
Hmm..wasn't visible in standard view to me. Switching to chrome's responsive view made is visible. Good catch!

**Comment by nisrulz** [comment]
> Maybe your tab is set to occupy 2 spaces in the vscode.
> Since there is no international standard for rendering markdown, sometimes this kind of thing happens I think.

![Screenshot from 2020-01-07 01-23-34](https://user-images.githubusercontent.com/2096087/71858669-5a159380-30ec-11ea-8f0a-508e0c919d2a.png)

But I get your point. I made the relevant fix so my post look normal.

**Comment by zzossig** [comment]
Ok, I'll close this issue when I finished the above bug
