### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by theapplegates** [zzossig/hugo-theme-zzo#66]
Any chance you can code the Table of Contents to show on a cell/mobile phone  like this Hugo Theme does ? Here is the theme: https://github.com/dillonzq/LoveIt

Thanks

**Comment by zzossig** [comment]
Yes, It's a good feature. I'll make it soon

**Comment by theapplegates** [comment]
Thank you. I appreciate it. Love your theme. Keep up the great work.

**Comment by zzossig** [comment]
Now, we have another param named `enableTocContent`.
You can set the param in the Front Matter like this.

```yaml
---
title:
date:
...
enableTocContent: true
---
```
