### ISSUE TITLE
Archive lists link to about page at the very last page

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#70]
I just noticed this. When inside the archive page, the very last page is the link to about page with 
`0001` as number for date. 

- Archive page shouldn't list the about page.
- About page type shouldn't require a date value.

Screenshot from archive page:
![Screenshot from 2020-01-10 00-04-29](https://user-images.githubusercontent.com/2096087/72112047-cdaddf80-333c-11ea-8dfe-75e09bc0742a.png)

**Comment by zzossig** [comment]
Thank you for the issue! It will be fixed soon:)

**Comment by zzossig** [comment]
Thank you for the issue! It's fixed 😋

**Comment by nisrulz** [comment]
Just checked! Thank you.
