### ISSUE TITLE
The link text doesnot wrap in talk index page.

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#71]
The text goes out of the main content area into the black area.

![Screenshot from 2020-01-10 00-16-26](https://user-images.githubusercontent.com/2096087/72112692-a35d2180-333e-11ea-8274-555fb5665e7b.png)

> Since talk page is similar to archive page, I believe this issue will also be in archive index page.

**Comment by zzossig** [comment]
It will be fixed soon, too :)

**Comment by zzossig** [comment]
Thank you for the issue! I think it's fixed now 😋

**Comment by nisrulz** [comment]
Just checked! Thank you.

Question: After your update now the long title ends with `...` . Do you think wrapping the title to the next line is possible? This is also fine, but having the title wrap to next line without any text being cut off would be nice to have.

**Comment by zzossig** [comment]
Yes, it's maybe possible, but I think the UI might be ugly if we do that.

**Comment by nisrulz** [comment]
Makes sense. Will close this issue since this is fixed.

Thank you!
