### ISSUE TITLE
Title in the top bar is gone and logo distorted

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#73]
After the last update,when I updated the GitModule the title is gone and the logo distorted.

![Screenshot from 2020-01-10 07-44-46](https://user-images.githubusercontent.com/2096087/72131665-361cb100-337d-11ea-8554-423145069e41.png)

**Comment by zzossig** [comment]
I was about to upload it. just a sec

**Comment by zzossig** [comment]
I updated!

**Comment by nisrulz** [comment]
Thank you. Can confirm this is fixed.
