### ISSUE TITLE
Hi, can I ask you a question?

### ISSUE THREAD

**Issue by Briy09** [zzossig/hugo-theme-zzo#74]
on the homepage(index.html), how to display a list of posts in a specific category ?
Take [demo site](https://themes.gohugo.io//theme/hugo-theme-zzo/en/) as an example, I wang to the homepage display a list of posts that have a category with a value of `diagram` .
now, how to open the [homepage](https://themes.gohugo.io//theme/hugo-theme-zzo/en/), the articles displayed on index page are just like https://themes.gohugo.io//theme/hugo-theme-zzo/en/categories/diagram/
so how to change [layouts/index.html](https://github.com/zzossig/hugo-theme-zzo/blob/master/layouts/index.html), thank you!
![image](https://user-images.githubusercontent.com/49552463/72197949-19a67480-3462-11ea-9f09-111bf862ebeb.png)
refer:
https://discourse.gohugo.io/t/how-to-get-all-post-of-a-specific-param-categories/3106
https://stackoverflow.com/questions/48679091/how-to-display-only-1-post-from-certain-category-with-certain-params-true

**Comment by zzossig** [comment]
1. Make a file at `root/layouts/partials/summary/classic.html`
2. Copy-paste the file at `root/theme/zzo/layouts/partials/summary/classic.html`
3. Edit the red part in the image
![gg](https://user-images.githubusercontent.com/52706977/72198198-4744eb00-346d-11ea-99db-7b7fd8ad7dbd.png)

**Comment by zzossig** [comment]
If you have more questions, we can talk here
