### ISSUE TITLE
Refreshing or Loading a Page Will Cause "utteranc.es" To Use Default Theme

### ISSUE THREAD

**Issue by runewake2** [zzossig/hugo-theme-zzo#75]
When someone has applied a theme using the theme dropdown other than the default (in my examples I'm using the provided default light and dark themes) and the utteranc.es integration themes are not being correctly applied. While viewing a page with utteranc.es integrated if you select a new style/theme the updated colors will apply to the page (including utteranc.es). However if you then refresh or move to another page utteranc.es will revert back to using the default theme while the remainder of the site continues to use the newly selected theme.

In this example I've applied the light theme and refreshed. utteranc.es is using dark styling, but the rest of the page is light. This causes the "powered by utteranc.es" test to be nearly unreadable and the comment box to be a dark color against the rest of the white page.

![image](https://user-images.githubusercontent.com/1161329/72210461-d273b000-3470-11ea-9cda-f6ceb156963b.png)

If you select the theme from the dropdown it correctly applies the theme. However the theme is reset to the default (dark) style as soon as you refresh or load a new page.

![image](https://user-images.githubusercontent.com/1161329/72210468-e5868000-3470-11ea-8cee-21c2e9e71444.png)

Ideally the theme would persist beyond page reloads and as you navigate the site.

**Comment by zzossig** [comment]
I thought that I have fixed this issue [4f730f](https://github.com/zzossig/hugo-theme-zzo/commit/4f730fee5df91d2f01f94c81a5d2a2899db00f23#diff-cefa66ce782d28652c99a3811c04a0fb).
Are you using the latest version of the Zzo theme?

**Comment by runewake2** [comment]
I was about a week behind. Syncing resolved it. Thanks!
