### ISSUE TITLE
Theme switching is broken after last update

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#76]
I just updated the git sub module. Switching the theme from the drop down has no effect.

**Comment by nisrulz** [comment]
I also noticed click on the `^` button to goto top also doesn't work. Seems like last  few changes, broke some actions.

**Comment by zzossig** [comment]
I checked it on Ubuntu but seems to work well.
Do you have any error messages in the browser?

**Comment by nisrulz** [comment]
![Screenshot from 2020-01-12 14-06-41](https://user-images.githubusercontent.com/2096087/72219287-cf49f400-3544-11ea-95eb-26d414ca8ecb.png)

![Peek 2020-01-12 14-08](https://user-images.githubusercontent.com/2096087/72219334-4089a700-3545-11ea-947c-416cf3a8a006.gif)

I am clicking on all options in the drop down

**Comment by zzossig** [comment]
did you override the baseof.html file to yours?

**Comment by nisrulz** [comment]
No. I have not overridden anything. This is why I am able to update via the git Sub module.

**Comment by zzossig** [comment]
Can you delete `root/resource` folder? Hugo will generate a new one.

**Comment by nisrulz** [comment]
I did that. I restarted hugo server. No change.

**Comment by zzossig** [comment]
Can you check the download version of Zzo theme

1. download this repo
2. make folder `themes/test`
3. unzip the downloaded zip file to the `themes/test` folder
4. in your config.toml file(`config/_default/config.toml`)
```toml
...
theme = "test"
...
```

**Comment by nisrulz** [comment]
I don't understand this point:

unzip the downloaded zip file to the themes/test folder

I already downloaded this repo in first step.

**Comment by zzossig** [comment]
I suspect the git submodule crash some code.
So, just want to check if we use the source(not in git submodule) makes it work.

**Comment by nisrulz** [comment]
Tried that. Doesn't work either :/

**Comment by zzossig** [comment]
Can you share some repo?
I can't reproduce on my end even on Ubuntu environment

**Comment by nisrulz** [comment]
https://github.com/crushingcode/crushingcode-source/tree/new

**Comment by nisrulz** [comment]
I can tell you if I revert to last git sub module commit, the theme change works. It is definitely broken by last 2 commits.

**Comment by zzossig** [comment]
I reproduced it. I'll check what is happening behind.

**Comment by zzossig** [comment]
Ok, I found an unnecessary file
![주석 2020-01-12 231235](https://user-images.githubusercontent.com/52706977/72220147-0940e780-3591-11ea-9b23-e12bd4827571.png)
You have to delete the `layouts` folder. In this folder, scripts.html file override the theme's scripts.html file.

And replace `custom` to `kimbie`
![주석 2020-01-12 231404](https://user-images.githubusercontent.com/52706977/72220165-3f7e6700-3591-11ea-8b31-de140c3cc3e6.png)

**Comment by zzossig** [comment]
@nisrulz I added some options for the site header font.

You can set options in the `content/_index.md` file
![주석 2020-01-12 234708](https://user-images.githubusercontent.com/52706977/72220628-dfd68a80-3595-11ea-8006-930577bf343a.png)

**Comment by nisrulz** [comment]
Everything works now. Thank you for your help here :)
