### ISSUE TITLE
Images on home page posts ?

### ISSUE THREAD

**Issue by haciz** [zzossig/hugo-theme-zzo#78]
Hello, i couldn't find anywhere in the readme or issues here, how do i achieve to have image next to a post title on left side, like on the demo?
<img width="208" alt="Screenshot 2020-01-13 at 00 09 43" src="https://user-images.githubusercontent.com/5979035/72227114-0813b880-3599-11ea-9155-978edf9ca66b.png">
Many Thanks!

**Comment by zzossig** [comment]
Can you check the files at example site?‘exampleSite/content/posts/test-flowchart.md’

You can see the featured_image front matter.

**Comment by zzossig** [comment]
I'm closing this issue.
But We can talk more here if you have any questions.

**Comment by haciz** [comment]
Excellent, thats what I was looking for :) i have one more question, how to lower the font size of a post tittle when its opened, if thats possible? Thanks a lot!

**Comment by zzossig** [comment]
It's not possible. we are not that much optimizable.
