### ISSUE TITLE
Text on header hero section shouldn't change with theme

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#79]
Here is the problem:
![ezgif com-resize](https://user-images.githubusercontent.com/2096087/72227591-bc640d80-359e-11ea-9b46-43af3bd45bc4.gif)

So since the background image doesn't switch with the theme, but the text in the header section does with change in theme, when one selects the theme as `light`, the text is rendered darker. Since the background is still the same, the text is not readable. 

I see few possible solutions:
- The text color shouldn't change when changing themes only for the header section.
- There is a css tint on the background image, say for example when it is light theme the tint is white and the text changes to dark. When `dark` theme is selected the tint is dark and the text changes to white.
- There is a an ability to tie a background image to each theme.
- I can just delete the text and put a background that has the text as part of the background image.

Personal choice is point 1 above.

What do you think?

**Comment by zzossig** [comment]
I think option1 is better.
I thought that I did implement it but it was not
I'll add the option `titleColor` in the header index file.

```yaml
---
...
- type: img
    ...
    titleColor: green
    ...
...
---
```

**Comment by zzossig** [comment]
I uploaded!

**Comment by nisrulz** [comment]
Although it fixed this issue, but now the whole blog is not responsive. I opened other issue #80 where there was a white bar at the right side and the header was not responsive. After your change, now the whole blog is not responsive :thinking: 

![Screenshot from 2020-01-13 01-15-46](https://user-images.githubusercontent.com/2096087/72227931-42358800-35a2-11ea-82f5-70f1487c88ba.png)

**Comment by zzossig** [comment]
Ok, I'll find out what's going on

**Comment by nisrulz** [comment]
This is also fixed.

Thank you :tada:
