### ISSUE TITLE
TOC is drawn outside of the sidebar

### ISSUE THREAD

**Issue by pastalian** [zzossig/hugo-theme-zzo#8]
`.toc` has `max-width: 250px` but sidebar width could go under 250px.

example:
![19-11-15_232413](https://user-images.githubusercontent.com/28638872/68950275-29596200-07ff-11ea-84b3-d593cdbf998c.png)

**Comment by zzossig** [comment]
This should be fixed. I'll look into it.

**Comment by zzossig** [comment]
@pastalian Can you update new version and check if it's fine now?
Feel free to suggest any other things.

**Comment by pastalian** [comment]
Thanks, it's working fine now.
This theme is great and I appreciate all your work!
