### ISSUE TITLE
Blog has issues with being responsive

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#80]
Here are some examples:
![Screenshot from 2020-01-13 01-08-58](https://user-images.githubusercontent.com/2096087/72227867-968c3800-35a1-11ea-8d1b-ff05d7d1b4b4.png)
![Screenshot from 2020-01-13 01-09-14](https://user-images.githubusercontent.com/2096087/72227869-968c3800-35a1-11ea-82bc-0d8fb32f9abb.png)
![Screenshot from 2020-01-13 01-09-22](https://user-images.githubusercontent.com/2096087/72227870-968c3800-35a1-11ea-9bc7-860743c16cbb.png)
![Screenshot from 2020-01-13 01-09-36](https://user-images.githubusercontent.com/2096087/72227871-968c3800-35a1-11ea-92d1-b5299cc5339a.png)

- Notice the white space on the side.
- Notice if I just have the background image for the header, it is not scaled down to fill the container but is cut off from the sides.

How to test:
1. Right click and select inspect
1. Select mobile view and then change width. 
1. Select devices option from the top bar. It breaks for iPhone 5/6/7 and Samsung Galaxy devices.

**Comment by zzossig** [comment]
Thank you for the issue!
I'll fix it soon😊

**Comment by zzossig** [comment]
I found that your `update-dependencies-code-repeat.md` file,
the browser doesn't wrap the title `Update Dependencies.Code.Repeat`

**Comment by nisrulz** [comment]
You mean this:
![Screenshot from 2020-01-13 01-35-22](https://user-images.githubusercontent.com/2096087/72228205-018b3e00-35a5-11ea-8e3a-ad67fdab52fe.png)

**Comment by nisrulz** [comment]
> I found that your `update-dependencies-code-repeat.md` file,
> the browser doesn't wrap the title `Update Dependencies.Code.Repeat`

I have bigger titles than just that. I think the longest is this: "I could not find a simple Gesture Detection android library, so I built one"

**Comment by zzossig** [comment]
Can you edit the `update-dependencies-code-repeat.md` file

this
```yaml
title = "Update Dependencies.Code.Repeat."
```

to this
```yaml
title = "Update Dependencies .Code. Repeat."
```

add space between `.`

**Comment by zzossig** [comment]
I updated to wrap the summary title

**Comment by nisrulz** [comment]
Whatever change you made, fixed the responsive issue. Now the blog fits in all phone sizes. I just tested! :tada: 

The only question to ask is can the background image for header also scale down to fit ?

**Comment by zzossig** [comment]
Can you try to change the imageSize param?
```yaml
- type: img
    ...
    imageSize:
    ...
```
imageSize: auto | length | cover | contain | initial | inherit

If it does not solve the problem, tell me

**Comment by nisrulz** [comment]
I think `contain` works. I am looking into making it work. I think this issue can be closed.

Thank you :)
