### ISSUE TITLE
The font is different for post text and title.

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#81]
Usually the blog should use the same font though out. However the theme is setting different fonts for summary/post body and title.

Example:
![Screenshot from 2020-01-13 01-19-31](https://user-images.githubusercontent.com/2096087/72227993-eb7c7e00-35a2-11ea-8570-d41cd77d6244.png)

**Comment by zzossig** [comment]
In case you want to change the font used in the summary part, you have to override the theme's data file. Follow these steps.

1. Make a folder `root/data`
2. make a file `root/data/font.toml`
3. font.toml file
```toml
content_font = "\"Montserrat\", sans-serif"
```
This will solve the problem

**Comment by nisrulz** [comment]
Will this get overridden when I update the git sub module?

**Comment by zzossig** [comment]
No, you have to make a `font.toml` file in `root/data`

**Comment by nisrulz** [comment]
Hmm.. I tried. It didn't change :thinking:

**Comment by zzossig** [comment]
restart hugo?

**Comment by nisrulz** [comment]
Tried.

**Comment by nisrulz** [comment]
![Screenshot from 2020-01-13 01-33-54](https://user-images.githubusercontent.com/2096087/72228177-c852ce00-35a4-11ea-979c-6fd6f1747eee.png)

**Comment by zzossig** [comment]
Did you tried `content_font = "\"Merriweather\", serif"`?

**Comment by nisrulz** [comment]
Yes and the font didn't change either. I check the css.

Disabling the css of font-family, fixes things.

![Screenshot from 2020-01-13 01-37-14](https://user-images.githubusercontent.com/2096087/72228228-4616d980-35a5-11ea-908a-cd320b441e8c.png)

**Comment by zzossig** [comment]
Did you tried force refresh the browser?
`ctrl+shift+r`

**Comment by nisrulz** [comment]
You are right. I had to hard reset the cache and reload the page. 

I guess I should do that before opening any issue :sweat_smile: [restart server, hard reset page]

Thanks! 

Closing this issue.

**Comment by zzossig** [comment]
No, it's Ok. Feel free to open a new issue. 
I'll document this in the future
