### ISSUE TITLE
When header is in text mode and left aligned, the title and subtext is not aligned

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#83]
![Screenshot from 2020-01-13 02-39-30](https://user-images.githubusercontent.com/2096087/72229315-01437080-35ae-11ea-845f-f871a1d9601e.png)

![Screenshot from 2020-01-13 02-41-03](https://user-images.githubusercontent.com/2096087/72229340-2a640100-35ae-11ea-8f07-88df23455282.png)

**Comment by nisrulz** [comment]
Nevermind, I figured.

```header:
  - type: text
    height: 200
    paddingX: 32
    paddingY: 0
    align: left```

Had to set `paddingX: 32`

**Comment by nisrulz** [comment]
![Screenshot from 2020-01-13 02-44-09](https://user-images.githubusercontent.com/2096087/72229397-98102d00-35ae-11ea-83a6-3f6e4461355a.png)


Although, "T" is still out by 1 px, I think. :thinking:

**Comment by zzossig** [comment]
I didn't add margin or padding on the subtitle.
Maybe the browser interprets and prints UI like that.
Do you think it's better to add a margin to the subtitle?

**Comment by nisrulz** [comment]
No, it can also be the font itself. I will look into this later. I don't think this is a huge issue.
