### ISSUE TITLE
How to support multi author's avatar?

### ISSUE THREAD

**Issue by ringsaturn** [zzossig/hugo-theme-zzo#84]
I'm trying to use these theme for my team blog, and I hope there is a way to show author's avatars.

**Comment by zzossig** [comment]
Can you tell me more specific? We already have avatar section
![주석 2020-01-15 003427](https://user-images.githubusercontent.com/52706977/72357737-cd438900-372e-11ea-9fcf-4338548f4376.png)

**Comment by zzossig** [comment]
Did you mean this part?
![주석 2020-01-15 003512](https://user-images.githubusercontent.com/52706977/72357793-ea785780-372e-11ea-9ef8-86fd0ace7aa0.png)

**Comment by zzossig** [comment]
I’m closing this issue since we already have this feature

**Comment by ringsaturn** [comment]
Thanks!

I missed this from readme.
