### ISSUE TITLE
forestry cms

### ISSUE THREAD

**Issue by tudorsaitoc** [zzossig/hugo-theme-zzo#85]
Trying to load up blog through Forestry.io and Netlify.  When importing the site, I get an import failure even though it seems to be pointing to correct config files at `example/Site/config/_default`.  

Think you could help me out?

**Comment by zzossig** [comment]
Sorry, but I never used cms before.
And I don't understand the concept of cms and why it is needed.
If this theme works well in the local environment, then, my job is done.
Maybe you can get help in the Hugo community [https://discourse.gohugo.io/](https://discourse.gohugo.io/)
