### ISSUE TITLE
Can the pictures in the gallery use the picture bed?

### ISSUE THREAD

**Issue by Codeapes666** [zzossig/hugo-theme-zzo#86]
Hi, my friend. The access speed in github in China is not very fast. If  use a static image, loading the webpage will become slow.

It would be nice,  if the pictures of the gallery could be used Markdown Code.

like this(By the way, do you like her? hahaha):

[![lxnyrR.md.jpg](https://s2.ax1x.com/2020/01/16/lxnyrR.md.jpg)](https://imgchr.com/i/lxnyrR)

**Comment by zzossig** [comment]
Yes, I like her😋
So, what you want is that you make a gallery page written in a markdown file. 
Is that so?

**Comment by Codeapes666** [comment]
Yes, That's what I meant .

I hope you can not only share the technology, but also share some customs and customs of South Korea. I am very interested in it.

Sincerely thank you, my friend.

**Comment by zzossig** [comment]
Hey bro, I just found that I already make it like that.
You just need to delete the file at `root/partials/head/scripts.js`
I told you before that you override the file because of the baseURL issue.
But this file prevents you from using updated code.
Just try it out to delete the `scripts.js` file

**Comment by Codeapes666** [comment]
Thank you.
