### ISSUE TITLE
Side bar on right under Posts page listed same items as on main page

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#89]
![Screenshot from 2020-01-18 14-04-00](https://user-images.githubusercontent.com/2096087/72664309-999d8300-39fc-11ea-8a80-909f700f19e6.jpg)

I think this sidebar should only list : Tags, Series and Categories.

Re-listing the posts looks redundant.

Your thoughts?

**Comment by zzossig** [comment]
I agree with you.
I'll make new param to hide the sidebar post title

**Comment by zzossig** [comment]
I added a param `enableListSidebarTitles`
Set the param value to `false` to hide titles

**Comment by nisrulz** [comment]
Works :tada: 

Thank you :smile:

**Comment by nisrulz** [comment]
Just noticed this also happens on the main page

![Screenshot from 2020-01-18 22-14-12](https://user-images.githubusercontent.com/2096087/72670636-f1111280-3a3f-11ea-97c9-bcb8b467e78d.png)

**Comment by zzossig** [comment]
I added a param `enableHomeSidebarTitles`
Set the param value to `false` to hide titles
