### ISSUE TITLE
enableGoToTop not implemented yet?

### ISSUE THREAD

**Issue by wolexa** [zzossig/hugo-theme-zzo#9]
config.toml contains a parameter "enableGoToTop". If it is set to true (like in the example site), there still doesn't seem to appear any button, symbol or link to jump to the top of the page. But then, maybe that's not the meaning of this parameter?

**Comment by zzossig** [comment]
![footer](https://user-images.githubusercontent.com/52706977/69006650-65163800-0975-11ea-9d89-a52dbca8f45b.png)
If you set the parameter "enableGoToTop", you can see the button shown in the image I attached. I'm not sure which position is the best to put go-to-top button.

**Comment by wolexa** [comment]
Ah, thanks for pointing this out to me! It is very subtle and, in fact, on my computer is neither visible in the examplesite (which has "enableGoToTop" set to true in all relevant files), nor in my own site.

Is it correct to assume that once Hugo has rendered the whole site, i.e. once the final HTML code is being created, that the HTML source would still contain a reference to "keyboard-arrow-up.svg"? If so, then something must be wrong because I cannot see any such reference in the generated HTML source code (as created by "hugo server").

**Comment by zzossig** [comment]
Hmm, Mayby, your site doesn't have some content in it. Right? Go-to-top button only show when you scroll down to more than 500px (offset top to 500px). This is because If we are in near the top page, we don't need the GTT botton.
