### ISSUE TITLE
[Suggestion] Improving simple performance points can help the theme perf score

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#90]
One can run audits on a website to know about issues that exists in the website.

To do so, you Right Click on the page, select Inspect Element, Goto Audit Tab and then run audit.

![Screenshot from 2020-01-18 14-29-19](https://user-images.githubusercontent.com/2096087/72664515-21848c80-39ff-11ea-9882-f51ad667097a.png)

Apart from scoring the webpage, suggestions are also provided for things that can be fixed.

Worth taking a look.

**Comment by zzossig** [comment]
Actually, I already take care of the score😋.
I already removed the jquery for the performance.
And changed all the heavy library to the light one(gallery, header slide).
Maybe, we can get more scores in the SEO part.

**Comment by nisrulz** [comment]
Yes, I know. I was thinking that you haven't looked at this option. Good that you know.

**Comment by zzossig** [comment]
Ah, I misunderstood. I didn't read this part.
>Apart from scoring the webpage, suggestions are also provided for things that can be fixed.

Ok, I'll take a look at what options can be used in the theme

**Comment by Gictorbit** [comment]
also, it could be awesome to add these features:
1. link preview for posts with a photo as cover like this:
https://telegram.org/blog/link-preview
-----
2. share button for telegram and WhatsApp
-----
3.  telegram `Instant View` for blog posts
https://instantview.telegram.org/

**Comment by zzossig** [comment]
@nisrulz I audit my blog today and inspected some options.
But I think I did everything I could.
If you can point me some specific option that I should fix, just open a new issue.

@Gictorbit I made a new issue regarding this since this issue is a new subject.
Always feel free to make a new issue.
I prefer to keep one subject in one issue.
