### ISSUE TITLE
Does the gallery support the paginate function?

### ISSUE THREAD

**Issue by xiaohao890809** [zzossig/hugo-theme-zzo#91]
Hi, if the gallery has many photos, can it support the paginate function to show the photos?

**Comment by zzossig** [comment]
No, the gallery page has no pagination.
Just make a new menu.
Actually, I was thought about it but give up for some reason.

**Comment by xiaohao890809** [comment]
> No, the gallery page has no pagination.
> Just make a new menu.
> Actually, I was thought about it but give up for some reason.

Thank you for your reply, I really like this theme.
