### ISSUE TITLE
[Suggestion] Project Showcase Page

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#92]
I was looking at integrating a page which would act like a project showcase. Something like [gitshowcase.com/nisrulz](https://www.gitshowcase.com/nisrulz)

It doesn't have to be exactly like this, but having a ability to define "Links" that look like cards would be a nice addition to this theme.

Something like this:
![Screenshot from 2020-01-18 23-41-38](https://user-images.githubusercontent.com/2096087/72671537-65ea4980-3a4c-11ea-8959-761f54391aa9.png)

What do you think?

**Comment by zzossig** [comment]
I think it's good for other people too.
I'll think about the design(this is always the hardest part for me)

**Comment by zzossig** [comment]
I made the showcase page. [https://github.com/zzossig/hugo-theme-zzo#showcase-page](https://github.com/zzossig/hugo-theme-zzo#showcase-page)

Also, I added an option to wrap the title in the Archive, Talks page. We talked before here [https://github.com/zzossig/hugo-theme-zzo/issues/71#issuecomment-572897977](https://github.com/zzossig/hugo-theme-zzo/issues/71#issuecomment-572897977)

To wrap the title in your Archive, Talks page, set the `titleWrap` to `wrap` in the file at `root/content/archive or talks/_index.md`
```yaml
title:
date:
...
titleWrap: wrap # wrap title
```

**Comment by nisrulz** [comment]
Can you post a screenshot too? I am at work, but would like to see the what you implemented 😅

**Comment by zzossig** [comment]
Look at my blog [https://zzossig.io/showcase/](https://zzossig.io/showcase/)

**Comment by nisrulz** [comment]
Wow, looks cool 🎉 

3 suggestions:
1. Making the whole card as the link, would make more sense instead of just the title and the repository link. Why, because they both link to the same link so having them as two different things is not very accessible.

<img width="324" alt="Screen Shot 2020-01-20 at 10 02 36 AM" src="https://user-images.githubusercontent.com/2096087/72712771-03886a80-3b6c-11ea-814c-8b1ddfd9d359.png">

2. The profile being moved to the left, changes the theme style. The home page has it on the right and the showcase has it on the left. The suggestion I have is that it stays the same based on a param. If say someone chooses left, the home page and showcase both have it on the left. If someone chooses right the showcase and the home page have it on the right. This is even better for the theme as it lets user select which side they want their info be shown.

3. Having the search bar here too would be really helpful.

I would like to mention, I really appreciate your quick responses and efforts in making these changes in the theme. Thank you 😸

**Comment by zzossig** [comment]
Interesting suggestion!
I never thought about switching position the bio component.

**Comment by zzossig** [comment]
3 suggestions done

We have a new param `sidebarPosition`.

params.toml
```toml
...
sidebarPosition = "left" # left / right
...
```

**Comment by nisrulz** [comment]
Wow that was quick. I checked it on your blog. 

I will update my blog and add more comments here when I get home.

Thank you 🎉

**Comment by zzossig** [comment]
I’m going to bed now. Leave a comment if something needs to be fixed. I’ll check it tomorrow 😀

**Comment by nisrulz** [comment]
When I click on the tag in the top bar, I see a broken box. The description is not wrapped and there is an extra title.

![Screenshot from 2020-01-20 18-57-26](https://user-images.githubusercontent.com/2096087/72748226-e927ae80-3bb6-11ea-9256-d67819837445.png)

However the one under the "Overview" works

![Screenshot from 2020-01-20 18-57-34](https://user-images.githubusercontent.com/2096087/72748238-fa70bb00-3bb6-11ea-88b9-531e203d3683.png)

**Comment by nisrulz** [comment]
Also without the bio, the width of the card changes.

![Screenshot from 2020-01-20 19-03-20](https://user-images.githubusercontent.com/2096087/72748449-91d60e00-3bb7-11ea-922b-36f1c1a8701e.png)

**Comment by zzossig** [comment]
You have to set thumb to the relative path for the image.

![1](https://user-images.githubusercontent.com/52706977/72776069-2b52fd80-3c54-11ea-85c4-caf5dc350d0e.png)
![2](https://user-images.githubusercontent.com/52706977/72776070-2b52fd80-3c54-11ea-9da2-59ffec45286c.png)

```yaml
...
thumb: "showcase/android/easydeviceinfo.png" 
...
```

I also changed card component CSS little a bit for considering the bio component

**Comment by nisrulz** [comment]
Yes. I understand that.

I think the point here is that not all cards here will have a thumbnail.So `thumb: ""` is valid and should be reflected in the final html.

**Comment by zzossig** [comment]
Ah, I see, you are right!

**Comment by nisrulz** [comment]
But the PR I had opened was supposed to fix it. I don't see why it doesn't work. I check if the Param.thumb is not set or is "" and then don't show thumbnail part  :thinking:

**Comment by zzossig** [comment]
I'll take care of the empty value.
We can use `{{ with .thumb }} {{end}}` syntax.

**Comment by zzossig** [comment]
I used `{{ if }}{{ end }}` syntax and it worked😁
And the maximum card component in one row limited 2, instead of 3 for making responsiveness.

**Comment by zzossig** [comment]
Ah, I didn't update my blog yet😅

**Comment by nisrulz** [comment]
This is fixed. Closing :)
