### ISSUE TITLE
Post title should wrap at word level and not at character level

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#96]
![Screenshot from 2020-01-20 21-30-42](https://user-images.githubusercontent.com/2096087/72756013-48dc8480-3bcc-11ea-810d-ded01879133a.png)

Note that the "You" breaks at "Yo" and continues on second line "u". It should wrap as a full word "You"

**Comment by zzossig** [comment]
When we use `break-word` instead of `break-all`, It sometimes doesn't wrap the title and makes layout unresponsive 
![72764245-8c90b780-3be7-11ea-8c5d-b887d5dfa733](https://user-images.githubusercontent.com/52706977/72765611-9d195000-3c30-11ea-992e-ded556012cda.png)
