### ISSUE TITLE
Showcase pinning and category doesn't work properly

### ISSUE THREAD

**Issue by nisrulz** [zzossig/hugo-theme-zzo#98]
![Peek 2020-01-21 00-25](https://user-images.githubusercontent.com/2096087/72763594-bbf1f500-3be4-11ea-8c4c-c9af3f389eb6.gif)

Points to note:
Switching between "Overview" and "Android" here changes the number tagged on "Android".. switches between 1 and 4,

**Comment by nisrulz** [comment]
Here is the latest code pushed to the source for my blog: https://github.com/crushingcode/crushingcode-source

**Comment by zzossig** [comment]
I can't reproduce this issue.
Even your blog works well!

**Comment by nisrulz** [comment]
Can't reproduce either anymore. Closing.
